.github/actions/kustomize/Dockerfile, .github/actions/kustomize/action.yml, .github/actions/kustomize/entrypoint.sh, .github/workflows/e2e.yaml, .github/workflows/release.yaml, .goreleaser.yml, Makefile, README.md, cmd/tk/check.go, cmd/tk/create.go, cmd/tk/create_source.go, cmd/tk/install.go, cmd/tk/main.go, cmd/tk/uninstall.go, go.mod, go.sum, manifests/bases/kustomize-controller/kustomization.yaml, manifests/bases/source-controller/kustomization.yaml, manifests/install/kustomization.yaml, manifests/install/labels.yaml, manifests/install/namespace.yaml, manifests/policies/deny-ingress.yaml, manifests/policies/kustomization.yaml, manifests/rbac/cluster_role.yaml, manifests/rbac/kustomization.yaml, manifests/rbac/role.yaml
Changes:
- add check command 
+ kubectl >=1.18.0
+ kustomize >=3.5.0
+ kubernetes >=1.14.0
- add install manifests
+ RBAC role for CRs
+ RBAC cluster role for kustomize reconciler
+ deny ingress network policy
- add install command with dry-run option
- add uninstall command with dry-run option
+ prompt for confirmation
- add create source command for Git repositories
+ generate secret for basic-auth credentials
+ generate SSH host and deploy keys
+ generate secret for SSH keys
+ prompt for deploy key setup
- add end-to-end tests for:
+ check
+ install (local manifests)
+ create source (public repository)
=> Implement check, install, uninstall and create source commands

.github/workflows/e2e.yaml, cmd/tk/get.go, cmd/tk/get_kustomization.go, cmd/tk/get_source.go, cmd/tk/get_source_git.go, cmd/tk/sync_kustomization.go
Changes:
- add get sources git command
+ list git sources and their revisions or the failed sync messages
- add get kustomizations command
+ list kustomizations and their last applied revisions or the failed apply messages
=> Implement get commands

manifests/bases/kustomize-controller/cluster_role.yaml, manifests/bases/kustomize-controller/kustomization.yaml, manifests/bases/kustomize-controller/patch.yaml, manifests/rbac/kustomization.yaml
Changes:
- add cluster reconciler RBAC and SA for kustomize controller
- bump kustomize controller version to v0.0.1-alpha.6
=> manifests: add cluster reconciler RBAC and SA

.github/workflows/e2e.yaml, manifests/bases/kustomize-controller/kustomization.yaml, manifests/bases/kustomize-controller/patch.yaml, manifests/rbac/cluster-role.yaml, manifests/rbac/kustomization.yaml, manifests/rbac/role.yaml
We should set the controllers to watch only the runtime namespace for CRs. Until then, the cluster role binding is required on both controllers.
=> manifests: fix leader election rbac

manifests/policies/deny-ingress.yaml
Allow intra-namespace traffic, e.g. kustomize-controller -> source-controller.
=> Fix deny traffic from other namespaces

.goreleaser.yml, cmd/tk/main.go, go.mod, go.sum, manifests/bases/kustomize-controller/kustomization.yaml, manifests/bases/source-controller/kustomization.yaml
Changes:
- set tk version at release time 
- update kustomize/api to v0.4.1
- update source-controller to v0.0.1-beta.1
- update kustomize-controller to v0.0.1-beta.1
=> Update controllers to v0.0.1-beta.1

cmd/tk/bootstrap_github.go
This PR adds an optional flag to the bootstrap command that allows specifying a repository path where the manifests will be placed. When a path is specified, the cluster sync is configured for the target path. Using a path per cluster, a repository can be used to define the desired state of a fleet of clusters.
=> Add target path to the bootstrap cmd

cmd/tk/bootstrap_github.go, cmd/tk/get_kustomization.go
This PR allows cluster admins to assign org teams during bootstrap. The teams are added with maintain permissions.
=> Assign GitHub teams during bootstrap

cmd/tk/flags.go
To ensure options are always printed in the same order.
=> Sort supported ECDSA curves names

cmd/tk/install.go, docs/cmd/tk_install.md
Add export option to `tk` so that it can be used to write the install manifests to a file with:
```
tk install --export > gitops-toolkit.yaml
```
Fix: #98
=> Add export option to tk install

cmd/tk/bootstrap.go, cmd/tk/install.go, cmd/tk/main.go, cmd/tk/utils.go, docs/cmd/tk_bootstrap.md, docs/cmd/tk_bootstrap_github.md, docs/cmd/tk_bootstrap_gitlab.md, docs/cmd/tk_install.md
Instead of cloning the components repositories to download the base manifests, we [build them in CI at release time](https://github.com/fluxcd/toolkit/blob/master/.github/workflows/release.yaml) and download them in `tk install/bootstrap` based on the provided semver. This speeds up the manifests generation from minutes to milliseconds.
=> Use semver manifests as kustomize base

docs/roadmap/index.md
.. and rearrange the line items a little. I removed the mention of source-controller because it doesn't feature in the design as drafted.
=> Link to image update discussion

docs/proposals/go-git-providers.md
Let's unify talking to Git providers once and for all with a new repo & library: `go-git-providers` :tada:
cc @stefanprodan @hiddeco @squaremo @martina-if @bboreham
=> Add go-git-providers proposal

.github/workflows/e2e.yaml, cmd/tk/create_helmrelease.go, cmd/tk/delete_helmrelease.go, cmd/tk/utils.go, docs/cmd/tk_create.md, docs/cmd/tk_create_helmrelease.md, docs/cmd/tk_delete.md, docs/cmd/tk_delete_helmrelease.md, go.mod, mkdocs.yml
Create command:
```
$ tk create hr podinfo \
--target-namespace=default \
--source=podinfo \
--chart-name=podinfo \
--chart-version=">4.0.0 <5.0.0" \
--values=./bin/values.yaml
✚ generating release
► applying release
✔ release created
◎ waiting for reconciliation
✔ release podinfo is ready
✔ applied revision 4.0.6
```
Delete command:
```
$ tk delete hr podinfo
◎ This action will remove the Kubernetes objects previously applied by the podinfo Helm release!
Are you sure you want to delete this Helm release: y
► deleting release podinfo in gitops-system namespace
✔ release deleted
```
Ref: #117
=> Implement create/delete for Helm releases

cmd/tk/install.go, cmd/tk/main.go, cmd/tk/utils.go
If one chooses to install the toolkit components without notification-controller, the installed controllers should only create Kubernetes events. This PR adds a patch to the controllers args to remove the events address when notification-controller is not one of the selected components.
=> Make notification component optional

docs/guides/sealed-secrets.md, mkdocs.yml
Add a guide for deploying the sealed-secrets controller with a `HelmRelease` and explain how kubeseal can be used to safely store secrets in Git repositories.
=> Add sealed secrets guide

cmd/tk/uninstall.go, docs/cmd/tk_uninstall.md
Remove Kustomizations, GitRepositories and HelmRepositories before deleting the toolkit controllers and CRDs. This ensures that GC finalizers are processed before control plane deletion.
=> Delete custom resources during uninstall

cmd/tk/bootstrap.go, cmd/tk/install.go, docs/cmd/tk_bootstrap.md, docs/cmd/tk_bootstrap_github.md, docs/cmd/tk_bootstrap_gitlab.md, docs/cmd/tk_install.md
Changes to install and bootstrap commands:
- Add container registry optional arg 
- Add image pull secret optional arg
Example of installing the toolkit using images from a private repository:
```sh
tk install \
--namespace=gitops-system \
--components=source-controller,kustomize-controller \
--registry=registry.internal/fluxcd \
--image-pull-secret=regcred
kubectl -n gitops-system create secret generic regcred \
--from-file=.dockerconfigjson=/.docker/config.json \
--type=kubernetes.io/dockerconfigjson
```
=> Add container registry and image pull secret as install options

cmd/tk/main.go, docs/cmd/tk.md
Remove `tk sync` example from help command
=> Remove tk sync example from help command

cmd/tk/create_kustomization.go, cmd/tk/create_source_git.go, cmd/tk/create_source_helm.go
=> Make export work offline

install/tk.sh
Add support for checksum verification
=> Add checksum verification to install script #24

cmd/tk/create_helmrelease.go, cmd/tk/reconcile_helmrelease.go
=> Fix: change v1.JSON for HelmRelease to pointer

docs/guides/installation.md, docs/guides/sealed-secrets.md
Issues:
- `✗ unknown flag: --chart-name`
- `✗ chart name or path is required`
- `✗ source must be in format <kind>/<name>`
- `✗ semver range parse error: Could not parse Range "^1.10.0": Could not parse comparator "^" in "^1.10.0"`
=> Docs: fix gotk create helmrelease examples

cmd/gotk/create_helmrelease.go, docs/cmd/gotk_create_helmrelease.md
To better reflect optional fields and highlight specific configuration
options.
=> Update `gotk create helmrelease` examples

cmd/gotk/bootstrap.go, cmd/gotk/install.go, docs/cmd/gotk_bootstrap.md, docs/cmd/gotk_bootstrap_github.md, docs/cmd/gotk_bootstrap_gitlab.md, docs/cmd/gotk_install.md, docs/guides/installation.md
Use GitHub Container Registry instead of Docker Hub for the toolkit controller images linux/amd64 and arm64.
Fix: #194
=> Use GitHub Container Registry for AMD64/ARM64 images

.github/workflows/release.yaml, .goreleaser.yml, docs/get-started/index.md, docs/guides/installation.md
Changes:
- Publish Homebrew formula to [fluxcd/homebrew-tap](https://github.com/fluxcd/homebrew-tap) repo from CI with goreleaser 
- Add brew install instructions to docs
=> Publish Homebrew formula

cmd/gotk/create.go, cmd/gotk/create_helmrelease.go, cmd/gotk/create_kustomization.go, cmd/gotk/create_source_git.go, cmd/gotk/create_source_helm.go, cmd/gotk/export_helmrelease.go, cmd/gotk/export_kustomization.go, cmd/gotk/export_source_git.go, cmd/gotk/export_source_helm.go, docs/cmd/gotk_create.md, docs/cmd/gotk_create_helmrelease.md, docs/cmd/gotk_create_kustomization.md, docs/cmd/gotk_create_source.md, docs/cmd/gotk_create_source_git.md, docs/cmd/gotk_create_source_helm.md
This PR adds support for defining labels when creating or updating the toolkit resources.
Example:
```sh
gotk create source git podinfo \
--url=https://github.com/stefanprodan/podinfo \
--label=toolkit.fluxcd.io/env=dev \
--label=toolkit.fluxcd.io/role=app
```
=> Add label arg to create commands

.github/workflows/bootstrap.yaml, cmd/gotk/bootstrap.go, cmd/gotk/bootstrap_github.go, cmd/gotk/bootstrap_gitlab.go, docs/cmd/gotk_bootstrap.md, docs/cmd/gotk_bootstrap_github.md, docs/cmd/gotk_bootstrap_gitlab.md, docs/guides/installation.md
This allows changing the bootstrap branch name for existing repositories or when the GitHub organization default branch is set to something else than master.
Fix: #169
=> Add branch flag to bootstrap cmd

manifests/rbac/role.yaml
During high custom resource count / low interval tests, I was greated
with a `cannot patch resource "events"` message. This happened due to
event compaction, where it will perform a patch instead of a create.
By giving the role the permission to do so this should no longer pose
a problem.
=> Add PATCH rule to crd-controller role for events

cmd/gotk/bootstrap.go, cmd/gotk/install.go, docs/cmd/gotk_bootstrap.md, docs/cmd/gotk_bootstrap_github.md, docs/cmd/gotk_bootstrap_gitlab.md, docs/cmd/gotk_install.md
This PR adds the `--watch-all-namespaces` flag to gotk install and bootstrap commands. 
With  `--watch-all-namespaces` (defaults to `true`) users can configure the toolkit controllers to watch for custom resources in all namespaces, if set to `false` it will only watch the namespace where the toolkit is installed.
Fix: #224
=> Add watch all namespaces flag

cmd/gotk/bootstrap.go, cmd/gotk/bootstrap_github.go, cmd/gotk/bootstrap_gitlab.go, cmd/gotk/install.go, cmd/gotk/main.go, docs/cmd/gotk_bootstrap.md, docs/cmd/gotk_bootstrap_github.md, docs/cmd/gotk_bootstrap_gitlab.md, docs/cmd/gotk_install.md
This PR adds the `--log-level` flag (defaults to `info`) to gotk install and bootstrap commands.
=> Add log level flag

cmd/gotk/completion_bash.go, cmd/gotk/completion_fish.go, cmd/gotk/completion_powershell.go, cmd/gotk/completion_zsh.go, docs/cmd/gotk.md, docs/cmd/gotk_completion.md, docs/cmd/gotk_completion_bash.md, docs/cmd/gotk_completion_fish.md, docs/cmd/gotk_completion_powershell.md, docs/cmd/gotk_completion_zsh.md, docs/get-started/index.md
Was running through the `get-started.md` and noticed we didn't have zsh support.
I use zsh, so I figured I'd add it along /w Cobra's other supported shells.
This sub-command approach is the same one used by `kind`.
It's also similar to `kubectl`, except they just use an argument instead of dedicated sub-commands.
=> Support bash, fish, zsh, and powershell shell completions as separate sub-commands

.goreleaser.yml, cmd/gotk/install.go, cmd/gotk/main.go, docs/get-started/index.md, docs/guides/installation.md
This adds `--arch=arm` to install/bootstrap for cluster with ARMv7 nodes. On the next release, gotk binaries for amd64, arm64 and arm/v7 will be made available on the release page.
Fix: #246
=> Add support for ARMv7

cmd/gotk/uninstall.go, docs/cmd/gotk_uninstall.md, docs/guides/installation.md
Changes:
- suspend bootstrap kustomization on uninstall to avoid namespace hanging on finalizers
- remove all custom resources by default on uninstall
- remove all custom resources before CRDs
- add uninstall section to install guide
Ref: #251
=> Suspend bootstrap kustomization on uninstall

cmd/gotk/create_helmrelease.go, cmd/gotk/create_kustomization.go, cmd/gotk/main.go, cmd/gotk/reconcile_helmrelease.go, cmd/gotk/reconcile_kustomization.go, cmd/gotk/reconcile_source_bucket.go, cmd/gotk/reconcile_source_git.go, cmd/gotk/reconcile_source_helm.go, cmd/gotk/utils.go, docs/cmd/gotk_create_helmrelease.md, docs/cmd/gotk_create_kustomization.md
=> Add support for Bucket sources to Kustomizations/HRs

cmd/gotk/create_tenant.go, docs/cmd/gotk_create_tenant.md
Changes:
- add `--with-namespace` arg to create tenant command
- label namespaces and role bindings with the tenant name for discovery purposes
- allow changing the the cluster role name with `--cluster-role` arg, defaults to `cluster-admin` 
- add create tenant examples to docs
Ref: https://github.com/fluxcd/toolkit/discussions/263
=> Add support for multi-namespace tenant ownership

.github/workflows/e2e.yaml, cmd/gotk/create_helmrelease.go, cmd/gotk/create_kustomization.go, cmd/gotk/create_source_git.go, cmd/gotk/get_helmrelease.go, cmd/gotk/get_kustomization.go, cmd/gotk/get_source_bucket.go, cmd/gotk/get_source_git.go, cmd/gotk/get_source_helm.go, cmd/gotk/reconcile_helmrelease.go, cmd/gotk/reconcile_kustomization.go, cmd/gotk/reconcile_source_bucket.go, cmd/gotk/reconcile_source_helm.go, cmd/gotk/resume_helmrelease.go, cmd/gotk/resume_kustomization.go
Fixes https://github.com/fluxcd/toolkit/issues/215 based on discussion in https://github.com/fluxcd/toolkit/discussions/217#discussioncomment-86404
=> Make use of `apis/meta` helpers and improve `reconcile` logic

cmd/gotk/bootstrap.go, cmd/gotk/install.go, docs/cmd/gotk_bootstrap.md, docs/cmd/gotk_bootstrap_github.md, docs/cmd/gotk_bootstrap_gitlab.md, docs/cmd/gotk_install.md
This PR adds the `--network-policy` boolean flag (defaults to `true`) to the install and bootstrap commands. This allows users to disable the network policy that denies ingress access to the toolkit controllers from other namespaces. Disabling the network policy is not advised especially when running on a multi-tenancy cluster.
Fix: #294
=> Add option to disable the network policy at install time

docs/guides/helmreleases.md, docs/guides/mozilla-sops.md, docs/guides/sealed-secrets.md, docs/guides/webhook-receivers.md
Using gotk 0.1.3 I've had to update the api versions shown in the docs for some of the examples to get them working in my cluster. This PR should fix those, please let me know if I've missed anything.
=> Update api versions in docs

cmd/gotk/get_source_bucket.go, cmd/gotk/get_source_git.go, cmd/gotk/get_source_helm.go
Includes a change to an empty revision string if the reconciler has not
produced an artifact yet, as this will otherwise result in a nil
pointer dereference.
Follow up on #299
=> Display proper revision for sources

cmd/gotk/bootstrap.go, cmd/gotk/install.go, pkg/install/install.go, pkg/install/install_test.go, pkg/install/manifests.go, pkg/install/options.go, pkg/install/templates.go
Changes:
- extract manifests generation to a dedicated package
- refactor the install and bootstrap command
The `install` package is meant as a replacement for Flux v1 `install` package.
=> Introduce install package

docs/guides/installation.md, manifests/monitoring/grafana/dashboards/control-plane.json, manifests/monitoring/grafana/deployment.yaml, manifests/monitoring/prometheus/deployment.yaml, manifests/policies/allow-scraping.yaml, manifests/policies/allow-webhooks.yaml, manifests/policies/kustomization.yaml
Changes:
- Use `gotk` commands to install the monitoring stack in docs 
- Update Prometheus to `2.21.0` and Grafana to `7.2.1`
- Add network policies to allow Prometheus scraping and webhooks
=> docs: Install the monitoring stack with gotk

docs/get-started/index.md
Issue : #306 
ARM instruction are now added inside the doc. Below is screenshot how it looks like based on the PR changes.
=> Add ARM instruction to get started guide

cmd/gotk/bootstrap.go, cmd/gotk/check.go, cmd/gotk/install.go, cmd/gotk/uninstall.go, cmd/gotk/utils.go
Hello.
Please let me know if this is something you expect here.
Or would be better to switch `execCommand` to something like `execCommand(ctx context.Context, mode ExecMode, commandName string, args ...string)`?
Related to #47
=> Get rid of shell-out and invoke command directly via exec

cmd/gotk/bootstrap.go, cmd/gotk/create_alert.go, cmd/gotk/create_alertprovider.go, cmd/gotk/create_helmrelease.go, cmd/gotk/create_kustomization.go, cmd/gotk/create_receiver.go, cmd/gotk/create_source_bucket.go, cmd/gotk/create_source_git.go, cmd/gotk/create_source_helm.go, cmd/gotk/reconcile_alert.go, cmd/gotk/reconcile_alertprovider.go, cmd/gotk/reconcile_helmrelease.go, cmd/gotk/reconcile_kustomization.go, cmd/gotk/reconcile_receiver.go, cmd/gotk/reconcile_source_bucket.go, cmd/gotk/reconcile_source_git.go, cmd/gotk/reconcile_source_helm.go, cmd/gotk/resume_alert.go, cmd/gotk/resume_helmrelease.go, cmd/gotk/resume_kustomization.go, cmd/gotk/resume_receiver.go, docs/cmd/gotk_create_helmrelease.md, docs/cmd/gotk_reconcile_kustomization.md
* Take ObservedGeneration into account in readiness checks where
applicable
* Reduce amount of code (and duplicate GETs) by working with pointers
where possible
* Improve logged messages to properly take resource names into account
and better describe processes
First point addresses https://github.com/fluxcd/helm-controller/issues/112
=> Refactor create, reconcile and resume commands

.github/workflows/docs.yaml, .github/workflows/update.yml
And re-use the same logic to properly compare current and next release
versions in update workflow.
=> Remove documentation version hotfix

cmd/gotk/bootstrap_gitlab.go, docs/cmd/gotk_bootstrap_gitlab.md, docs/guides/installation.md
This PR changes the bootstrap procedure for GitLab. It will generate a deploy key only when `--ssh-hostname` is specified, otherwise it uses the `GITLAB_TOKEN` to authenticate against Git over HTTPS instead of SSH.
Testing this PR:
```
git clone https://github.com/fluxcd/toolkit.git
cd toolkit
git checkout gitlab-https-auth
make build
./cmd/gotk bootstrap gitlab --owner=<group> --repository=<repo name> \
--hostname=gitlab.com
./cmd/gotk bootstrap gitlab --owner=<group> --repository=<repo name> \
--hostname=gitlab.com \
--ssh-hostname=gitlab.com
```
Using HTTPS auth should fix: #335 and fix: https://github.com/fluxcd/source-controller/issues/120
PS. I tested this on Gitlab.com with both https and ssh.
=> Add GitLab HTTPS auth to bootstrap options

README.md, docs/components/helm/controller.md, docs/components/kustomize/controller.md, docs/components/notification/controller.md, docs/components/source/controller.md, docs/get-started/index.md, docs/guides/installation.md
Starting with `v0.1.7`, Windows binaries are available for download from GitHub releases page.
=> Add Windows OS to CLI install docs

cmd/gotk/create_source_bucket.go, cmd/gotk/create_source_git.go, cmd/gotk/create_source_helm.go, docs/cmd/gotk_create_source_bucket.md, docs/cmd/gotk_create_source_git.md, docs/cmd/gotk_create_source_helm.md
Add secret-ref flag to `create source` options
This allows passing the name of an existing secret that already exists in the cluster (perhaps created with terraform)
`make test` is passing
Manually tested with `--export`
=> Add secret-ref flag to create source git

docs/guides/installation.md, docs/guides/monitoring.md, mkdocs.yml
This PR moves the monitoring stack docs to a dedicated guide and documents the reconciliation metrics.
=> Add monitoring guide

README.md
moved Oct 19 meetup from "upcoming meetings" to "featured talks" and linked to youtube recording.
=> Update featured talks and add upcoming meeting

cmd/gotk/bootstrap.go, cmd/gotk/install.go, docs/cmd/gotk_install.md, pkg/install/install.go, pkg/install/options.go, pkg/sync/options.go, pkg/sync/sync.go, pkg/sync/sync_test.go
The reason the manifest generation is refactored into a separate package is to make it possible for other projects to use the code.
The change also includes changing the return parameters as the file path and the content is important for the Terraform provider rather than reading files from a temp directory.
=> Refactor manifest generation into a separate package

docs/faq/index.md, docs/guides/helmreleases.md
* Remove mention of dependency download limitation
* Include bucket sources in HelmRelease guide
=> Update HelmRelease documentation

Makefile
This ensures no stray files are kept when for example a command name
changes.
=> Delete generated docs before regenerating them

CONTRIBUTING.md, README.md, docs/dev-guides/source-watcher.md, docs/faq/index.md, docs/get-started/index.md, docs/guides/installation.md, docs/guides/monitoring.md, docs/index.md, docs/roadmap/index.md, mkdocs.yml
This replaces most mentions of "GitOps Toolkit" and "toolkit" with "Flux". I have adopted the style of using "Flux v2" in the first mention, and thereafter just "Flux" (except where contrasting with Flux v1).
Ref: #388
=> Replace GitOps Toolkit in docs

docs/guides/flux-v1-migration.md, docs/roadmap/index.md, mkdocs.yml
This PR contains the migration guide from Flux v1 (read-only mode/without automated image updates) to Flux v2.
Preview: https://toolkit.fluxcd.io/guides/flux-v1-migration/
=> Add migration guide for Flux v1 users

docs/guides/installation.md
When following the guide for generic git server, I came across this problem which I solved, thought I'd do a PR to update the docs. 
The \ before the comment here means the subsequent lines end up getting commented out (and then not exported), see: https://stackoverflow.com/questions/9522631/how-to-put-a-line-comment-for-a-multi-line-command
=> docs: fixing command for expected output

mkdocs.yml
As they are used in the metadata, instead of the title from the
document.
=> Rename migration menu items

docs/guides/mozilla-sops.md
Updates the authentication hint for Azure, as it is not possible to add IAM permissions to a service account in Azure.
Fixes #427
=> Update authentication hint for Azure

cmd/flux/check.go
Make it easy to view each component version with:
```console
$ flux check 
✔ kubectl 1.19.3 >=1.18.0
✔ Kubernetes 1.18.10-gke.601 >=1.16.0
✔ source-controller is healthy
► ghcr.io/fluxcd/source-controller:v0.2.1
✔ kustomize-controller is healthy
► ghcr.io/fluxcd/kustomize-controller:v0.2.1
✔ helm-controller is healthy
► ghcr.io/fluxcd/helm-controller:v0.2.0
✔ notification-controller is healthy
► ghcr.io/fluxcd/notification-controller:v0.2.0
✔ all checks passed
```
=> List component images in check cmd

cmd/flux/create_tenant.go
Fix multiple issues when running `flux create tenant --export` 
1. Panic when creating a tenant with a single namespace.
```
$ flux create tenant sample --with-namespace=sample --export
panic: runtime error: index out of range [1] with length 1
goroutine 1 [running]:
main.createTenantCmdRun(0x36b0f20, 0xc0006a13b0, 0x1, 0x3, 0x0, 0x0)
/home/runner/work/flux2/flux2/cmd/flux/create_tenant.go:138 +0x11b4
github.com/spf13/cobra.(*Command).execute(0x36b0f20, 0xc0006a1380, 0x3, 0x3, 0x36b0f20, 0xc0006a1380)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x36aea60, 0x0, 0xc000092058, 0x0)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...) …
```
=> Fix create tenant command export

cmd/flux/bootstrap.go, cmd/flux/bootstrap_github.go, cmd/flux/bootstrap_gitlab.go, docs/cmd/flux_bootstrap.md, docs/cmd/flux_bootstrap_github.md, docs/cmd/flux_bootstrap_gitlab.md, docs/guides/installation.md
This PR adds the `--token-auth` flag to the bootstrap command, when enabled, a SSH deploy key will no longer be generated, Flux will connect to Git using HTTPS token authentication. 
Fix: #449
=> Add token authentication option to bootstrap

cmd/flux/install.go
Currently, the components are installed even with `--dry-run` option.
=> Fix --dry-run option

cmd/flux/create_helmrelease.go, docs/cmd/flux_create_helmrelease.md, internal/flags/helm_release_values.go
This PR adds `--values-from` arg to create hr command, example usage:
```sh
kubectl -n app create secret generic my-secret-values \
--from-file=values.yaml=/path/to/my-secret-values.yaml
flux -n app create helmrelease redis \
--source=HelmRepository/bitnami \
--chart=redis \
--values-from=Secret/my-secret-values
```
Ref: #213
=> Add values-from arg to create helmrelease cmd

action/Dockerfile, action/README.md, action/action.yml, action/entrypoint.sh
This PR adds a GitHub Action for using Flux CLI in CI.
Example workflow:
```yaml
name: e2e
on:
push:
branches:
- '*'
jobs:
kubernetes:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v2
- name: Setup Flux CLI
uses: fluxcd/flux2/action@main
- name: Setup Kubernetes Kind
uses: engineerd/setup-kind@v0.5.0
- name: Install Flux in Kubernetes Kind
run: flux install
```
=> Add GitHub Action for Flux CLI

cmd/flux/create_tenant.go, docs/cmd/flux_create.md, docs/cmd/flux_create_tenant.md, mkdocs.yml
Generate a service account with limited access to its namespace, for each namespace owned by a tenant.
```
flux create tenant dev-team --with-namespace apps --export
```
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
labels:
toolkit.fluxcd.io/tenant: dev-team
name: apps
---
kind: ServiceAccount
metadata:
labels:
toolkit.fluxcd.io/tenant: dev-team
name: dev-team
namespace: apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
labels:
toolkit.fluxcd.io/tenant: dev-team
name: gotk-reconciler
namespace: apps
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: ClusterRole
name: cluster-admin
subjects:
- kind: User
name: gotk:apps:reconciler
- kind: ServiceAccount
name: dev-team
```
=> Add service accounts to tenant command

docs/guides/mozilla-sops.md
This PR adds a note to clarify a bit that encrypted secrets are not to be applied directly to the cluster.
=> add a note not to apply encrypted secrets directly

cmd/flux/create_helmrelease.go, cmd/flux/create_kustomization.go, docs/cmd/flux_create_helmrelease.md, docs/cmd/flux_create_kustomization.md
This PR adds a `--service-account` arg to `create helmrelease` command and renames the `--sa-name` arg to `--service-account` in the `create kustomization` command.
This allows users to specify the name of the service account to impersonate when reconciling a Kustomization or HelmRelease.
Example:
```sh
flux create tenant dev-team --with-namespace=apps
flux create kustomization --namespace=apps --service-account=dev-team
flux create helmrelease --namespace=apps --service-account=dev-team
```
=> Add service account arg to create commands

MAINTAINERS
Many of the GitOps Toolkit controllers will share maintainers with
this repo, acting as the central Flux v2 repo. For convenience of
tracking membership and applying permissions, we can share maintainers
by:
- referring to the MAINTAINERS file here, from elsewhere;
- making a GitHub team that tracks those shared maintainers.
This commit makes a note of this in the MAINTAINERS file, to inform
people of the arrangement, and remind them to keep the team up to
date.
See https://github.com/fluxcd/flux2/discussions/515 for the original proposal. NB since this touches on governance, should be approved by @fluxcd/oversight-committee.
=> Note the shared Flux v2 maintainers and team

install/flux.sh
`uname -m` will print out architecture codenames based on UTS_MACHINE
and COMPAT_UTS_MACHINE kernel defined constants. These extra values will
ensure the right version of the arm binary is installed on most Linux
systems running on ARM CPUs.
I was only able to test this on my RPiv3, `uname -m` reports `armv7l`. With the tweak, the installation is able to complete.
=> Improve installer list match for arm arches

cmd/flux/create_tenant.go, cmd/flux/reconcile_alert.go, cmd/flux/reconcile_helmrelease.go, cmd/flux/reconcile_kustomization.go, cmd/flux/reconcile_receiver.go, cmd/flux/reconcile_source_bucket.go, cmd/flux/reconcile_source_git.go, cmd/flux/reconcile_source_helm.go
Changes:
- Add service account namespace to tenant role binding
- Rename role binding to match the tenant name
- Do not try to reconcile a suspended object
=> Fix tenant and reconcile commands

docs/roadmap/index.md
Alan [commented in a Flux dev meeting](https://docs.google.com/document/d/1l_M0om0qUEN_NNiGgpqJ2tvsF2iioHkaARDeh6b70B0/edit#heading=h.4w6ysomi4xa) that it is not easy to find out the status of the various components of Flux v2 (e.g., the image update automation).
TODO:
On that latter, the suggestion was 
> from the new home page, “Getting Started” and “Learn More” [...] -- at least one of them -- should give a quick summary of v2 feature parity status
=> Show the roadmap status more prominently and precisely

cmd/flux/create_source_bucket.go, cmd/flux/create_source_git.go, cmd/flux/create_source_helm.go
Label secrets generated by the create commands:
```sh 
flux create source <TYPE> <NAME> \
--label=environment=dev \
--label=region=eu-west-2
```
Fix: #545
=> Add labels to generated secrets

cmd/flux/create_secret.go, cmd/flux/create_secret_git.go, docs/cmd/flux_create.md, docs/cmd/flux_create_secret.md, docs/cmd/flux_create_secret_git.md, mkdocs.yml
This PR adds a command for generating Kubernetes secrets with Git credentials.
```sh
flux create secret git podinfo-auth \
--url=ssh://git@github.com/stefanprodan/podinfo \
--ssh-key-algorithm=ecdsa \
--ssh-ecdsa-curve=p521
flux create secret git podinfo-auth \
--url=https://github.com/stefanprodan/podinfo \
--username=username \
--password=password
flux create secret git podinfo-auth \
--url=ssh://git@github.com/stefanprodan/podinfo \
--export > podinfo-auth.yaml
yq read podinfo-auth.yaml 'data."identity.pub"' | base64 --decode
flux create secret git podinfo-auth \
--namespace=apps \
--url=ssh://git@github.com/stefanprodan/podinfo \
--export > podinfo-auth.yaml
sops --encrypt --encrypted-regex '^(data|stringData)$' \
--in-place podinfo-auth.yaml
```
Fix: #360
Fix: …
=> Add create secret git command

.github/workflows/release.yaml
The AUR_BOT_SSH_PRIVATE_KEY environment variable needs to be set in
goreleaser so publishing the packages to AUR can work.
=> Add AUR_BOT_SSH_PRIVATE_KEY env var for goreleaser

.github/workflows/release.yaml, .goreleaser.yml, docs/guides/installation.md
Build and publish Flux `install.yaml` to GitHub release for those that don't want to use `flux bootstrap`.
After the next release, Flux can be installed with kubectl:
```
kubectl apply -f https://github.com/fluxcd/flux2/releases/latest/download/install.yaml
```
=> Publish install manifest to GitHub releases

.github/aur/flux-bin/publish.sh, .github/aur/flux-go/publish.sh, .github/aur/flux-scm/publish.sh, .goreleaser.yml
Using a lock to prevent parallel executions in GoReleaser's custom
publishers. The custom publisher logic executes the tasks in parallel
for each available artifact.
https://goreleaser.com/customization/publishers/#how-it-works
=> Prevent AUR package publishing parallel execution

go.mod, go.sum
`fluxcd/pkg/git` v0.1.0 comes with various fixed to GitLab bootstrap, ref: https://github.com/fluxcd/pkg/pull/62
=> Update fluxcd/pkg/git to v0.1.0

internal/utils/utils.go, pkg/manifestgen/install/manifests.go
Work around for a bug in kustomize causing it to not properly
handle absolute paths on Windows.
Fixes #362
=> Use relative filepaths in generated kustomization and during build

cmd/flux/create_source_git.go, cmd/flux/log.go, cmd/flux/main.go
This commit refactors the `printLogger` into a `stderrLogger` that
properly logs to `os.stderr` instead of `os.stdout`.
Fixes: #579
=> Log to stderr

.github/workflows/update.yml, cmd/flux/bootstrap.go, cmd/flux/bootstrap_github.go, cmd/flux/bootstrap_gitlab.go, cmd/flux/install.go, docs/cmd/flux_bootstrap.md, docs/cmd/flux_bootstrap_github.md, docs/cmd/flux_bootstrap_gitlab.md, docs/cmd/flux_install.md, manifests/bases/image-automation-controller/kustomization.yaml, manifests/bases/image-automation-controller/patch.yaml, manifests/bases/image-reflector-controller/kustomization.yaml, manifests/bases/image-reflector-controller/patch.yaml, manifests/install/kustomization.yaml
This adds kustomizations for `image-{reflector,automation}-controller`, which will get bundled into the file fetched by `flux install`.
It also adds the corresponding APIs into the update workflow, so they don't get left out.
Lastly, this introduces an argument `--extra-components`, which can be used to add components to the defaults. E.g., you can do
flux install --extra-components image-reflector-controller,image-automation-controller
rather than having to use `--components` and name all of them including the defaults.
=> Include image controller config in `flux install`

cmd/flux/bootstrap.go, cmd/flux/install.go, docs/cmd/flux_bootstrap.md, docs/cmd/flux_bootstrap_github.md, docs/cmd/flux_bootstrap_gitlab.md, docs/cmd/flux_install.md, pkg/manifestgen/install/options.go, pkg/manifestgen/install/templates.go
Since https://github.com/fluxcd/source-controller/pull/233 the bootstrap command will use `--storage-adv-addr=source-controller.$(RUNTIME_NAMESPACE).svc.cluster.local.` as default option for the source controller.
But for some users, the cluster domain is not `cluster.local` and this will result in breaking their source controller each time they run the `bootstrap` command (for upgrading their flux instance for example).
=> Add cluster-domain option for bootstrap command

docs/cmd/flux_create_helmrelease.md, docs/cmd/flux_create_kustomization.md, internal/flags/arch_test.go, internal/flags/decryption_provider.go, internal/flags/decryption_provider_test.go, internal/flags/ecdsa_curve.go, internal/flags/ecdsa_curve_test.go, internal/flags/helm_chart_source.go, internal/flags/helm_chart_source_test.go, internal/flags/helm_release_values.go, internal/flags/helm_release_values_test.go, internal/flags/kustomization_source.go, internal/flags/kustomization_source_test.go, internal/flags/log_level_test.go, internal/flags/public_key_algorithm_test.go, internal/flags/rsa_key_bits.go, internal/flags/rsa_key_bits_test.go, internal/flags/source_bucket_provider.go, internal/flags/source_bucket_provider_test.go, internal/utils/utils.go
This includes various bug fixes, especially around the area of missing
names for `<kind>/<name>` formats.
=> Add tests for CLI flags

internal/flags/helm_chart_source.go, internal/flags/helm_chart_source_test.go, internal/flags/helm_release_values.go, internal/flags/helm_release_values_test.go, internal/flags/kustomization_source.go, internal/flags/kustomization_source_test.go, internal/utils/utils.go
So that `<kind>/<name>` flags can be supplied as:
* `secret/foo`
* `Secret/foo`
* `SeCrEt/foo`
But result in: `Secret/foo`.
=> Make resource selector args case insensitive

.github/workflows/e2e.yaml
This PR adds the [flux2-kustomize-helm-example](https://github.com/fluxcd/flux2-kustomize-helm-example) setup to the end-to-end test suite, this covers:
- kustomize overlays mapped to Flux's Kustomizations
- dependsOn relationships between Flux's Kustomizations
- HelmReleases heath checks in Flux's Kustomizations
- HelmReleases with values from ConfigMaps generated with kustomize
- HelmReleases with fixed versions and semver ranges
=> Add e2e test for flux2-kustomize-helm-example

docs/get-started/index.md, docs/guides/installation.md
Adds a hint regarding the fact that the deploy key created by the bootstrap command is linked to the personal access token used to authenticate. This is important as users must be warned so that they do not just remove their personal access tokens.
=> Add note about deploy key linked to pat

.github/workflows/bootstrap.yaml, .github/workflows/e2e.yaml
Increase timeout for `flux uninstall` to work around GitHub Actions slow workers.
=> Set e2e uninstall timeout to 10m

README.md
Sorted 'featured talks' chronologically, moved Dec 14 talk from upcoming to featured section with video link, added Scott's upcoming Helm talk in Jan 2021.
Signed-off-by: Stacey Potter <50154848+staceypotter@users.noreply.github.com>
=> Updated Upcoming Events & Featured Talks sections

docs/core-concepts/index.md
Fix small typo, added verb to make the intent clear, added spaces before "(" to match the same pattern used in other parts of the docs
=> Minor fixes to core concepts doc

docs/dev-guides/source-watcher.md
The example consumer of the GitOps Toolkit Source APIs was moved from `stefanprodan/source-watcher` to `fluxcd/source-watcher`, this PR updates the dev guide to point to the new URL.
=> Update dev guide to point to fluxcd/source-watcher

cmd/flux/create_secret_git.go, cmd/flux/create_secret_helm.go, docs/cmd/flux_create_secret.md, docs/cmd/flux_create_secret_git.md, docs/cmd/flux_create_secret_helm.md, mkdocs.yml
This PRs adds a new command that can be used to generate Helm repository auth secrets.
Example of creating a Helm authentication secret on disk and encrypting it with Mozilla SOPS:
```sh
flux create secret helm repo-auth \
--namespace=my-namespace \
--username=my-username \
--password=my-password \
--cert-file=./cert.crt \
--key-file=./key.crt \
--ca-file=./ca.crt \
--export > repo-auth.yaml
sops --encrypt --encrypted-regex '^(data|stringData)$' \
--in-place repo-auth.yaml
flux create source helm my-repo \
--namespace=my-namespace \
--interval=10m \
--url=https://my-repo \
--secret-ref=repo-auth
```
=> Add create secret helm command

docs/guides/installation.md
Fix: https://github.com/fluxcd/source-controller/issues/253
=> Fix Azure DevOps URL in docs

docs/guides/sealed-secrets.md
Since global helm chart is deprecated, it seems that the sealed-secrets chart repo is now available on bitnami-labs github.
Signed-off-by: Guillaume Le Biller <glebiller@Traveldoo.com>
=> Update sealed-secrets chart URL

cmd/flux/bootstrap.go, cmd/flux/bootstrap_github.go, cmd/flux/bootstrap_gitlab.go, docs/cmd/flux_bootstrap_github.md, docs/cmd/flux_bootstrap_gitlab.md, pkg/manifestgen/sync/options.go, pkg/manifestgen/sync/sync.go
Add git implementations to options. I don't think it is pertinent to add this as a flag to the GitHub or GitLab bootstrap commands as they will probably not be used. I guess we should reconsider if we add self signed cert support which would only work in libgit2.
=> Add git implementation to generate sync options

manifests/policies/deny-ingress.yaml
Seems that AKS network policy addon blocks pod-to-pod communication by default, even if the pods are in the same namespace, this PR enabled egress traffic for Flux controller pods allowing kustomize/helm controllers to fetch artifacts from source-controller.
Fix: #703, #697, #690
=> Allow egress traffic for controller pods

docs/guides/image-update.md
This is a simple typo fix (maker => marker) in the image update documentation. 
I've stumbled over this and was not sure what a "maker" should be and if its really just the comment in the yaml. Maybe it could also be just simply be named comment? The reader adds a comment which acts as a marker for flux.
=> Typo fix in image-update documentation 

cmd/flux/bootstrap.go, cmd/flux/install.go, docs/cmd/flux_bootstrap.md, docs/cmd/flux_bootstrap_github.md, docs/cmd/flux_bootstrap_gitlab.md, docs/cmd/flux_install.md, docs/get-started/index.md, docs/guides/installation.md, pkg/manifestgen/install/options.go, pkg/manifestgen/install/templates.go
This commit deprecates the architecture flag (`--arch`) for the install
and bootstrap commands, in favor of the bundled multi-arch images that
will be available for the next MINOR range of GOTK controller releases.
Summary of changes:
* `*Arch` variables have been marked as deprecated for both commands.
* `-arm64` suffix is no longer selectively added to the image definition
of a component's `Deployment`.
* `kubernetes.io/arch` node selector with the defined value has been
removed from the components' `Deployment`s.
* `Arch` has been removed from the available `Options` in
`manifestgen/install`.
* Documentation references have been changed to highlight existence
of multi-arch images and supported architectures.
Fixes: https://github.com/fluxcd/flux2/issues/493
=> Deprecate arch flags in favor of multi-arch images

cmd/flux/reconcile.go, cmd/flux/reconcile_alert.go, cmd/flux/reconcile_alertprovider.go, cmd/flux/reconcile_helmrelease.go, cmd/flux/reconcile_kustomization.go, cmd/flux/reconcile_receiver.go, cmd/flux/reconcile_source_bucket.go, cmd/flux/reconcile_source_git.go, cmd/flux/reconcile_source_helm.go
Replace deprecated `ReconcileAtAnnotation` with `ReconcileRequestAnnotation`.
Fix: #542
=> Use reconcile request annotation

.goreleaser.yml, install/flux.sh
This causes the format of the checksum file generated during the release
to change from `flux2_*_checksums.txt` to `flux_*_checksums.txt`.
The configuration change is made through `project_name` and not via the
`checksum.name_template` setting, because a single checksum file is
generated during the release process.
The download and/or installation script in `install/flux.sh` has been
adapted to assume the new filename starting with MINOR version `0.6.0`.
=> Configure `project_name` for GoReleaser

cmd/flux/create_image_policy.go, cmd/flux/create_image_updateauto.go, docs/cmd/flux_create_image_policy.md, docs/cmd/flux_create_image_update.md
Changes:
- Make `--branch` arg required for `flux create image update` to match the API changes
- Add optional `--filter-regex` arg to `flux create image policy` command
=> Add regex filter arg to policy command

.github/workflows/update.yml
This results in the automatic rebase of an outstanding PR on merges to
this branch, removing the need of manually firing it.
=> Fire 'Update Components' workflow on push to main

docs/guides/mozilla-sops.md
This pull request will update the guide to let users know that they don't need a gpg secretRef when using KMS.
=> Update guide for mozilla sops

go.mod, go.sum
Fixes Gitlab bootstrap when used with a project token, ref: https://github.com/fluxcd/pkg/issues/75
=> Update fluxcd/pkg/git to v0.2.3

.github/workflows/docs.yaml, docs/components/image/controller.md, docs/components/index.md
This adds the image-* controllers, with their API refs, to the "components" part of the docs.
=> Include image spec and ref docs

manifests/rbac/role.yaml
The v0.8.0 version of the controller-runtime uses both config maps and
leases to perform leader election. These permissions seem to be in the
individual controller repos, but not here. For example
https://github.com/fluxcd/kustomize-controller/blob/2d38de8779b68bde3366489a0b7657488c747fdb/config/rbac/leader_election_role.yaml#L33-L44
=> Add permissions for controller leader election.

docs/guides/installation.md, docs/guides/mozilla-sops.md, manifests/bases/helm-controller/account.yaml, manifests/bases/helm-controller/kustomization.yaml, manifests/bases/helm-controller/patch.yaml, manifests/bases/image-automation-controller/account.yaml, manifests/bases/image-automation-controller/kustomization.yaml, manifests/bases/image-automation-controller/patch.yaml, manifests/bases/image-reflector-controller/account.yaml, manifests/bases/image-reflector-controller/kustomization.yaml, manifests/bases/image-reflector-controller/patch.yaml, manifests/bases/kustomize-controller/account.yaml, manifests/bases/kustomize-controller/kustomization.yaml, manifests/bases/kustomize-controller/patch.yaml, manifests/bases/notification-controller/account.yaml, manifests/bases/notification-controller/kustomization.yaml, manifests/bases/notification-controller/patch.yaml, manifests/bases/source-controller/account.yaml, manifests/bases/source-controller/kustomization.yaml, manifests/bases/source-controller/patch.yaml, manifests/rbac/controller.yaml, manifests/rbac/kustomization.yaml, manifests/rbac/reconciler.yaml
This PR assigns each controller a service account named the same as the controller. 
At install/upgrade time, `flux bootstrap` and `flux install` will create two cluster roles and bindings prefixed with the `--namespace` value. This change will also apply to Flux Terraform provider.
This `ClusterRoleBinding` grands cluster wide RW access to the `toolkit.fluxcd.io` custom resources (required by controller runtime), RO access to Kubernetes secrets (required by `secretRef`) and RW access to Kubernetes leases (required by leader election). All the controller service accounts are bind to this cluster role.
This `ClusterRoleBinding` grands `cluster-admin` access to kustomize-controller and helm-controller using their dedicate service account.
Fix: #243
=> Add a dedicated service account per controller

manifests/rbac/controller.yaml, manifests/rbac/reconciler.yaml, pkg/manifestgen/install/templates.go
Fix `flux install` when not all controllers have been selected, if no namespace is specified for the missing controller, the install fails with:
```
The ClusterRoleBinding "crd-controller-flux-system" is invalid:
* subjects[4].namespace: Required value
```
Fix: #784
=> RBAC Fix: Add SA namespace to cluster role bindings

cmd/flux/create_secret.go, cmd/flux/create_secret_git.go, cmd/flux/create_secret_helm.go, cmd/flux/create_secret_tls.go, docs/cmd/flux_create_secret.md, docs/cmd/flux_create_secret_tls.md, go.mod
The image-reflector controller now accepts a secret containing a
client certificate and key, and/or a CA certificate; so it's useful to
have a command for creating them.
`flux create secret helm` is close, but accepts username/password
(which would be ignored), and has the wrong name of course. Happily
though, much can be shared between the implementations.
```bash
$ flux create secret tls --help
The create secret tls command generates a Kubernetes secret with certificates for use with TLS.
Usage:
flux create secret tls [name] [flags]
Examples:
flux create secret tls certs \
--namespace=my-namespace \
--cert-file=./client.crt \
--key-file=./client.key \
--export > certs.yaml
sops --encrypt --encrypted-regex '^(data|stringData)$' \
--in-place certs.yaml
Flags:
--ca-file string     TLS …
```
=> Create secret for TLS command

cmd/flux/get_source_chart.go, cmd/flux/get_source_git.go, cmd/flux/get_source_helm.go
This fixes a bug where the wrong type was displayed for various
`get source` commands.
```console
$ flux get sources helm --namespace default
✗ no Bucket objects found in default namespace
```
Regression bug introduced in #761
=> Use correct type in various get source commands

docs/guides/image-update.md
The API changed in v0.7 and the example from the guide is outdated.
=> Update docs ImageUpdateAutomation example

.github/workflows/e2e.yaml, .github/workflows/e2e_kind_config.yaml
This PR disables the default KIND-net, and uses Calico CNI instead to enable network policy for the KIND cluster in e2e testing.
fixes #800
=> Enable network policy in e2e

action/README.md, docs/guides/image-update.md
Changes:
- document how to trigger image updates with webhooks
- add staging CI/CD pipeline to image automation use-cases
- provide an example of how to tag images for staging `${GIT_BRANCH}-${GIT_SHA:0:7}-$(date +%s)`
=> Add webhook section to image update docs

docs/faq/index.md
Changes:
- rename "general questions" to "Flux v1 vs v2"
- add How to debug "not ready" errors? to Helm FAQ
=> Add HelmChart not ready to FAQ

.github/workflows/e2e.yaml, cmd/flux/create_secret.go, cmd/flux/create_secret_git.go
The `flux create secret` commands are throwing panic errors due to regression bug introduced in https://github.com/fluxcd/flux2/pull/788 (the secret StringData wasn't initialised).
Fix: #826
=> Fix create secret commands

cmd/flux/bootstrap.go, cmd/flux/check.go, cmd/flux/install.go, cmd/flux/status.go, docs/cmd/flux_check.md
Changes:
- run install/bootstrap checks in parallel (1m timeout)
- list not found components
- add `--components-extra` arg to check command
Example output:
```console
$ flux check --components-extra=image-reflector-controller,image-automation-controller
✔ kubectl 1.20.2 >=1.18.0
✔ Kubernetes 1.18.12-gke.1205 >=1.16.0
✔ source-controller: healthy
► ghcr.io/fluxcd/source-controller:v0.7.3
✔ kustomize-controller: healthy
► ghcr.io/fluxcd/kustomize-controller:v0.7.4
✔ helm-controller: healthy
► ghcr.io/fluxcd/helm-controller:v0.6.1
✔ notification-controller: healthy
► ghcr.io/fluxcd/notification-controller:v0.7.1
✗ image-reflector-controller: unhealthy (timed out waiting for rollout)
► ghcr.io/fluxcd/image-reflector-controller2:v0.5.0
✗ …
```
=> Refactor components status check

cmd/flux/create_image_repository.go, docs/cmd/flux_create_image_repository.md
ImageRepository objects can now refer to a secret containing
certificates to use for TLS. This adds the flag
flux create image repository --cert-secret-ref
for naming a secret to use. You can create such a secret with
flux create secret tls
TODO:
=> Give image repository a cert-secret-ref flag

docs/guides/monitoring.md
If a resource is deleted, the alert will fire indefinitely.
I multiply the "Deleted" count by 2 to have a distinct case.
* If the reconciliation fails, left part is valued 1.
* If the resource is deleted, right part is valued 2.
=> Exclude deleted resources on prometheus alerting query

cmd/flux/create_helmrelease.go, docs/cmd/flux_create_helmrelease.md, internal/utils/utils.go
This PR adds support for providing multiple values files to `flux create helmrelease` command.
Example:
```sh
flux create helmrelease podinfo \
--source=HelmRepository/podinfo \
--chart=podinfo \
--values=./replicas.yaml \
--values=./resources.yaml
```
Fix: #865
=> Add support for multiple values files to create hr

cmd/flux/get.go, cmd/flux/get_alert.go, cmd/flux/get_alertprovider.go, cmd/flux/get_helmrelease.go, cmd/flux/get_image.go, cmd/flux/get_kustomization.go, cmd/flux/get_receiver.go, cmd/flux/get_source.go, docs/cmd/flux_get.md, docs/cmd/flux_get_images.md, docs/cmd/flux_get_images_policy.md, docs/cmd/flux_get_images_repository.md, docs/cmd/flux_get_images_update.md, mkdocs.yml
Changes:
- add singular alias to `flux get` commands
- allow filtering the `flux get` commands result by resource name
- add the image commands to mkdocs index
Example:
```console
$ flux get sources git
NAME    	READY	MESSAGE                                                          	REVISION                                       	SUSPENDED 
podinfo 	True 	Fetched revision: master/e43ebfa5bf4b87c46f2e1db495eb571cd398e2f7	master/e43ebfa5bf4b87c46f2e1db495eb571cd398e2f7	False    	
podinfo2	True 	Fetched revision: master/e43ebfa5bf4b87c46f2e1db495eb571cd398e2f7	master/e43ebfa5bf4b87c46f2e1db495eb571cd398e2f7	False    
$ flux get source git podinfo
NAME   	READY	MESSAGE                                                          	REVISION                                       	SUSPENDED 
podinfo …
```
=> Add support for getting resources by name

.github/workflows/e2e.yaml, cmd/flux/create_image_policy.go, docs/cmd/flux_create_image_policy.md
=> Adding --select-alpha and --extract to create image policy

cmd/flux/bootstrap.go, cmd/flux/install.go, docs/cmd/flux.md, docs/cmd/flux_bootstrap.md, docs/cmd/flux_bootstrap_github.md, docs/cmd/flux_bootstrap_gitlab.md, docs/cmd/flux_install.md, docs/guides/installation.md, pkg/manifestgen/install/install_test.go, pkg/manifestgen/install/options.go, pkg/manifestgen/install/templates.go
This PR adds the `--toleration-keys` arg to `flux install` and `flux bootstrap` commands.
Example:
```sh
flux install --toleration-keys=node.kubernetes.io/dedicated-to-flux,node.kubernetes.io/dedicated-to-controllers
```
The above command will add the following [tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) to all the controllers pods:
```yaml
kind: Deployment
spec:
template:
spec:
nodeSelector:
kubernetes.io/os: linux
tolerations:
- key: node.kubernetes.io/dedicated-to-flux
operator: Exists
- key: node.kubernetes.io/dedicated-to-controllers
operator: Exists
```
Ref: https://github.com/fluxcd/flux2/discussions/895 and https://github.com/fluxcd/terraform-provider-flux/issues/93
=> Allow Flux to be deployed on tainted Kubernetes nodes

cmd/flux/bootstrap.go, cmd/flux/bootstrap_github.go, cmd/flux/bootstrap_gitlab.go, cmd/flux/install.go, pkg/manifestgen/install/install.go
This PR changes the commit messages of `flux bootstrap` to include the actual flux version even when using latest.
Example:
```
flux bootstrap github \
--owner=stefanprodan \
--repository=test \
--branch=main \
--path=./clusters/my-cluster \
--personal
```
Ref: #723
=> Add flux version to bootstrap commit messages

.github/workflows/bootstrap.yaml, .github/workflows/e2e.yaml, cmd/flux/main.go, cmd/flux/uninstall.go, docs/cmd/flux.md, docs/cmd/flux_uninstall.md, docs/guides/installation.md, internal/utils/utils.go
This is a complete rewrite of `flux uninstall` in Go without any shell-execs to kubectl. 
The uninstall command performs the following operations:
- deletes Flux components (deployments and services)
- deletes Flux network policies
- deletes Flux RBAC (service accounts, cluster roles and cluster role bindings)
- removes the **Kubernetes finalizers** from Flux custom resources in all namespaces
- deletes Flux custom resource definitions and custom resources from all namespaces
- deletes the namespace where Flux was installed if `--keep-namespace=false`
**Breaking changes**:
- the `uninstall` command will no longer remove any Kubernetes objects or Helm releases that were reconciled on the cluster by Flux
- the `crds` and `resources` arguments were removed
Example:
```console
$ flux …
```
=> Refactor flux uninstall command

docs/dev-guides/debugging.md, mkdocs.yml
Fix: #873
Should not be merged before the controllers have seen a release.
=> Add guide for pprof endpoints

cmd/flux/bootstrap.go, cmd/flux/create_secret_git.go, cmd/flux/create_source_git.go, docs/cmd/flux_create_secret_git.md, docs/cmd/flux_create_source_git.md
=> Add caFile to create source/secret git commands

docs/guides/flux-v1-automation-migration.md, docs/guides/sortable-image-tags.md, mkdocs.yml
Ref: #736
TODO:
- how to pause an automation
- how to lock an image where it is
=> Image automation migration guide

cmd/flux/create_helmrelease.go, go.mod, go.sum, internal/utils/utils.go
pkg/runtime v0.8.2 introduces runtime/transform which includes `MergeMaps`: https://github.com/fluxcd/pkg/pull/85
=> Use `MergeMaps` from pkg/runtime v0.8.2

docs/guides/sealed-secrets.md
- Update to sealed secrets 1.13 helm chart. 1.10 is no longer available.
- Use `--dry-run=client` with kubectl. `--dry-run` on its own is deprecated.
=> A few minor updates to sealed secrets docs

.goreleaser.yml
=> Exclude ARM archs from Darwin release builds

docs/roadmap/index.md
Changes:
- Add draft GA roadmap
- Add production ready section to clarify which APIs and controllers are considered production ready
- Clarify that image update automation based on timestamps found inside image layers has been deprecated
Preview here: https://toolkit.fluxcd.io/roadmap/
=> Add production ready and GA sections to roadmap

cmd/flux/check.go
This ensures the advertised version from e.g. GKE or EKS (for example
`v1.17.15-gke.800`) do not trigger a false warning.
Fixes #947
=> Include prerelease data in k8s version constraints

docs/guides/image-update.md
Kustomize doesn't support local bases in sibling directories from the same archive.
( go-getter limitation: https://github.com/kubernetes-sigs/kustomize/issues/2538#issuecomment-634970648 )
Quick fix for this broken example while we work on additional docs to help people fork into their repos.
@stefanprodan @kingdonb
problem:
```shell
kustomize build https://github.com/fluxcd/flux2/archive/main.zip//flux2-main/manifests/integrations/registry-credentials-sync/_base
kustomize build https://github.com/fluxcd/flux2/archive/main.zip//flux2-main/manifests/integrations/registry-credentials-sync/azure
Error: accumulating resources: 2 errors occurred:
* accumulateFile error: "accumulating resources from '../_base': evalsymlink failure on '/tmp/kustomize-462235843/_base' : lstat …
```
=> Use git remote-base instead of zip-archive for cloud image-update example

.github/workflows/update.yaml
To prevent false `go.mod` modifications.
=> Properly setup Go version in update workflow

.github/workflows/bootstrap.yaml, .github/workflows/e2e.yaml, .github/workflows/release.yaml, .github/workflows/scan.yaml, .gitignore, Makefile, cmd/flux/bootstrap.go, cmd/flux/embed.go, cmd/flux/install.go, cmd/flux/main.go, cmd/flux/version.go, docs/cmd/flux_bootstrap.md, docs/cmd/flux_bootstrap_github.md, docs/cmd/flux_bootstrap_gitlab.md, docs/cmd/flux_install.md, manifests/scripts/bundle.sh, pkg/manifestgen/install/install.go, pkg/manifestgen/install/install_test.go
This PR allows using the flux `install` and `bootstrap` commands in environments without access to GitHub releases (ref: https://github.com/fluxcd/flux2/discussions/913). 
Changes:
- add make target for generating the manifests using kustomize
- embed the generated manifests in flux binary
- use the embedded manifests by default in install and bootstrap commands
- download the manifests from GitHub only if the install/bootstrap `--version` arg is set to `latest` or to a value that's different to the CLI version
=> Embed the Kubernetes manifests in flux binary

cmd/flux/bootstrap.go, cmd/flux/bootstrap_github.go, cmd/flux/bootstrap_gitlab.go, cmd/flux/create_secret.go, cmd/flux/create_secret_git.go, cmd/flux/create_secret_helm.go, cmd/flux/create_secret_tls.go, cmd/flux/create_source_git.go, cmd/flux/create_source_helm.go, docs/cmd/flux_create_secret_helm.md, docs/cmd/flux_create_source_git.md, go.mod, internal/utils/utils.go, pkg/manifestgen/kustomization/kustomization.go, pkg/manifestgen/kustomization/options.go, pkg/manifestgen/sourcesecret/options.go, pkg/manifestgen/sourcesecret/sourcesecret.go, pkg/manifestgen/sync/sync.go
This includes a change to the `sync` generator to make the deploy
secret name configurable for future implementation by deploy refactor in #968.
=> Add `sourcesecret` and `kustomization` manifestgen

cmd/flux/completion_fish.go, docs/cmd/flux_completion_fish.md
Fixes #995 
This PR updates the documentation and removes the posix style sourcing for fish completions and corrects the file extension for the fish auto-completions.
=> [docs] Fix fish completions example

docs/faq/index.md, docs/guides/helm-operator-migration.md
This PRs adds an entry to the FAQ for users who want to manage Helm releases with kubectl instead of git.
=> faq: Can I use Flux HelmReleases without GitOps?

cmd/flux/create_kustomization.go
This fixes a bug on Windows where the safe relative path would contain
'\' slashes, which are not compatible with the controller.
Fixes: #1006
=> Use path with '/' slashes in created Kustomization

cmd/flux/create_secret_git.go, cmd/flux/create_source_git.go, docs/cmd/flux_create_source_git.md
This was removed by accident in the PR that introduced the new
`manifestgen` packages, and now restored in full glory.
=> Restore default key algorithm flag create source

.github/aur/flux-go/PKGBUILD.template, .github/aur/flux-scm/PKGBUILD.template, .github/workflows/release.yaml, manifests/scripts/bundle.sh
There was an assumption in this script that it is always executed in Git
repository/directory, this is however not always true, for example when
one downloads the `.tar.gz` that is made available for every release
by GitHub (and used in one of our AUR packages).
This commit changes this, and makes the first argument of `bundle.sh`
configurable, so a custom manifests directory can always be defined
_without_ relying on Git.
Omitting it, or passing an empty string, will still fall back to the
previous behavior of using `git rev-parse --show-toplevel`.
=> Make manifests dir `bundle.sh` configurable

docs/core-concepts/index.md
=> docs: fix link to source-controller documentation

docs/guides/mozilla-sops.md
- Switch to batch GPG key creation
- Accurately name the cluster's decryption key
- Suggest password-manager backup
- Optionally cleanup secret key from generating machine
- Optionally commit the public key to the repo for team members
- Document SOPS limitations decryption required for editing / appending fields
=> Improve SOPS GPG guide key management

CONTRIBUTING.md
Changes to contributing doc:
- add image automation repos to GOTK list
- add prerequisites for running the tests locally
=> Add Go 1.16 to prerequisites (contributing doc)

cmd/flux/export_source_bucket.go, cmd/flux/export_source_git.go, cmd/flux/export_source_helm.go, docs/cmd/flux_export_source_bucket.md, docs/cmd/flux_export_source_git.md, docs/cmd/flux_export_source_helm.md
This commit fixes a small typo in the comments for the export source
commands.
Signed-off-by: Lucas Servén Marín <lserven@gmail.com>
=> cmd/flux/export_source*: fix typo in comment

docs/_static/custom.css, docs/migration/timetable.md, docs/roadmap/index.md, mkdocs.yml
Thanks to @stefanprodan for collab on details, and to those who gave feedback on [my initial gist](https://gist.github.com/scottrigby/f9030494d8d6566a983e2d12c87d70de) during the [Feb 25 2001](https://docs.google.com/document/d/1l_M0om0qUEN_NNiGgpqJ2tvsF2iioHkaARDeh6b70B0/view#heading=h.7oos817jjrag) Flux dev meeting.
This PR additionally adds mkdocs `markdown_extensions` and sorts the list alphabetically (I noticed there was one duplicate. May be helpful). Also adds custom admonition for the Timetable page (and anywhere else we want to use it).
You can see the timetable in a (mostly) readable format [HERE](https://github.com/scottrigby/flux2/blob/migration-timetable/docs/migration/timetable.md). That just won't render `^insert me^` as `<INS>`, or `[^1]` as footnotes without the mkdocs md …
=> Migration and Support Timetable

cmd/flux/bootstrap.go, cmd/flux/check.go, cmd/flux/install.go, cmd/flux/status.go, pkg/log/log.go, pkg/status/status.go
This PR moves the `StatusChecker` to a separate package, while
making it more generic so that it is able to assess the status of any
given set of `object.ObjMetadata` identifiers.
=> Move `StatusChecker` to separate and generic pkg

docs/guides/flux-v1-automation-migration.md
The wrong indenting here means the hint body will not display as a hint, this fixes it.
=> Fix hint in Flux v1 Migration guide

cmd/flux/bootstrap_github.go, cmd/flux/bootstrap_gitlab.go, cmd/flux/create_secret_git.go, cmd/flux/create_source_git.go
=> Use Host from parsed URL instead of Hostname

.github/workflows/update.yaml
We noticed that some of our components had not received `go.mod` updates
while they did receive updates for the versions declared in the YAML
manifests.
Was able to trace this back to a behavior change in Go since `1.16.x`,
resulting in it no longer making automated changes to `go.mod` and
`go.sum`[1]. This is an issue for our updater script as it relies
on `go list -m all`, which now after the first `go mod edit` returns:
```console
$ go list -m all
go: github.com/fluxcd/notification-controller/api@v0.10.0: missing
go.sum entry; to add it:
go mod download github.com/fluxcd/notification-controller/api
```
To work around the issue without having to repeatedly call `go mod tidy`,
I have opted to simply `grep` on the contents of `go.mod` as a
workaround.
[1]: …
=> Fix updating of `go.mod` entries for components

cmd/flux/create_image_policy.go, cmd/flux/create_image_repository.go, cmd/flux/create_image_update.go, cmd/flux/logs.go, docs/cmd/flux.md, docs/cmd/flux_create_image_policy.md, docs/cmd/flux_create_image_repository.md, docs/cmd/flux_create_image_update.md, docs/cmd/flux_logs.md
Changes:
- add `--git-repo-path` and `--push-branch` to `flux create image update` cmd
- rename `--branch` to `--checkout-branch` in `flux create image update` cmd
- add examples to `flux create image policy` cmd docs
- update `flux logs` examples
=> Add repo path and push branch to image update cmd

manifests/integrations/registry-credentials-sync/_base/sync.yaml, manifests/integrations/registry-credentials-sync/_cronjobs/_base/sync.yaml, manifests/integrations/registry-credentials-sync/_cronjobs/azure/reconcile-patch.yaml, manifests/integrations/registry-credentials-sync/azure/reconcile-patch.yaml
Hello.
The order of the parameters when calling `apply-secret` on Azure's ACR secret reconcile script is incorrect, it's setting the token where it should be the ACR server name and the other way around.
It's being called like this:
```
apply-secret "${KUBE_SECRET}" "${token}" "${user}" "${server}"
```
but the `apply-secret` function defined on `_base` is: 
```
apply-secret() {
/kbin/kubectl create secret docker-registry "${1}" \
--docker-server="${2}" \
--docker-username="${3}" \
--docker-password="${4}" \
--dry-run=client -o=yaml \
| grep -v "creationTimestamp:" \
| /kbin/kubectl apply -f -
}
```
Since the password is the forth parameter it must be changed to:
```
apply-secret "${KUBE_SECRET}" "${server}" "${user}" "${token}"
```
Kind regards, MA
=> Azure ACR reconcile script fix parameter order

docs/guides/image-update.md
--branch is not a valid flag for this command.
```
Flags:
--author-email string      the email to use for commit author
--author-name string       the name to use for commit author
--checkout-branch string   the branch to checkout
--commit-template string   a template for commit messages
--git-repo-path string     path to the directory containing the manifests to be updated, defaults to the repository root
--git-repo-ref string      the name of a GitRepository resource with details of the upstream Git repository
-h, --help                     help for update
--push-branch string       the branch to push commits to, defaults to the checkout branch if not specified
```
=> Remove branch switch for image update cmd in guide

docs/guides/helm-operator-migration.md
The command to delete the old helm release crd in the docs does not work.
=> Fix CRD deletion instruction in Helm Operator migration docs

cmd/flux/create_secret_git.go, cmd/flux/create_source_git.go, docs/cmd/flux_create_secret_git.md, docs/cmd/flux_create_source_git.md
This commit adds support for supplying a path to an existing private
key file to both the `flux create secret git` and `flux create source
git`
commands.
If a path is given, any private key generation configuration options
are ignored by the manifest generator. The SSH host will however still
be scanned for server keys.
=> Allow supplying PK from file for Git source/secret

docs/guides/flux-v1-automation-migration.md
The text description in the automation migration guide uses a wrong crd schema.
=> Updated automation migration guide filter tags crd

.github/workflows/e2e.yaml, cmd/flux/create_helmrelease.go, cmd/flux/create_kustomization.go, docs/cmd/flux_create_helmrelease.md, docs/cmd/flux_create_kustomization.md, internal/flags/helm_chart_source.go, internal/flags/kustomization_source.go, internal/utils/utils.go
This PR allows sources to be references by namespace (format `<kind>/<name>.<namespace>`) in `flux create kustomization` and `flux create helmrelease` commands.
Ref: #213
=> Add source namespace to create commands

.github/workflows/release.yaml, .gitignore, .goreleaser.yml, Dockerfile
This PR adds the bits and pieces to enable the build of Docker images (and a multi-arch) image for goreleaser, publishing them to both Docker Hub and GHCR.
It offers a workaround for #1125 as described in https://github.com/fluxcd/flux2/issues/1125#issuecomment-806482915.
Release process was tested locally against a fork, see:
- https://hub.docker.com/r/hiddeco/flux-cli/tags
- https://github.com/users/hiddeco/packages/container/package/flux-cli
=> Publish AMD64, ARM64, ARMv7 images for binary

cmd/flux/install.go
Resolves https://github.com/fluxcd/flux2/issues/1204
If the `export` flag exists, print the generated manifest and return from the function; it should prevent any additional steps from being run. 
If the `verbose` flag exists, then print the generated manifest and continue with the function.
=> fix: install command flags logic bug

.github/workflows/bootstrap.yaml, cmd/flux/bootstrap.go, cmd/flux/bootstrap_git.go, cmd/flux/bootstrap_github.go, cmd/flux/bootstrap_gitlab.go, docs/cmd/flux_bootstrap.md, docs/cmd/flux_bootstrap_git.md, docs/cmd/flux_bootstrap_github.md, docs/cmd/flux_bootstrap_gitlab.md, go.mod, go.sum, internal/bootstrap/bootstrap.go, internal/bootstrap/bootstrap_plain_git.go, internal/bootstrap/bootstrap_provider.go, internal/bootstrap/git/git.go, internal/bootstrap/git/gogit/gogit.go, internal/bootstrap/options.go, internal/bootstrap/provider/factory.go, internal/bootstrap/provider/provider.go, pkg/manifestgen/install/templates.go
This pull request changes the implementation used to connect to Git
providers like GitHub from `fluxcd/pkg/git` to `fluxcd/go-git-providers`,
eliminating quite some bugs that were present in the GitLab integration.
In addition to this, the bootstrap logic has been factored out into an
(for now) internal package with two bootstrap "runners" `PlainGitBootstrapper`
and `GitProviderBootstrapper`. The `GitProviderBootstrapper` is a superset
of the `PlainGitBootstrapper` that besides `Reconciler` also implements the
`RepositoryReconciler`.
The Git actions rely on an interface, making it easier to support other
implementations than `go-git` at a later moment, to for example support
bootstrapping to Git servers that only support the v2 protocol.
By doing this, it was possible to introduce a new …
=> Refactor bootstrap to make use of go-git-providers

.github/workflows/e2e.yaml, cmd/flux/bootstrap.go, cmd/flux/bootstrap_git.go, cmd/flux/bootstrap_github.go, cmd/flux/bootstrap_gitlab.go, cmd/flux/create_source_git.go, docs/cmd/flux_bootstrap.md, docs/cmd/flux_bootstrap_git.md, docs/cmd/flux_bootstrap_github.md, docs/cmd/flux_bootstrap_gitlab.md, docs/cmd/flux_create_source_git.md, pkg/manifestgen/sync/options.go, pkg/manifestgen/sync/sync.go
Changes to `flux create source git` command:
- Add `--recurse-submodules` boolean arg 
- Allow recurse submodules only when `--git-implementation=go-git`
- Allow self-signed certs for both `go-git` and `libgit2`
Changes to `flux bootstrap` commands:
- Add `--recurse-submodules` boolean arg
=> Add recurse submodules arg to create source git and bootstrap cmd

README.md, docs/guides/installation.md, docs/guides/mozilla-sops.md, docs/guides/notifications.md, docs/use-cases/azure.md
Changes:
- Document `flux bootstrap git` (followup #968)
- Move Azure DevOps bootstrap to Azure docs
- Add flux CLI container image to docs 
Fix: #1013
=> Revamp bootstrap documentation

cmd/flux/bootstrap_git.go, cmd/flux/bootstrap_github.go, cmd/flux/bootstrap_gitlab.go, cmd/flux/create_kustomization.go, internal/bootstrap/bootstrap.go, internal/flags/safe_relative_path.go
Fixes #1235
```console
C:\Users\IEUser>flux bootstrap github --owner=hiddeco --repository=staple.huge.horse --personal --path=clusters/cozy
► connecting to github.com
► cloning branch "main" from Git repository "https://github.com/hiddeco/staple.huge.horse.git"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ component manifests are up to date
✔ reconciled components
► determining if source secret "flux-system/flux-system" exists
✔ source secret up to date
► generating sync manifests
✔ generated sync manifests
✔ sync manifests are up to date
► applying sync manifests
✔ applied sync manifests
✔ reconciled sync configuration
► confirming components are healthy
✔ helm-controller: deployment ready
✔ notification-controller: deployment ready
✔ …
```
=> Normalize paths to forward slashes

cmd/flux/bootstrap_github.go, cmd/flux/bootstrap_gitlab.go, docs/cmd/flux_bootstrap_github.md, docs/cmd/flux_bootstrap_gitlab.md
To highlight the fact that it configures the repository as defined,
which was not _really_ clear to some users and has resulted in public
repositories accidentally being changed to private (losing important
goodies like stars and linked forks).
Discussion on this is ongoing and there will likely be other
improvements in the near future to protect users against this.
=> Change private flag description

.github/workflows/release.yaml, .goreleaser.yml, manifests/crds/kustomization.yaml
This PR generates OpenAPI schemas for all the GitOps Toolkit CRDs and adds the `crd-schemas.tar.gz` file to the release assets.
Ref: https://github.com/fluxcd/flux2/discussions/408
=> Publish OpenAPI schemas for Flux CRDs

cmd/flux/create_alert.go
Previously I couldn't create the following yaml in the docs using the flux cli
https://github.com/fluxcd/flux2/blob/65d5cadf293663662a756cbbb34d2739508045ab/docs/guides/notifications.md#L209-L221 
Running the create alert command with the appropriate kind/name.namespace resulted in name: <name>.<namespace>
``` bash
$ flux create alert podinfo \ 
--provider-ref flux-system \
--event-severity info \
--event-source Kustomization/podinfo.flux-system \
--namespace flux-system \
--export
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
name: podinfo
namespace: flux-system
spec:
eventSeverity: info
eventSources:
- kind: Kustomization
name: podinfo.flux-system
providerRef:
name: flux-system
```
This fix changes it so the output of the command, matches what
s in the …
=> Change createAlertCmdRun parsing to include namespace

cmd/flux/reconcile_helmrelease.go, cmd/flux/reconcile_kustomization.go, cmd/flux/reconcile_with_source.go
Fixes #1283
I tested these changes and I confirm that I fixed the regression bug introduced in #1224 that prevented users from reconciling a Kustomization or helmrelease when the source is in a different namespace.
=> Ensure kustomization/helmrelease is reconciled when source is in a different namespace

docs/guides/helm-operator-migration.md
[As suggested on Slack](https://cloud-native.slack.com/archives/CLAJ40HV3/p1618498889004400), here is a technique based on customizing `RoleBindings` bound to the Helm Operator `ServiceAccount` so it continues to continuously process legacy `HelmReleases` in all namespaces but the ones in which `HelmReleases` are being migrated to the Helm Controller's.
It follows https://github.com/fluxcd/flux2/pull/1286 up, which was not completely accurate. In fact the Helm Operator requires a cluster-wide read-only role, otherwise it's not able to start its reconciliation loop at all. Credits to @ViBiOh for experimenting and validating the technique.
=> Suggest an alternative gradual migration technique

install/flux.sh
When using tar with sudo the extracted files will retain the ownership
of the files in the archive. When using the bash install script the flux
binary is owned by user ID 1001 and group docker after installation.
This commit fixes the ownership by appending the -o option to the tar
command which will extract files with the correct ownership, namely user
root and group root.
Signed-off-by: Julian Lengelsen <julian.lengelsen@th-koeln.de>
=> Fix ownership issue in bash install script

manifests/policies/allow-egress.yaml, manifests/policies/kustomization.yaml
Kustomize by default reorders resources in "legacy" mode. This is harmful for the network policies, as the order of how they are defined in yaml (and applied) matters. At least for Azure Network policy. Different order leads to different resulting iptables.
This is a simple fix to suppress the default Kustomize reordering for network policies while building the manifests.
Fixes #703
=> Keep network policy order as defined

internal/bootstrap/bootstrap_provider.go
Pushing the first branch is sufficient to set a default, and
README.md (and/or LICENSE) can better be pushed elsewhere so commit
author and templates be configured.
=> Drop AutoInit from Org repository create

cmd/flux/bootstrap_git.go
As otherwise (comparisons to) cluster configuration will fail due to
Separator differences. Was already fixed for provider implementations.
Follow up on #1240
Fixes #1303
=> Use slash target path in Git bootstrap sync opts

cmd/flux/get_all.go, cmd/flux/get_image_all.go, cmd/flux/get_source_all.go, docs/cmd/flux_get.md, docs/cmd/flux_get_all.md, mkdocs.yml
=> Add get all command

cmd/flux/create_helmrelease.go, docs/guides/helm-operator-migration.md, docs/guides/helmreleases.md
- Changes `valuesFile` documentation to `valuesFiles`
- Purposely did not reference `valuesFile` as we would like to move people towards the non-deprecated option
- Updates source-controller/api to latest main (matching changes in helm-controller, source-controller)
- Renames `valuesFile` var to `valuesFiles`
Continuation of https://github.com/fluxcd/source-controller/issues/291, https://github.com/fluxcd/source-controller/pull/305
=> Add `ValuesFiles` documentation

docs/use-cases/helm.md, mkdocs.yml
What is the simplest way to explain how Flux works with Helm to existing Helm users?
There's a lot more we can say, but is there anything critical we think should go into an intro that I'm missing?
See https://github.com/fluxcd/website/issues/120
=> Add Helm use case intro page

docs/use-cases/gh-actions-manifest-generation.md, mkdocs.yml
Closes #1083
Resolves fluxcd/flux#3433
For your review!
I think the level of commentary is about right now. There may still be some rough sections remaining toward the end of the doc. Reviews are appreciated.
=> use-case: GitHub Actions Manifest Generation

.github/workflows/docs.yaml, manifests/crds/kustomization.yaml
Changes:
- bump the CRD versions for the OpenAPI schema generation 
- switch the image automation docs to v1alpha2
=> Update the APIs docs

internal/bootstrap/bootstrap_provider.go
Based on observations in
https://github.com/fluxcd/flux2/runs/2410633975:
1. Print error correctly by switching from `%w` to `%s`
2. Only print the change messsage if there has not been an error.
=> Change permission grant error print conditons

docs/use-cases/azure.md
In docs/use-cases/azure.md, fix the link to the Mozilla SOPS Azure Guide.
=> fix link to Mozilla SOPS Azure Guide

docs/guides/sortable-image-tags.md
Signed-off-by: Frederik Baetens <baetens.fr@gmail.com>
This makes the example a bit simpler, and I think many people will find github.run_number useful, because it saves them from having to define an additional step.
If you feel it's educational to still keep the branch name in the example, I will add that back in.
=> update sortable image tag guide with github.run_number

cmd/flux/create_helmrelease.go, docs/cmd/flux_create_helmrelease.md, docs/guides/sealed-secrets.md, internal/flags/crds.go, internal/flags/crds_test.go
Changes:
- add optional `--crds` arg to `flux create helmrelease` command
- update the sealed-secrets guide with `--crds=CreateReplace`
=> Add upgrade CRDs policy arg to create helmrelease cmd

cmd/flux/get_image_all.go
Before this change, running `get all`:
```
NAME                    READY   MESSAGE                                                         REVISION                                        SUSPENDED 
helmrepository/podinfo  True    Fetched revision: 878b81372f19855d96af071ef089f91a6a323d3c      878b81372f19855d96af071ef089f91a6a323d3c        False           
NAME                            READY   MESSAGE                 REVISION        SUSPENDED 
helmchart/flux-system-podinfo   True    Fetched revision: 4.0.6 4.0.6           False           
✗ no matches for kind "ImageRepository" in version "image.toolkit.fluxcd.io/v1alpha2"
NAME                    READY   MESSAGE                                 REVISION        SUSPENDED 
helmrelease/podinfo     True    Release reconciliation succeeded …
```
=> Remove redundant getCommand for image repository

_redirects, netlify.toml
Add redirects from toolkit.fluxcd.io to fluxcd.io/docs - largely following https://github.com/fluxcd/flux2/discussions/367
One thing which was unfortunately overseen to date is:
User Guides | toolkit.fluxcd.io/guides | fluxcd.io/docs/flux
-- | -- | --
=> add redirects file

README.md, docs/dev-guides/source-watcher.md, docs/get-started/index.md, docs/guides/flux-v1-migration.md, docs/guides/installation.md
As we don't pass '-L' to curl, the redirect is not followed.
=> Update install script URL

.goreleaser.yml, CONTRIBUTING.md, manifests/integrations/registry-credentials-sync/_cronjobs/aws/config-patches.yaml, manifests/integrations/registry-credentials-sync/aws/config-patches.yaml
Following up on #1380, updated some more docs links which now live under fluxcd.io itself.
=> Update more toolkit.fluxcd.io redirects

cmd/flux/docgen.go
=> Remove ' command' from Flux CLI docs title

go.mod, go.sum
This PR updates [go-git-providers](https://github.com/fluxcd/go-git-providers) to v0.1 that contains a fix for the `cacheRoundtripper ` panic. 
Fix: #1383
=> Update go-git-providers to v0.1

cmd/flux/create_source_git.go
Remove the default branch value from `flux create source git` and validate that one of the ref options are specified.
Fix: #1387
=> Make the Git ref required

cmd/flux/bootstrap_git.go
This removes the usage of Hostname() which does not honor configured SSH
port to be used.
Resolves: #1377
See also: #1101, #1102
Signed-off-by: Tobias Jakobsson <jakobsson.tobias@gmail.com>
=> Use proper Host configuration for SSH

cmd/flux/bootstrap_git.go
This changes the logic for the parsing of private keys, as already
done for the source-controller, so that it is able to recognize and
work with a wider range of key formats instead of returning a vague
error:
```console
$ flux bootstrap git [..]
✗ ssh: this private key is passphrase protected
```
A patch for this was already submitted and merged in `go-git/go-git`,
but is not made available in a release yet:
https://github.com/go-git/go-git/pull/298
Fixes #1401
=> Switch to `crypto/ssh` for parsing of private keys

manifests/integrations/registry-credentials-sync/_base/sync.yaml
The Kustomization uses a name prefix of `acr-`. The sync deployment uses the `serviceAccount` property in the template. This field is deprecated (Deployments should use `serviceAccountName`) and therefore doesn't get the name prefix during kustomization, resulting in the deploy failing with:
``` 
Error creating: pods "acr-credentials-sync-78c56d4876-" is forbidden: error looking up service account flux-system/credentials-sync: serviceaccount "credentials-sync" not found
```
This is similar to [this issue](https://github.com/kubernetes-sigs/kustomize/issues/505).
=> Fix service account name in registry-credentials-sync deployment kustomization

manifests/integrations/eventhub-credentials-sync/_base/kustomization.yaml, manifests/integrations/eventhub-credentials-sync/_base/kustomizeconfig.yaml, manifests/integrations/eventhub-credentials-sync/_base/sync.yaml, manifests/integrations/eventhub-credentials-sync/_cronjobs/_base/kustomization.yaml, manifests/integrations/eventhub-credentials-sync/_cronjobs/_base/kustomizeconfig.yaml, manifests/integrations/eventhub-credentials-sync/_cronjobs/_base/sync.yaml, manifests/integrations/eventhub-credentials-sync/_cronjobs/azure/az-identity.yaml, manifests/integrations/eventhub-credentials-sync/_cronjobs/azure/config-patches.yaml, manifests/integrations/eventhub-credentials-sync/_cronjobs/azure/kubectl-patch.yaml, manifests/integrations/eventhub-credentials-sync/_cronjobs/azure/kustomization.yaml, manifests/integrations/eventhub-credentials-sync/_cronjobs/azure/kustomizeconfig.yaml, manifests/integrations/eventhub-credentials-sync/_cronjobs/azure/reconcile-patch.yaml, manifests/integrations/eventhub-credentials-sync/_cronjobs/generic/config-patches.yaml, manifests/integrations/eventhub-credentials-sync/_cronjobs/generic/kubectl-patch.yaml, manifests/integrations/eventhub-credentials-sync/_cronjobs/generic/kustomization.yaml, manifests/integrations/eventhub-credentials-sync/_cronjobs/generic/kustomizeconfig.yaml, manifests/integrations/eventhub-credentials-sync/_cronjobs/generic/reconcile-patch.yaml, manifests/integrations/eventhub-credentials-sync/_cronjobs/generic/secret-azure-credentials.yaml, manifests/integrations/eventhub-credentials-sync/azure/az-identity.yaml, manifests/integrations/eventhub-credentials-sync/azure/config-patches.yaml, manifests/integrations/eventhub-credentials-sync/azure/kubectl-patch.yaml, manifests/integrations/eventhub-credentials-sync/azure/kustomization.yaml, manifests/integrations/eventhub-credentials-sync/azure/kustomizeconfig.yaml, manifests/integrations/eventhub-credentials-sync/azure/reconcile-patch.yaml, manifests/integrations/eventhub-credentials-sync/generic/config-patches.yaml, manifests/integrations/eventhub-credentials-sync/generic/kubectl-patch.yaml, manifests/integrations/eventhub-credentials-sync/generic/kustomization.yaml, manifests/integrations/eventhub-credentials-sync/generic/kustomizeconfig.yaml, manifests/integrations/eventhub-credentials-sync/generic/reconcile-patch.yaml, manifests/integrations/eventhub-credentials-sync/generic/secret-azure-credentials.yaml
To use JWT to communicate with Azure eventhub we need to renew the JWT credentials
from time to time.
Supports both deployment and cronjob based renewal
Signed-off-by: Edvin Norling <edvin.norling@xenit.se>
=> Add example manifests for Azure eventhub credentials renewal

manifests/integrations/eventhub-credentials-sync/_base/sync.yaml, manifests/integrations/registry-credentials-sync/_base/sync.yaml, manifests/integrations/registry-credentials-sync/_cronjobs/_base/sync.yaml
* Fixes: #1524
* We remove resourceName due to the following:
Note: You cannot restrict create or deletecollection requests by resourceName.
For create, this limitation is because the object name is not known at authorization time.
* Fix typo in azure-registry cronjob
Signed-off-by: Edvin Norling <edvin.norling@xenit.se>
=> Remove resourceNames in integration secrets

.github/workflows/e2e-arm64.yaml
Until now, we've been running conformance testing of Flux release candidates only on AMD64 Kubernetes clusters (provided by GitHub hosted runners). While GitHub offers no ARM64 runners, we really need to make sure Flux does work on ARM64 as many users have deployed Flux on ARM64 clusters in production.
In order to ensure Flux releases can be run on ARM64, I've created a GitHub self-hosted runner on my personal account in Oracle Could with the following specs:
- VM: Oracle Cloud VM.Standard.A1.Flex 4CPU 24GB RAM
- OS: Linux 5.4.0-1045-oracle 49-Ubuntu SMP aarch64
- Packages: docker, kind, kubectl, kustomize
The ARM64 conformance test suite covers the following:
- Flux CLI can be build on aarch64 and all unit tests are passing
- The Flux controllers can be successfully installed on …
=> Run conformance tests on ARM64 Kubernetes clusters

cmd/flux/create_source_helm.go, go.mod, go.sum
This includes an introduction of a `--pass-credentials` flag for the
`flux create source helm` command to allow configuring the new
option introduced.
=> Update source-controller to v0.15.1

.github/runners/README.md, .github/runners/arm64.sh, .github/workflows/e2e-arm64.yaml
This PR adds the script used to provision the GitHub Actions self-hosted runners for Flux conformance testing on ARM64. The script is accompanied by documentation on how to add an Oracle Cloud Ampere instance to the runners pool.
The ARM64 pool is currently made of two Ampere instances (created on my personal Oracle Cloud account) with 2CPU and 12GB RAM each:
- arm64-runner-1 (test run https://github.com/fluxcd/flux2/runs/2864585134)
- arm64-runner-2 (test run https://github.com/fluxcd/flux2/runs/2864586435)
Followup: #1540
=> Add provisioning script for ARM64 GitHub runners

cmd/flux/create_image_policy.go, cmd/flux/create_image_repository.go, cmd/flux/create_image_update.go, cmd/flux/delete_image_policy.go, cmd/flux/delete_image_repository.go, cmd/flux/delete_image_update.go, cmd/flux/export_image_policy.go, cmd/flux/export_image_repository.go, cmd/flux/export_image_update.go, cmd/flux/get_image_all.go, cmd/flux/get_image_policy.go, cmd/flux/get_image_repository.go, cmd/flux/get_image_update.go, cmd/flux/image.go, cmd/flux/reconcile_image_repository.go, cmd/flux/reconcile_image_updateauto.go, cmd/flux/resume_image_repository.go, cmd/flux/resume_image_updateauto.go, cmd/flux/suspend_image_repository.go, cmd/flux/suspend_image_updateauto.go, internal/utils/utils.go
Makes all the image commands use the v1beta1 version of the API. Since v1beta1 is the same schema as v1alpha2, no changes to the handling of the values need to be made.
=> Use image API v1beta1

manifests/monitoring/grafana/dashboards/control-plane.json
The legend was not showing the Pod name, instead the whole resource in
the dashboard
As a result, use the correct Prometheus label
For example, this was displayed previously
With this PR, it'll look like this
Resolves:
Related:
=> fix Control Plane dashboard legend

manifests/monitoring/monitoring-config/podmonitor.yaml
`targetPort` is deprecated since prometheus-operator 0.38.0 (changelog: https://github.com/prometheus-operator/prometheus-operator/blob/master/CHANGELOG.md#0380--2020-03-20).
=> Update podmonitor example

cmd/flux/get.go
This PR adds a  --no-header flag for all of the get commands. When the flag is provided, the table header is not printed. Closes #1585
=> Add no-header flag for get commands to omit printing the header

cmd/flux/get.go, cmd/flux/get_alert.go, cmd/flux/get_alertprovider.go, cmd/flux/get_helmrelease.go, cmd/flux/get_image_policy.go, cmd/flux/get_image_repository.go, cmd/flux/get_image_update.go, cmd/flux/get_kustomization.go, cmd/flux/get_receiver.go, cmd/flux/get_source_bucket.go, cmd/flux/get_source_chart.go, cmd/flux/get_source_git.go, cmd/flux/get_source_helm.go
Signed-off-by: Chanwit Kaewkasi <chanwit@gmail.com>
This PR implements status-selector for the `get` commands.
Fixes #1587
=> Add status-selector flag for get commands to filter results based on status conditions

internal/utils/testdata/components-with-crds.yaml, internal/utils/testdata/components-without-crds.yaml, internal/utils/utils.go, internal/utils/utils_test.go
Add unit tests for various utils functions.
Signed-off-by: Sunny <darkowlzz@protonmail.com>
=> internal/utils: Add unit tests

cmd/flux/trace.go
Check for existence of GitRepository.Spec.Reference when displaying a trace to
avoid error:
✗ template: tmpl:28:21: executing "tmpl" at <.GitRepository.Spec.Reference.Tag>: nil pointer evaluating *v1beta1.GitRepositoryRef.Tag
Fixes issue #1621
Manually tested using the use cases highlighted in the issue.
Signed-off-by: Allen Porter <allen@thebends.org>
=> Fix trace for optional GitRepository.Spec.Reference

.github/ISSUE_TEMPLATE/bug_report.yaml
This commit adds suggestion for some of the required fields because
there can be a few exceptions in which these values can not be
provided. For example when the `flux` binary can not be installed, or
the set of controllers has been installed with just an `install.yaml`
file.
We use this approach instead of making the fields optional because it
guides people to provide the information whenever they can, which
should result in higher quality bug reports.
As a tiny addition, the reference to "Flux v2" has been renamed to just
"Flux" as we are slowly transitioning "Flux v1" into "Flux Legacy".
=> Provide suggestion for some fields in bug report

cmd/flux/main.go, cmd/flux/testdata/trace/deployment.txt, cmd/flux/testdata/trace/deployment.yaml, cmd/flux/testdata/trace/helmrelease-missing-git-ref.txt, cmd/flux/testdata/trace/helmrelease-missing-git-ref.yaml, cmd/flux/testdata/trace/helmrelease.txt, cmd/flux/testdata/trace/helmrelease.yaml, cmd/flux/testdata/trace/no-args.txt, cmd/flux/trace.go, cmd/flux/trace_test.go, go.mod, go.sum, internal/utils/utils.go
Add tests for flux trace command that fake out the kubernetes client,
load objects from a yaml file and create them in the client, and
assert on the output of the trace command to an expected golden file.
Follow up from the suggestions in PR https://github.com/fluxcd/flux2/pull/1626 which suggested that additional
testing would be helpful. This test approach is modeled after the helm command tests.
This required some changes to the kubernetes client setup to make it possible to use a fake.  If we agree this pattern makes sense, it can be applied to other commands (kube client creation, and test library setup could be moved to a common place). An alternative could be to use `envtest` which seemed much more heavyweight. Another alternative could be to declare all the objects in go code …
=> Add tests for flux trace command

cmd/flux/alert.go, cmd/flux/alert_provider.go, cmd/flux/helmrelease.go, cmd/flux/image.go, cmd/flux/kustomization.go, cmd/flux/object.go, cmd/flux/receiver.go, cmd/flux/reconcile.go, cmd/flux/source.go
This should prevent the generation of the object getting bumped, as
observed on a GKE K8s 1.18 cluster using the  logic before this commit.
We only want to generation to increase when there are actual changes to
the `spec` of a resource, as some controllers use the `generation`
value to make assumptions about what they should do during a
reconciliation.
Ref: https://github.com/fluxcd/helm-controller/issues/295
=> Request reconcile using patch instead of update

cmd/flux/create_secret_git.go, cmd/flux/create_secret_helm.go, cmd/flux/create_secret_tls.go
=> feat: display success message while create secrets via `flux` cli.

cmd/flux/main_test.go
Replace use of `init()` function with a `TestMain` which is the right way to do test setup and teardown.
=> Replace init() with TestMain()

cmd/flux/create_tenant.go, cmd/flux/get.go, cmd/flux/get_alert.go, cmd/flux/get_alertprovider.go, cmd/flux/get_all.go, cmd/flux/get_helmrelease.go, cmd/flux/get_image.go, cmd/flux/get_image_all.go, cmd/flux/get_image_policy.go, cmd/flux/get_image_repository.go, cmd/flux/get_image_update.go, cmd/flux/get_kustomization.go, cmd/flux/get_receiver.go, cmd/flux/get_source.go, cmd/flux/get_source_all.go, cmd/flux/get_source_bucket.go, cmd/flux/get_source_chart.go, cmd/flux/get_source_git.go, cmd/flux/get_source_helm.go, cmd/flux/main_test.go, go.sum, internal/utils/utils.go
Fix: #1586 
The new flag fetch and display the request ressource and then continue
watching the ressource until timeout or cancellation.
A single ressource/ressource type is supported.
=> Adds a watch flag to the get command

.github/workflows/e2e.yaml, Makefile, cmd/flux/install_test.go, cmd/flux/main_test.go, cmd/flux/testdata/install/install_extra_components.golden, cmd/flux/testdata/install/install_no_args.golden, cmd/flux/testdata/uninstall/uninstall.golden, cmd/flux/testdata/uninstall/uninstall_extra_components.golden, cmd/flux/trace_test.go, go.sum, internal/flags/crds_test.go, internal/flags/decryption_provider_test.go, internal/flags/ecdsa_curve_test.go, internal/flags/git_implementation_test.go, internal/flags/helm_chart_source_test.go, internal/flags/helm_release_values_test.go, internal/flags/kustomization_source_test.go, internal/flags/log_level_test.go, internal/flags/public_key_algorithm_test.go, internal/flags/rsa_key_bits_test.go, internal/flags/safe_relative_path_test.go, internal/flags/source_bucket_provider_test.go, internal/utils/utils_test.go, pkg/manifestgen/sourcesecret/sourcesecret_test.go, pkg/manifestgen/sync/sync_test.go, pkg/status/status.go
This PR implements multiple test modes for e2e.
In addition to fakeKubeManager, we add 2 modes of testEnv:
- testEnv's controlplane only, and 
- the existing cluster mode
This PR also implements 2 test cases for `flux install` and `flux install --component-extras` using the existing cluster mode. 
Signed-off-by: Chanwit Kaewkasi <chanwit@gmail.com>
=> Implement testEnv for e2e tests

cmd/flux/check_test.go, cmd/flux/main_test.go, cmd/flux/testdata/check/check_pre.golden
This PR implements an e2e test case for the `flux check --pre` happy path.
To this end, this PR adds a templating mechanism for golden files.
=> Add e2e test case fo check --pre

manifests/integrations/registry-credentials-sync/azure/reconcile-patch.yaml
https://fluxcd.io/docs/components/kustomize/kustomization/#variable-substitution
> Note that if you want to avoid var substitutions in scripts embedded in ConfigMaps or container commands, you must use the format $var instead of ${var}. All the undefined variables in the format ${var} will be substituted with string empty, unless a default is provided e.g. ${var:=default}.
https://cloud-native.slack.com/archives/CLAJ40HV3/p1629301869218600?thread_ts=1629215863.169600&cid=CLAJ40HV3
=> Avoid substitution issue in kustomize for azure credentials sync

.github/workflows/e2e-arm64.yaml
Currently the ARM64 tests are broken in main branch, this PR fixes CI by switching the e2e tests to controller-runtime envtest.
=> Move arm64 e2e to Go tests

cmd/flux/check_test.go, cmd/flux/helmrelease_test.go, cmd/flux/image_test.go, cmd/flux/kustomization_test.go, cmd/flux/main_test.go, cmd/flux/trace_test.go, cmd/flux/version_test.go
Replace the 4 arguments to cmdTestCase with a function that
can let tests run arbitrary logic if it is more complex than
what is provided by the test harness. Move the existing logic
into functions that the test can use for common checks on
golden files and golden values.
These changes were pulled out of PR #1696 to make a smaller review.
=> Make test harness more flexible with functions

CONTRIBUTING.md, cmd/flux/check_test.go, cmd/flux/helmrelease_test.go, cmd/flux/image_test.go, cmd/flux/kustomization_test.go, cmd/flux/main_e2e_test.go, cmd/flux/main_test.go, cmd/flux/main_unit_test.go, cmd/flux/testdata/helmrelease/delete_helmrelease_from_git.golden, cmd/flux/testdata/helmrelease/reconcile_helmrelease_from_git.golden, cmd/flux/testdata/helmrelease/resume_helmrelease_from_git.golden, cmd/flux/testdata/helmrelease/suspend_helmrelease_from_git.golden, cmd/flux/testdata/kustomization/delete_kustomization_from_git.golden, cmd/flux/testdata/kustomization/reconcile_kustomization_from_git.golden, cmd/flux/testdata/kustomization/resume_kustomization_from_git.golden, cmd/flux/testdata/kustomization/suspend_kustomization_from_git.golden, cmd/flux/testdata/trace/deployment.golden, cmd/flux/testdata/trace/deployment.yaml, cmd/flux/testdata/trace/helmrelease.golden, cmd/flux/testdata/trace/helmrelease.yaml, cmd/flux/trace_test.go, cmd/flux/version_test.go
Speed up unit tests by using a shared envTest. This requires each
test to use its own namespace to avoid clobbering objects for
other tests. Tests previously took around 8 seconds each, and now
the initial test takes 2 seconds with follow up tests taking less
than a second each.
Share gold file template function with yaml files.
Remove the testClusterMode, and instead rely on MainTest to do
the appropriate test setup and rootArgs flag setup. Move the
rootArg flag setup out of NewTestEnvKubeManager to avoid
side effects.
A follow up change can be to push the individual setups
from NewTestEnvKubeManager() into their respective TestMain since
the harness share little code.
=> Use shared envTest for unit tests

cmd/flux/main_test.go
Remove deprecated io/ioutil call to `ioutil.WriteFile` and replace with `os.WriteFile`.
Issue #1658
=> Remove use of deprecated io/ioutil

cmd/flux/create_source_git_test.go, cmd/flux/main_test.go, cmd/flux/main_unit_test.go, cmd/flux/testdata/create_source_git/success.golden
Add unit tests for `create source git`.
The create source tests are more interesting than the existing unit tests as they
create objects then wait for the flux source reconciler to complete. The tests
simulate this with a background goroutine that waits for an object to be
created then uses a test specific function to update it.  The reconciler was
implemented assuming that it might be possible to make it more generic
in the future if needed by additional tests.
The tests set a timeout so that if there is a failure they timeout somewhat
quickly rather than hanging for a longer period of time.
Issue #1603
=> Add tests for create source git

cmd/flux/bootstrap_git.go, internal/bootstrap/bootstrap.go, internal/bootstrap/bootstrap_plain_git.go, internal/bootstrap/git/git.go, internal/bootstrap/git/gogit/gogit.go
When a user provided the `--ca-file` flag to the `bootstrap` command,
the given CA file wasn't taken into account for cloning the repository
locally. It was just passed along to the CR that is created so Flux
can make use of it when cloning the repository in-cluster.
However, users may not want to add a custom CA to their local host's
trust chain and may expect the `--ca-file` flag to be respected also
for cloning the repository locally. This is what this commit
accomplishes.
closes #1775
Signed-off-by: Max Jonas Werner <mail@makk.es>
=> feat: enable bootstrap with custom CA locally

cmd/flux/create_source_bucket.go
Found a bug while creating a bucket source with the ```--secret-ref``` Flag.
Signed-off-by: Fynn Späker <spaeker@23technologies.cloud>
=> Fix Bucket SecretRef mapping

Makefile
Allow specifying the version when building the CLI binary with Make. This is useful for projects such as EKS Anywhere that distribute their own Flux CLI binary.
Example usage:
```bash
FLUX_TAG="v0.17.0"
git clone https://github.com/fluxcd/flux2.git
cd flux2
git checkout $FLUX_TAG
FLUX_VERSION=${FLUX_TAG#"v"}
make build VERSION=$FLUX_VERSION
```
Ref: https://github.com/aws/eks-anywhere/issues/143
=> Add version arg to make build

go.mod, go.sum
This PR replaces promptui with a fork that has no dependencies on LGPL code. When https://github.com/manifoldco/promptui/pull/181 is merged we can switch back.
Ref: https://github.com/aws/eks-anywhere/issues/143
=> Replace promptui pkg with a fork free of LGPL

.github/workflows/bootstrap.yaml, .github/workflows/scan.yaml, .gitignore, Makefile
Using the directory cmd/flux/manifests as a prerequisite causes a problem: if the script that creates the files within fails, the next invocation of make will see the directory and assume it succeeded. Since the executable expects certain files to be present, but they are not explicit prerequisites of the recipe for building the binary, this results in a successful build but a broken `flux` executable.
Instead, depend on a file that's explicitly updated when the script has succeeded, and which itself depends on the inputs.
=> Use a file to record successful manifests build

cmd/flux/completion_zsh.go
This PR fixes `flux completion zsh` to work with `source` only.
`flux completion zsh` does not work with `source <(flux completion zsh)`, and needs to be executed as follows:
```
source <(flux completion zsh) && compdef _flux flux
```
This is confusing to Kubernetes users because `kubectl completion zsh` works well with `source <(kubectl completion zsh)`.
Fixes https://github.com/fluxcd/flux2/issues/971
=> Fix `flux completion zsh` to work with `source` only

cmd/flux/create_helmrelease.go
This fixes the case where you create a HelmRelease with `--export` and
the `install: {}` field being there, adding no value to the manifest.
Context: https://cloud-native.slack.com/archives/CLAJ40HV3/p1631797885154100
Before:
```
$ ./bin/flux create hr podinfo --source HelmRepository/podinfo.flux-system --chart=podinfo --chart-version="4.0.x" --interval=1m --export
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
name: podinfo
namespace: flux-system
spec:
chart:
spec:
chart: podinfo
sourceRef:
kind: HelmRepository
name: podinfo
namespace: flux-system
version: 4.0.x
install: {}
interval: 1m0s
```
After:
```
$ ./bin/flux create hr podinfo --source HelmRepository/podinfo.flux-system --chart=podinfo --chart-version="4.0.x" --interval=1m --export
---
apiVersion: …
```
=> fix: don't set 'Install' field by default in 'create hr'

.github/workflows/release.yaml
There's another location which uses the "manifests directory" target directly, but isn't run when testing a PR: the release workflow.
=> Update Makefile target in release workflow

cmd/flux/bootstrap.go, cmd/flux/bootstrap_github.go, internal/bootstrap/bootstrap_provider.go
Fixes #1452 
This pull request doesn't reconcile a team if the team already exists and the reconcile flag wasn't passed in. 
It also adds a feature where a user can specify the level of access that can be given to a team through the `--team` flag. It maintains backwards compatibility by defaulting to maintainer access if no access level is specified.
Example
`flux bootstrap github --team=eng:admin` -> Gives eng team admin access
`flux bootstrap github --team=eng` -> Gives eng team maintainer access
=> Extend `--team` flag to include access level

cmd/flux/check.go, cmd/flux/testdata/check/check_pre.golden
Update the `flux check` command to the new minimum supported version of Kubernetes required by server-side apply:
| Kubernetes version | Minimum required |
| --- | --- |
| `v1.16` | `>= 1.16.11` |
| `v1.17` | `>= 1.17.7` |
| `v1.18` | `>= 1.18.4` |
| `v1.19` and later | `>= 1.19.0` |
Part of: #1889 
⚠️ This PR is made against the `ssa` branch which is used to collect all SSA related changes.
=> Update Kubernetes version minimum requirements

.github/workflows/e2e.yaml, cmd/flux/create_kustomization.go, cmd/flux/delete_kustomization.go, cmd/flux/export_kustomization.go, cmd/flux/get_all.go, cmd/flux/get_kustomization.go, cmd/flux/kustomization.go, cmd/flux/kustomization_test.go, cmd/flux/main.go, cmd/flux/reconcile_kustomization.go, cmd/flux/resume_kustomization.go, cmd/flux/suspend_kustomization.go, cmd/flux/trace.go, cmd/flux/uninstall.go, go.mod, go.sum, internal/bootstrap/bootstrap.go, internal/bootstrap/bootstrap_plain_git.go, internal/utils/utils.go, manifests/bases/kustomize-controller/kustomization.yaml, pkg/manifestgen/sync/sync.go, pkg/manifestgen/sync/sync_test.go, tests/azure/azure_test.go, tests/azure/util_test.go
This PR updates the kustomize-controller API to v1beta2 from https://github.com/fluxcd/kustomize-controller/pull/426 and deprecates the `--validation` arg in `flux create kustomization` command.
⚠️ Note that the kustomize-controller container image is set to the release candidate build.
Part of: #1889 
⚠️ This PR is made against the `ssa` branch which is used to collect all SSA related changes.
=> Update kustomize-controller API to v1beta2

cmd/flux/create_source.go, cmd/flux/create_source_bucket.go, cmd/flux/create_source_git.go, cmd/flux/create_source_helm.go
This PR adds an optional arg `--fetch-timeout` to all `flux create source` commands.
Adresses https://github.com/fluxcd/flux2/discussions/1991
Example:
```console
$ flux create source git podinfo --fetch-timeout=55s --url=ssh://git@github.com/stefanprodan/podinfo --branch=master --export
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
name: podinfo
namespace: test-system
spec:
interval: 1m0s
ref:
branch: master
timeout: 55s
url: ssh://git@github.com/stefanprodan/podinfo
```
=> Add fetch timeout arg to create source commands

cmd/flux/check.go, cmd/flux/logs.go, cmd/flux/uninstall.go, cmd/flux/version.go, pkg/manifestgen/labels.go
Use `app.kubernetes.io/part-of: flux` label instead of `app.kubernetes.io/instance` to select the in-cluster objects used in flux version, check, logs and uninstall commands.
Fix: #1894
=> Switch to `app.kubernetes.io/part-of` label selector

cmd/flux/bootstrap.go, cmd/flux/create_secret_git.go
Motivation: RSA SHA-1 SSH keys are no longer accepted by GitHub https://github.blog/2021-09-01-improving-git-protocol-security-github/.
Given this we are switching the default from RSA to ECDSA for `git`, `github` and `gitlab` variants of `flux bootstrap`.
Fix: #2040
=> bootstrap: Set ECDSA as the default SSH key algorithm

cmd/flux/create_source_git.go
=> Set ECDSA as the default algorithm for `flux create source git`

pkg/manifestgen/install/manifests.go
We need to use full domain name for http urls as some users may deploy flux in environments that use http proxy to access internet.
In such environments they normally add `.cluster.local` and `.local` suffixes to `no_proxy` variable in order to prevent cluster-local traffic from going through http proxy. Without fully specified domain they need to mention `notifications-controller`  explicitly in `no_proxy` variable after debugging http proxy logs.
=> Use full domain name for notification-controller

cmd/flux/bootstrap_github.go, cmd/flux/bootstrap_gitlab.go, cmd/flux/main.go, go.mod
This change adds functionality to both, `bootstrap github` and
`bootstrap gitlab` to prompt the user for the personal access tokens
if those can't be derived from the shell environment. Echoing is
turned off for better privacy.
Instead of having to interactively type the token or manually paste it
from the clipboard, users can also pipe it to Flux which comes in
handy e.g. when executing Flux remotely over an SSH connection:
```
$ echo 'asdf' | flux bootstrap github
```
Otherwise, Flux will prompt the user:
```
$ flux bootstrap github
Please type your GitHub personal access token:
```
closes #2011
Signed-off-by: Max Jonas Werner <mail@makk.es>
=> feat: prompt for access tokens in 'bootstrap' command

manifests/monitoring/grafana/dashboards/cluster.json
Add new variable to filter by exported namespace.
Edit definition of namespace variable to use grafana custom promql function `label_values`.
Rename variable namespace to operator_namespace.
Rename variable exported_namespace to namespace
Signed-off-by: Daniel AguadoAraujo <daniel.aguadoaraujo@gfk.com>
=> Edit grafana dashboard to be able to filter by namespace

cmd/flux/install.go
Signed-off-by: Jack Evans <jack.evans1@ibm.com>
fix: #2056 
- remove trailing `---` that I missed in the first PR 😢 
- flux bootstrap and flux install commands now generate the exact same thing
=> Remove trailing `---` for `flux install` to match `flux bootstrap` generated YAML

.github/workflows/release.yaml, .goreleaser.yml
Signed-off-by: Chanwit Kaewkasi <chanwit@gmail.com>
This change publishes the auto-generated JSON schemas as a single URL,
so that it is consumable by a tool like VS Code.
The CRD generator creates 2 files, a tar.gz for Kubeval,
and another one is a JSON file. The JSON file is a combination of
all schemas, put under the "oneOf" operator.
This PR depends on https://github.com/fluxcd/pkg/pull/189.
=> Publish OpenAPI JSON schemas for Visual Studio Code IntelliSense

cmd/flux/tree_kustomization.go
Fix: #1658 this was the last place where `ioutil` was used in Flux v2 and the GitOps Toolkit controllers.
=> Remove deprecated `io/ioutil` from `flux tree`

cmd/flux/bootstrap_github.go
Remove extra space in check for ca file.
=> Fix GitHub bootstrap when using custom TLS CA

.github/runners/README.md, .github/runners/prereq.sh, .github/runners/runner-setup.sh, .github/workflows/e2e-arm64.yaml
Move the runners from Oracle Cloud free tier to Equinix ARM64 hardware (account sponsored by CNCF).
| Runner        | Instance            | Region |
|---------------|---------------------|--------|
| equinix-arm-1 | flux-equinix-arm-01 | AMS1   |
| equinix-arm-2 | flux-equinix-arm-01 | AMS1   |
| equinix-arm-3 | flux-equinix-arm-01 | AMS1   |
| equinix-arm-4 | flux-equinix-arm-02 | DFW2   |
| equinix-arm-5 | flux-equinix-arm-02 | DFW2   |
| equinix-arm-6 | flux-equinix-arm-02 | DFW2   |
PS. @squaremo @hiddeco you can delete your Oracle runners after this PR is merged.
=> Run the ARM64 e2e tests on Equinix hardware

manifests/monitoring/kube-prometheus-stack/release.yaml
Something wrong (a bug) in kube-prometheus-stack 20.0.0 and on has broken our example.
See:
* https://github.com/fluxcd/flux2/pull/2193 and
* #2192 for more information.
=> monitoring: Pin kube-prometheus-stack  to v19.3.0

.github/workflows/e2e.yaml
Update Calico to the latest stable version in end-to-end tests.
Ref: #2152
=> e2e: Update Calico to v3.20

cmd/flux/trace.go
This fixes a styling issue:
```
$ flux --help
Command line utility for assembling Kubernetes CD pipelines the GitOps
way.
Usage:
flux [command]
...
Available Commands:
...
suspend     Suspend resources
trace       trace an in-cluster object throughout the GitOps delivery
pipeline
uninstall   Uninstall Flux and its custom resource definitions
...
```
=> cmd: start trace short description with T

manifests/monitoring/kube-prometheus-stack/release.yaml
this release contains the prometheus operator in version 0.52.1
see https://github.com/fluxcd/flux2/issues/2192 and https://github.com/fluxcd/flux2/pull/2193 for issues
Fix: #2150
=> Update kube-prometheus-stack to 23.2.0

manifests/scripts/bundle.sh
The script now uses the path of the script file itself to determine the
manifests directory paths. This fixes an issue when building the AUR
packages where the check() phase would fail because the git repository
of the package would be used and this would generate invalid paths.
=> Fix ./manifests/scripts/bundle.sh path resolution

.github/runners/prereq.sh
Helm is required to deploy Minio for the source-controller e2e tests.
=> Add the Helm CLI to the GitHub ARM64 runners setup

rfcs/0001-authorization/README.md
This adds an RFC describing how authorisation works as of v0.24. This can then be a baseline for subsequent RFCs changing authorisation, e.g., namespace ACLs and default-untrusted deployments.
=> [RFC-0001] Memorandum on the authorization model

go.mod, go.sum, tests/azure/go.mod, tests/azure/go.sum
This includes the full commit tree to solve both CVE-2020-29652 and
CVE-2021-43565:
https://github.com/golang/crypto/compare/8b5274cf687fd9316b4108863654cc57385531e8...5770296d904e90f15f38f77dfc2e43fdf5efc083
=> Update golang.org/x/crypto to latest main

cmd/flux/bootstrap_git.go
Hello
This PR is related to [this one](https://github.com/fluxcd/flux2/pull/2216) and both them should be closed once this one is merged :)
**The problem:**
When you use the bootstrap command on Flux CLI using the generic git subcommand, the port is always removed from the URL that is written on gotk-sync.yaml. If you use a Git server on non-standard port this is a problem. Removing this line will keep the port untouched, when it is standard and when it is not.
**The proof:**
As you can see in the commits, I squashed previous ones but I can not clean it better now again because some others were merged in the middle and some of them are not shown in the git rebase -i
As far as I can not control the right behavior to upload the clean PR, I preferred to open this one without dust
=> Fix port overwrite for `flux bootstrap git`

.github/workflows/e2e.yaml, .gitignore, Makefile
Refactor logic to install helper tools into one function in the
Makefile. Add support for envtest to help install tools like kubectl,
etcd which helps users run tests more conveniently.
Ref: https://github.com/fluxcd/flux2/issues/2273
Signed-off-by: Sanskar Jaiswal <jaiswalsanskar078@gmail.com>
=> Fix makefile envtest setup and usage

.github/aur/flux-scm/PKGBUILD.template
For users who build their packages inside containers (for example aurutils with the `-c` flag), git may not yet be installed and therefore needs to be in the makedepends. This is also recommended on [the VCS package guildlines](https://wiki.archlinux.org/title/VCS_package_guidelines). This patch adds `git` to the `makedepends` for the flux-scm aur package.
I also ran into an issue where the `cmd/flux/manifests` make target does not exist. I think it was updated to `cmd/flux/.manifests.done` in 7ae4f2892035d9a8c22505905035092a340a7592 so I've updated it in this patch.
I've written a Dockerfile to recreate the issue. Simply pop this into a file named `Dockerfile` and run `docker build -t fluxtest .` and it will fail to build the package:
```
Step 12/12 : RUN makepkg -s --noconfirm --nocheck …
```
=> Add git build dependency to flux-scm

cmd/flux/trace.go, cmd/flux/trace_test.go
With the `--kind` and `--api-version` flags `flux trace` is pretty tedious to use, especially with custom resources. This PR adds support for using `<resource>/<name>` and `<resource> <name>` instead, like with `kubectl` commands.
Instead of
```
flux trace --api-version helm.toolkit.fluxcd.io/v2beta1 --kind HelmRelease -n flux-system prometheus
```
you can use
```
flux trace -n flux-system helmrelease prometheus
```
It is using the same logic from `k8s.io/cli-runtime` that's used within `kubectl`.
`internal/utils/restclientgetter.go` is something that should really be added to `k8s.io/cli-runtime` as it's needed to get from a `rest.Config` to a `resource.Builder`, which implements resource fetching with only resource and name.
There are also no tests yet. Just adding them to the list in …
=> Simplify arguments of flux trace command

.github/workflows/bootstrap.yaml
Bootstrap e2e workflow changes:
- delete the repository regardless of the bootstrap test exit code
- wait for image automation to push changes to upstream (max 60s)
=> Improve the bootstrap e2e test workflow

.github/aur/flux-go/PKGBUILD.template, .github/aur/flux-scm/PKGBUILD.template
The `check()` run started to fail after #2288 since `ENVTEST_ARCH` was not
set correctly on ARM/ARM64. This should fix the problem for the flux-go
and flux-scm AUR packages.
=> Fix Archlinux PKGBUILD check() run on ARM

.github/workflows/release.yaml, .goreleaser.yml
Changes to the release workflow:
- generate [SBOM](https://www.linuxfoundation.org/blog/what-is-an-sbom/) for Flux Go modules with [Syft](https://github.com/anchore/syft)
- publish the SBOM [SPDX](https://spdx.dev/) JSON files to GitHub releases with GoReleaser
Depends on: https://github.com/fluxcd/pkg/pull/219
=> Publish Flux Software Bill of Materials (SBOM)

.github/workflows/release.yaml, .goreleaser.yml
This PR implements [cosign](https://www.sigstore.dev) keyless signing for the Flux release artifacts using GoReleaser.
Release workflow changes:
- add the Flux manifests and API schemas to checksums
- sign the checksum.txt with Cosign and GitHub OIDC
- sign the flux-cli container images with Cosign and GitHub OIDC
=> Sign the release artifacts checksums and images

Dockerfile
Update `kubectl` in the flux-cli container image to match the Kubernetes version used in Flux CLI.
=> Update kubectl to 1.23.1 in flux-cli container image

cmd/flux/get_kustomization.go, cmd/flux/get_source_git.go, cmd/flux/testdata/kustomization/get_kustomization_from_git.golden
This pull request shortens the sha1 commit hash from the status of Kustomization and GitRepository custom resource to the first seven digits when displaying output for `flux get kustomization` and `flux get source git`.
Fixes #2186 
=> Shorten Git SHA commit in `flux get` commands output

internal/build/build.go, internal/build/build_test.go, internal/build/diff.go
This adds an up to date license header to the files.
=> Add license Header to internal/build files

manifests/install/namespace.yaml, pkg/manifestgen/install/templates.go
Enable warnings for any violation of the `restrict` [Pod Security Standard](https://kubernetes.io/docs/concepts/security/pod-security-standards/) at the `flux-system` namespace. This only works when [Pod Security Admission Controller](https://kubernetes.io/docs/concepts/security/pod-security-admission/) is installed and enabled, which is the default setting on Kubernetes `v1.23+`.
As of version `v0.26.0` all flux components should be compatible with above mentioned policy. This is not being enforced by default to allow backwards compatibility with users that decided deploying non-flux components into the `flux-system` namespace.
=> [security] Enable pod security warnings for flux-system

Dockerfile
Run the Flux CLI inside the container under the nobody user and group `65534:65534`.
Closes: #2014
=> Run the CLI as non-root

.github/workflows/e2e.yaml, CONTRIBUTING.md, cmd/flux/check.go, cmd/flux/testdata/check/check_pre.golden
Drop support for the Kubernetes versions that have reached end-of-life. Given that Kubernetes between 1.20.0 and 1.20.5 had [a bug](https://github.com/kubernetes/kubernetes/pull/98576) with server-side apply, the `flux check` command constraint has been update to Kubernetes >= 1.20.6.
Part of: https://github.com/fluxcd/flux2/issues/2308
=> Set minimum supported version to Kubernetes 1.20.6

cmd/flux/get_image.go, cmd/flux/get_source.go
Fixes #2346
**Background:**
Cobra will automatically print Usage for commands that do not have a `.RunE`.
All of the `flux get` command tree (including the `flux get` root) have `--watch/-w`
registered as a PersistentFlag.
The `validateWatchOption()` func is used to short circuit runnable sub-commands that
operate on multiple kinds, since the watch is not designed to stream/output multiple GVK's.
**Justification:**
These commands are runnable and need filtering:
- `flux get all`
- `flux get sources all`
- `flux get images all`
These commands are not runnable, so there should be no `RunE` at all:
- `flux get sources`
- `flux get images`
**Current Bug/Inconsistency:**
```shell
$ flux get sources
$ flux get sources -w
✗ expected a single resource type, but found sources
$ flux get images
$ …
```
=> Fix output usage for `flux get <sources|images>`

cmd/flux/testdata/diff-kustomization/diff-with-drifted-service.golden
Kubernetes 1.23.3 comes with a fix where the ports are no longer reordered by the API when performing a sever-side apply dry-run. This PR updates the diff test golden file to match Kubernetes 1.23.3.
=> Adapt diff test to match Kubernetes 1.23.3 API response

internal/build/build.go, internal/build/build_test.go
fixes #2363
If implemented this fixes #2363 and make sure we can build with sops
encrypted data
=> Fix `flux build/diff` when parsing SOPS encrypted secrets

internal/bootstrap/bootstrap_provider.go
If implemented, not retrieving an orgRef will always return an error
=> Fix panic on bootstrap when orgRef is not retrieved

go.mod, internal/build/diff.go
If implemented, when error happens in dry-run and we have pruning
enforced, the deletion message will be consistent
=> Fix wrong deletion message on flux diff

cmd/flux/diff_kustomization_test.go, cmd/flux/main.go, cmd/flux/testdata/build-kustomization/podinfo-result.yaml, cmd/flux/testdata/build-kustomization/podinfo/dockerconfigjson-sops-secret.yaml, cmd/flux/testdata/build-kustomization/podinfo/kustomization.yaml, cmd/flux/testdata/build-kustomization/podinfo/stringdata-secret.yaml, cmd/flux/testdata/diff-kustomization/diff-with-deployment.golden, cmd/flux/testdata/diff-kustomization/diff-with-dockerconfigjson-sops-secret.golden, cmd/flux/testdata/diff-kustomization/diff-with-drifted-key-sops-secret.golden, cmd/flux/testdata/diff-kustomization/diff-with-drifted-service.golden, cmd/flux/testdata/diff-kustomization/diff-with-drifted-value-sops-secret.golden, cmd/flux/testdata/diff-kustomization/diff-with-stringdata-sops-secret.golden, cmd/flux/testdata/diff-kustomization/dockerconfigjson-sops-secret.yaml, cmd/flux/testdata/diff-kustomization/nothing-is-deployed.golden, cmd/flux/testdata/diff-kustomization/stringdata-sops-secret.yaml, internal/build/build.go, internal/build/build_test.go, internal/build/diff.go
If implemented, flux diff kustomization will managed correctly sops
managed dockerconfigjson secrets.
Sops encrypted secret with stringData maps are supported too.
Fix: #2387
Fix: #2388
=> Mask dockerconfigjson secret types and support StringData secrets

internal/flags/safe_relative_path.go, internal/flags/safe_relative_path_test.go
- in `flux bootstrap` and `flux create kustomization` etc.
- E.g. for example `--path=.flux` should work now
- Previous behaviour is to strip off any leading "." and leave you with
"./flux" in the kustomizations / folder structure generated by `flux
bootstrap`
Fixes https://github.com/fluxcd/flux2/issues/1669
=> Add support for Kustomizations with dot-prefixed paths

cmd/flux/create.go, cmd/flux/create_alert.go, cmd/flux/create_alertprovider.go, cmd/flux/create_helmrelease.go, cmd/flux/create_image_policy.go, cmd/flux/create_image_repository.go, cmd/flux/create_image_update.go, cmd/flux/create_kustomization.go, cmd/flux/create_receiver.go, cmd/flux/create_secret_git.go, cmd/flux/create_secret_git_test.go, cmd/flux/create_secret_helm.go, cmd/flux/create_secret_helm_test.go, cmd/flux/create_secret_tls.go, cmd/flux/create_secret_tls_test.go, cmd/flux/create_source_bucket.go, cmd/flux/create_source_git.go, cmd/flux/create_source_git_test.go, cmd/flux/create_source_helm.go, cmd/flux/create_tenant.go, cmd/flux/create_test.go
This pull request validates the name passed to `flux create` commands matches the [RFC 1123 Label Names].(https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names)
=> Validate that object name adheres to RFC 1123 for `flux create` commands

cmd/flux/testdata/trace/deployment.golden, cmd/flux/testdata/trace/helmrelease.golden, cmd/flux/trace_test.go
The TestTrace/Deployment and TestTrace/HelmRelease test cases fail in environments where the timezone isn't UTC, because they compare a local time string to the golden file, which has time in UTC.  Here is an example:
```
--- FAIL: TestTrace (0.12s)
--- FAIL: TestTrace/Deployment (0.08s)
main_test.go:337: Mismatch from golden file 'testdata/trace/deployment.golden': Mismatch from expected value (-want +got):
  strings.Join({
    ... // 88 identical bytes
    " Flux\n---\nHelmRelease:    podinfo\nNamespace:      podinfo-8\nRevi",
    "sion:       6.0.0\nStatus:         Last reconciled at 2021-07-16 ",
-   "15:42:20 +0000 UTC",
+   "09:42:20 -0600 MDT",
    "\nMessage:        Release reconciliation succeeded\n---\nHelmChart:",
    "      podinfo-podinfo\nNamespace: …
```
=> Fix failure in TestTrace/* when timezone isn't UTC

CONTRIBUTING.md, Makefile, cmd/flux/get_alert.go, cmd/flux/get_helmrelease.go, cmd/flux/get_image_policy.go, cmd/flux/get_image_repository.go, cmd/flux/get_image_update.go, cmd/flux/get_kustomization.go, cmd/flux/get_receiver.go, cmd/flux/get_source_bucket.go, cmd/flux/get_source_chart.go, cmd/flux/get_source_git.go, cmd/flux/get_source_helm.go, cmd/flux/main_test.go, cmd/flux/testdata/helmrelease/get_helmrelease_from_git.golden, cmd/flux/testdata/image/get_image_policy_regex.golden, cmd/flux/testdata/image/get_image_policy_semver.golden, cmd/flux/testdata/kustomization/get_kustomization_from_git.golden
- Move `READY` and `MESSAGE` to the end of `get` subcommand output.
- Add test flag `-update` to update the golden files.
- Update the golden files based on the output change using.
Fixes https://github.com/fluxcd/flux2/issues/2385
Associated PRs:
- https://github.com/fluxcd/source-controller/pull/592
- https://github.com/fluxcd/kustomize-controller/pull/578
- https://github.com/fluxcd/helm-controller/pull/425
- https://github.com/fluxcd/notification-controller/pull/337
=> Update `get` subcommand column order

cmd/flux/get.go, internal/build/diff.go, internal/utils/utils.go, pkg/printers/dyff.go, pkg/printers/interface.go, pkg/printers/table_printer.go
If implemented, there will a common interface to print flux resource.
We are adding new way to print resource information e.g. diff of objects (and unified diff in the future).
This will make it easier to add new printers for json, jsonpath, etc... when the need arise.
=> Introduce a printer interface for flux resources

manifests/bases/helm-controller/patch.yaml, manifests/bases/image-automation-controller/patch.yaml, manifests/bases/image-reflector-controller/patch.yaml, manifests/bases/kustomize-controller/patch.yaml, manifests/bases/source-controller/patch.yaml, pkg/manifestgen/install/manifests.go
Add ending dot to the events address to be consistent with source controller address.
This will affect `flux bootstrap` and `flux install` by setting `--events-addr=http://notification-controller.flux-system.svc.cluster.local./`.
=> Use absolute domain name for the events address

cmd/flux/create_source_bucket.go, cmd/flux/create_source_git.go, cmd/flux/create_source_git_test.go, cmd/flux/create_source_helm.go, cmd/flux/reconcile_source_bucket.go, go.mod, go.sum
This ensures the command will wait for the object to report a Ready
Condition with an ObservedGeneration matching the Generation of the
resource. Ensuring that when a "create" is actually a mutation, it waits
instead of prematurely assuming the Source to be Ready.
=> fix: wait for Source objects observed generation

CONTRIBUTING.md
When trying to run the tests on Mac OS Monterey (Apple Silicon), I get this error:
```
❯ make test
./manifests/scripts/bundle.sh
./manifests/scripts/bundle.sh: line 19: realpath: command not found
make: *** [cmd/flux/.manifests.done] Error 127
```
I solved it by doing a `brew install coreutils`. Not sure it's a dependency you'd like to have listed, but it was required for me at least.
=> Add coreutils (for Mac OS) as a dependency

go.mod, go.sum
If implemented, this will provide an inline diff for configmaps with the command `flux diff`.
possibly fixes #2400 
=> Diff: Update homeport/Dyff to v1.5.2

cmd/flux/build_kustomization_test.go, cmd/flux/testdata/build-kustomization/podinfo-kustomization.yaml, cmd/flux/testdata/build-kustomization/podinfo-with-var-substitution-result.yaml, cmd/flux/testdata/build-kustomization/var-substitution/cluster.json, cmd/flux/testdata/build-kustomization/var-substitution/deployment.yaml, cmd/flux/testdata/build-kustomization/var-substitution/kustomization.yaml, go.mod, go.sum
If implemented this fixes a bug where retrieving the groupVersion.Group of a `kustomization` were returning an empty string.
fixes #2598 
=> [Diff] Update pkg/kustomize to v0.1.0

manifests/monitoring/kube-prometheus-stack/release.yaml, manifests/monitoring/monitoring-config/kustomization.yaml
Since kube-prometheus-stack helm chart v32.2.0, the `labelValue` has to
be set to "1" for the default grafana dashboard label selector to select
the flux dashboard configuration.
Refer: https://github.com/prometheus-community/helm-charts/commit/eba5b198f597a39f2d40d3edd209dfa09429623e
Also, update kube-prometheus-stack to v34.7.0, latest.
=> monitoring-config: set grafana dashboards labelValues

cmd/flux/build_kustomization.go, cmd/flux/build_kustomization_test.go, cmd/flux/diff_kustomization.go, internal/build/build.go
If implemented, users will be able to provide a local Flux Kustomization YAML file to `flux build/diff`.
=> Add an option to diff with a local Flux Kustomization file

cmd/flux/delete_kustomization.go
The `flux delete kustomization` docs imply that deleting a Kustomization always deletes the resources created by it.
This is only true when the resource is not `suspended` and when `prune` is enabled.
I think it's clear enough that resources do not do anything when they are suspended, and I don't want to make the doc string too long, but in #2622 at least one user found this doc string wasn't detailed enough and was confused about the behavior.
=> Add detail to delete docs

cmd/flux/bootstrap_git.go
Solves issue #2619 
This PR align the generic `bootstrap git` command with `bootstrap github` and `bootstrap gitlab`, allowing the user to provide password using environment var `GIT_PASSWORD` or be prompted to provide it as an input.
Signed-off-by: Chen Anidam <canidam@gmail.com>
=> bootstrap git: Allow the password to be specified with GIT_PASSWORD env var

rfcs/0002-helm-oci/README.md, rfcs/helm-oci/README.md
Given that Helm v3.8 supports [OCI](https://helm.sh/docs/topics/registries/) for package distribution, we should extend the Flux Source API to allow fetching Helm charts from container registries.
This proposal is for adding OCI support with minimal API changes to Flux.
=> [RFC-0002] Flux OCI support for Helm

go.mod, go.sum, internal/bootstrap/bootstrap_plain_git.go, internal/build/build.go, pkg/manifestgen/install/manifests.go, pkg/manifestgen/kustomization/kustomization.go, pkg/manifestgen/kustomization/options.go
This switches to a secure FS implementation in most places, except for
where we can not make changes at this moment because it would break
behavior.
Not handled in this commit:
- Allowing the root for `manifestgen` packages to be configured.
- Allowing the user to define a working root while building locally.
- Defaulting to the secure FS implementation in
`kustomization.MakeDefaultOptions`. Problem here is that constructing
the secure FS could result in an error, which we can not surface
without signature changes to the constructor func.
=> kustomize: use FS from `fluxcd/pkg`

pkg/manifestgen/install/manifests.go
Use the OS package to write the generated files on disk instead of Flux  secure FS package which is meant for read operations.
Fix: #2699
=> MacOS: fix bootstrap manifest generation

manifests/rbac/controller.yaml
For image automation to use a service account to authenticate to container registries, the controllers need read-only access to service accounts. 
Followup: https://github.com/fluxcd/image-reflector-controller/pull/253
=> Grant service account read-only access to controllers

cmd/flux/bootstrap.go, cmd/flux/bootstrap_bitbucket_server.go, cmd/flux/bootstrap_git.go, cmd/flux/bootstrap_github.go, cmd/flux/bootstrap_gitlab.go, cmd/flux/install.go, pkg/manifestgen/install/install.go, pkg/manifestgen/install/manifests.go, pkg/manifestgen/tmpdir.go
Fixes: #2699 
Signed-off-by: Sanskar Jaiswal <jaiswalsanskar078@gmail.com>
=> Modify tmp dir generation to be absolute on all OSes

cmd/flux/check_test.go
fix e2e check test
The output of `kubectl version` has changed with newer kubectl version
from
```
{
"serverVersion": ...,
"clientVersion": ...
}
```
to
```
{
"serverVersion": ...,
"clientVersion": ...,
"kustomizeVersion": ...
}
```
So the `kustomizeVersion` field is new which causes the JSON
unmarshaling to fail.
We now just unmarshal it to `map[string]interface{}` and peel the
server git version out of that map manually w/o unmarshalling the JSON
into a custom type.
=> fix e2e tests

MAINTAINERS
Part of https://github.com/fluxcd/community/issues/207
=> Move MAINTAINERS to f/community

manifests/monitoring/grafana/dashboards/cluster.json
Signed-off-by: Cristian Chiru <cristi.chiru@gmail.com>
Includes #2717 and #2749 and fixes the exported namespace datasource.
=> grafana: display exported ns, slight resizing, default sorting by state

cmd/flux/create_source_bucket.go, cmd/flux/create_source_git.go, cmd/flux/create_source_git_test.go, cmd/flux/testdata/create_source_git/export.golden
A new --ignore-path flag is added to following commands:
```
flux create source git --ignore-paths ...
flux create source bucket --ignore-paths ...
```
A StringSliceVar is used which supports specifying the flag multiple
times to populate a list or either a comma seperated string value
Fixes https://github.com/fluxcd/flux2/issues/2763
=> Add `--ignore-paths` flag to `flux create source (git|bucket)`

cmd/flux/bootstrap_git.go
This change will allow the end-user to bootstrap with HTTP git URLs
But the user must explicitly set --allow-insecure-http=true
Fix: https://github.com/fluxcd/flux2/issues/2786
=> Add `--allow-insecure-http` to `bootstrap git`

internal/build/build.go, internal/build/build_test.go, internal/build/testdata/local-kustomization/different-name.yaml, internal/build/testdata/local-kustomization/multi-doc-valid.yaml, internal/build/testdata/local-kustomization/no-ns.yaml, internal/build/testdata/local-kustomization/valid.yaml
=> Handle multi-doc yaml for flux build

manifests/monitoring/loki-stack/kustomization.yaml, manifests/monitoring/loki-stack/release.yaml, manifests/monitoring/loki-stack/repository.yaml, manifests/monitoring/monitoring-config/dashboards/logs.json, manifests/monitoring/monitoring-config/kustomization.yaml
Changes:
- add `loki-stack` HelmRelease to install Loki and Promtail in the monitoring namespace
- set Loki data retention to 12h
- make the `loki-stack` HelmRelease depend on `kube-prometheus-stack` to install Loki's datasource and service monitors in the correct order
- add a Grafana dashboard for displaying and filtering the Flux controllers JSON logs
=> monitoring: Add Grafana Loki HR and Flux logs dashboard

rfcs/0002-helm-oci/README.md
Changes:
- Set status to partially implemented
- Add implementation history and TODOs
- Make corrections to the implementation details to match the reality
=> [RFC-0002] Update status and implementation history

cmd/flux/check.go
Changes to `flux check`:
- Verify that the Flux CRDs are correctly registered on the cluster and print their version
- Error out if no controllers or crds are found
Example output:
```console
$ flux check
✔ Kubernetes 1.23.5-gke.1501 >=1.20.6-0
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.22.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.23.2
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.19.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.26.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.24.0
✔ source-controller: deployment ready
► …
```
=> Add CRDs to `flux check` command

manifests/monitoring/monitoring-config/kustomization.yaml
Hi
The current monitoring-manifest namespace is set to flux-system namespace.
Grafana sidecar looks up for configmaps in the monitoring namespace.
[2022-06-22 14:55:35] Working on ADDED configmap monitoring/flux-grafana-dashboards-625985h2t7
[2022-06-22 14:55:35] Found 'data' on configmap
=> Put the dashboard configmap in the right namespace for monitoring

cmd/flux/logs.go
This sets the container to `manager` which is used by all Flux
controllers as the container name.
The other options I thought about were selecting the first, or doing
something with image detection. But both can be sensitive to either
users adding their patch as a first entry, or e.g. mirroring the image
to a different name.
Fixes #2843
=> logs: select manager container when multiple exist

cmd/flux/create_source_git.go
Without a reference specified, the create command will fail. 
Signed-off-by: David Harris <david.harris@weave.works>
Not tested given nature of the change.
=> Add the `--branch` arg to the basic auth example

rfcs/0003-kubernetes-oci/README.md, rfcs/kubernetes-oci/README.md
Proposal for adding OCI support for Kubernetes manifests to Flux.
Flux should be able to distribute and reconcile Kubernetes configuration packaged as OCI artifacts.
On the client-side, the Flux CLI should offer a command for packaging Kubernetes configs into an OCI artifact and pushing the artifact to a container registry using the Docker config file and the Docker credential helpers for authentication.
```sh
flux push artifact oci://ghcr.io/org/my-app-config:v1.0.0 --path ./deploy
```
On the server-side, the Flux source-controller should offer a dedicated API Kind for defining how OCI artifacts are pulled from container registries and how the artifact's authenticity can be verified. Flux source-controller should be able to work with any type of artifact even if it's not created with the …
=> [RFC-0003] Flux OCI support for Kubernetes manifests

cmd/flux/create_secret_oci.go, cmd/flux/create_secret_oci_test.go, cmd/flux/testdata/create_secret/oci/create-secret.yaml, pkg/manifestgen/sourcesecret/options.go, pkg/manifestgen/sourcesecret/sourcesecret.go
=> Add `create secret oci` command

.github/aur/flux-bin/.SRCINFO.template
Upon noticing pkgrel = 2 of pkgver = 0.31.4 has [broken SHAs](https://aur.archlinux.org/cgit/aur.git/commit/?h=flux-bin&id=aca324e1cbc673bb6921ffc9ec3072bb8ce08766) for amd64, I also noticed the templates appear to need release URLs updating.
=> SRCINFO: fix path

.github/aur/flux-bin/.SRCINFO.template
Otherwise it breaks the AUR, as apparent in https://aur.archlinux.org/packages/flux-bin.
Follow up on #2917
=> AUR: ensure `pkgname` is bottom entry in .SRCINFO

rfcs/0003-kubernetes-oci/README.md
Amend the RFC to add a field for enabling OIDC auth for AWS, Azure and Google Cloud. The `provider` field mirrors the Bucket API.
=> [RFC-0003] Add the provider field for OIDC auth

cmd/flux/pull_artifact.go
Fixup docs string to match pull command - this one is for Pull artifact, but it says Push
=> Docs: correct "pull" in pull artifact docs

cmd/flux/testdata/trace/helmrelease-oci.golden, cmd/flux/testdata/trace/helmrelease-oci.yaml, cmd/flux/testdata/trace/helmrelease.golden, cmd/flux/trace.go, cmd/flux/trace_test.go
* Added support for OCIRepositories to `flux trace`
* Changed indentation to compensate new, longer field name "Source
Revision"
* Added unit tests for the new output
Example output:
```sh
$ ./bin/flux trace -n default deploy podinfo
Object:          Deployment/podinfo
Namespace:       default
Status:          Managed by Flux
---
Kustomization:   podinfo
Namespace:       flux-system
Target:          default
Path:            ./kustomize
Revision:        dbdb109711ffb3be77504d2670dbe13c24dd63d8d7f1fb489d350e5bfe930dd3
Status:          Last reconciled at 2022-08-10 14:40:28 +0200 CEST
Message:         Applied revision: dbdb109711ffb3be77504d2670dbe13c24dd63d8d7f1fb489d350e5bfe930dd3
---
OCIRepository:   podinfo
Namespace:       flux-system
URL: …
```
=> Make `flux trace` work with OCIRepository

rfcs/0003-kubernetes-oci/README.md
This PR adds an optional field to the `OCIRepository` spec for specifying a media type of the OCI artifact layer which contains the Kubernetes configs. This field is meant to make Flux more flexible when dealing with multi-layer artifacts created by other tools than the Flux CLI.
=> [RFC-0003] Select layer by OCI media type

cmd/flux/get.go
Before 
```
➜  flux get ks me
✗ no Kustomization objects found in flux-system namespace # misleading as there are Kustomizations in the flux-system namespace
```
Now:
```
➜  ./bin/flux get ks me
✗ Kustomization object 'me' not found in `flux-system` namespace
```
=> Improve error message in get cmd

rfcs/0002-helm-oci/README.md
Add basic auth and contextual login for AWS, Azure, GCP to the Helm OCI RFC.
=> [RFC-0002] Add auth specification for Helm OCI

cmd/flux/docgen.go
This MR closes https://github.com/fluxcd/flux2/issues/2203
As described in the original issue, the fix to disable the source page related links is pretty simple by adding `importedDoc: true` within the header.
It took me a while to realise where this was exactly needed, I was unable to find documentation about that option and another while to test that the change was good.
I did checkout https://github.com/fluxcd/website then I ran
```shell
$ make serve
```
Which generated the site and served it on http://localhost:1313 then navigated to http://localhost:1313/docs/cmd/flux/ and observed the "Edit this page" along with the other source page links.
After that edited `content/en/docs/cmd/flux.md` by adding `importedDoc: true` under title.
```markdown
---
title: "flux"
importedDoc: true
--- …
```
=> Fix broken "edit this page" links in Flux CLI section

rfcs/0002-helm-oci/README.md, rfcs/0003-kubernetes-oci/README.md
Update RFCs for Flux v0.33.0 release.
=> Status update for RFC-0002 and RFC-0003

manifests/monitoring/monitoring-config/podmonitor.yaml
Prometheus job generated by the PodMonitor does not exclude non-running pods. All the "completed" Pods are still going to be  listed as targets in Prometheus and marked as down. This issue is related to PodMonitor implementation and is discussed in prometheus-operator/prometheus-operator#4816
Signed-off-by: Arcadie Condrat <arcadie.condrat@gmail.com>
=> Filter out non-running pods in Prometheus

cmd/flux/docgen.go
Reverts fluxcd/flux2#3034
Once we merge https://github.com/fluxcd/website/pull/1114 we won't need the change below any more.
=> Revert "Fix broken "edit this page" links in Flux CLI section"

cmd/flux/uninstall.go
Fix `flux uninstall` when using OCIRepositories, currently the Source CRDs and namespace can't be terminated.
=> Remove finalizers for OCI repositories on uninstall

.github/workflows/release-manifests.yml
Add CI workflow to build and push the [install manifests](https://github.com/fluxcd/flux2/tree/main/manifests/install) as OCI artifacts to:
- `ghcr.io/fluxcd/flux-manifests`
- `docker.io/fluxcd/flux-manifests`
The manifests pushed to GHCR have the container images set to `image: ghcr.io/fluxcd/<controller-name>:<controller-version>` while the manifests pushed to DockerHub have the controller images set to `image: docker.io/fluxcd/<controller-name>:<controller-version>`.
The OCI artifacts are signed with Cosign and GitHub OIDC (keyless).
=> Publish the install manifests to GHCR and DockerHub as OCI artifacts

cmd/flux/uninstall.go
Depends on [notification-controller#416](https://github.com/fluxcd/notification-controller/pull/416).
=> Remove finalizers for notification controllers

internal/bootstrap/bootstrap_provider.go
=> [bootstrap] Make sure we reconcile with the right reconciliation method

.github/workflows/scan.yaml, cmd/flux/list_artifact.go, cmd/flux/pull_artifact.go, cmd/flux/push_artifact.go, cmd/flux/tag_artifact.go, go.mod, go.sum, internal/flags/source_oci_provider.go
I've noticed during CI, that the current command already expected a configured Docker client to push artifacts to authenticated registries.
Some users might not want to have the Docker client in their process (like a CI job) or build a handcrafted config.json file.
This MR adds `--creds` and `--provider` to the `push artifact` command.
`--creds` can accept either a token that will be used with the `Bearer` keyword, or a username & password which will be used for Basic authentication.
`--provider` will run the provider login logic.
This would allow this kind of behavior:
```
flux push artifact oci://my-registry.dev/foo:v1 \
--source xxx \
--revision xxx \
--path . \
--creds $TOKEN # Authenticate via "Bearer $TOKEN" Authorization header
```
Or via provider:
```
flux push artifact …
```
=> Support autologin when pushing OCI artifacts

manifests/bases/helm-controller/kustomization.yaml, manifests/bases/helm-controller/labels.yaml, manifests/bases/image-automation-controller/kustomization.yaml, manifests/bases/image-automation-controller/labels.yaml, manifests/bases/image-reflector-controller/kustomization.yaml, manifests/bases/image-reflector-controller/labels.yaml, manifests/bases/kustomize-controller/kustomization.yaml, manifests/bases/kustomize-controller/labels.yaml, manifests/bases/notification-controller/kustomization.yaml, manifests/bases/notification-controller/labels.yaml, manifests/bases/source-controller/kustomization.yaml, manifests/bases/source-controller/labels.yaml
Label each controller deployment, service, service account and CRDs with `app.kubernetes.io/component: <controller-name>`.
Ref: https://github.com/fluxcd/flux2/discussions/3100
=> Add component label for controllers and their CRDs

cmd/flux/bootstrap_git.go
Fixes #3116.
If you're using an HTTP-based Git server with Flux, you need to provide `--token-auth` to avoid triggering an SSH host key check (see [#2825](https://github.com/fluxcd/flux2/issues/2825#issuecomment-1151355914)). Unfortunately, doing this forces the URL in the `GitRepository` resource created during bootstrapping to always use `https`. This will cause Kustomization reconcile errors for servers that do not have HTTPS enabled or do not have the appropriate certs installed or available.
This pull request fixes this by keeping the repository URL scheme intact when using `--token-auth`.
Signed-off-by: Carlos Nunez <75340335+carlosonunez-vmw@users.noreply.github.com>
=> Maintain original scheme when using --token-auth

.github/workflows/bootstrap.yaml, .github/workflows/e2e-arm64.yaml, .github/workflows/e2e-azure.yaml, .github/workflows/e2e.yaml, .github/workflows/release.yaml, .github/workflows/scan.yaml, .github/workflows/update.yaml, CONTRIBUTING.md, Makefile, cmd/flux/create.go, cmd/flux/get.go
Changes:
- Update Go to 1.19 in CI
- Update Kubernetes to 1.25.2 in bootstrap e2e test
=> Build with Go 1.19

manifests/monitoring/monitoring-config/dashboards/control-plane.json
This PR could close [#3086](https://github.com/fluxcd/flux2/issues/3086#issue-1366306801)
Updating current metric of type `go_memstats_alloc_bytes_total` with `container_memory_working_set_bytes` to correctly report memory consumption.
=> [Grafana] Use `container_memory_working_set_bytes` to report memory consumption

rfcs/0003-kubernetes-oci/README.md
After 6 months, Flux OCI support for Kubernetes manifests has been fully implemented 🎉
=> Update RFC-0003 implementation history

pkg/log/nop.go
This change adds a discard implementation of the logger interface which is useful for testing purposes.
=> Add nop logger

.github/workflows/bootstrap.yaml, .github/workflows/scan.yaml
Dependabot doesn't have access to GitHub secrets, so as with PRs from forks, we need to skip those workflows which require secrets.
=> Only run e2e tests for Dependabot PRs

rfcs/0004-insecure-http/README.md
Proposal for blocking HTTP connections across all Flux controllers and objects
TLDR:
* A new boolean flag `--insecure-allow-http` shall be added to all controllers, which would be used to allow/disallow HTTP connections at the controller level. The default value is `true`, which _allows_ HTTP connections
* A new boolean field `.spec.insecure` shall be added to all relevant objects where the specified endpoint doesn't allow for inference of the transport type through the scheme and HTTP connections must be used.
* A new boolean flag `--insecure` shall be added to relevant CLI commands, to configure the value of `.spec.insecure` in the related object definition.
Sponsored by @pjbgf 
Fixes #3076
=> RFC-0004: Block insecure HTTP connections across Flux

.github/runners/README.md, .github/runners/prereq.sh, .github/runners/runner-setup.sh, .github/workflows/e2e-arm64.yaml
Changes:
- Migrate the GitHub runners to Equinix c3.large.arm64 instances
- Run the test suite on all supported Kubernetes versions
- Add multi-tenancy smoke test
=> Refactor ARM64 e2e test suite

cmd/flux/bootstrap_bitbucket_server.go, cmd/flux/bootstrap_git.go, cmd/flux/bootstrap_github.go, cmd/flux/bootstrap_gitlab.go, cmd/flux/create_secret_git.go, cmd/flux/create_secret_helm.go, cmd/flux/create_secret_tls.go, cmd/flux/create_source_git.go, cmd/flux/create_source_helm.go, pkg/bootstrap/bootstrap_plain_git.go, pkg/bootstrap/git/commit_options.go, pkg/bootstrap/git/gogit/gogit.go, pkg/bootstrap/git/gogit/gogit_test.go, pkg/bootstrap/options.go, pkg/manifestgen/sourcesecret/options.go, pkg/manifestgen/sourcesecret/sourcesecret.go, pkg/manifestgen/sourcesecret/sourcesecret_test.go
This change moves all file reading for certificates and PGP from code located in pkg to the CLI command. The purpose for this is to make sharing the code easier where the content is not expected to be in files.
=> Remove file reading from bootstrap package

.github/workflows/e2e-arm64.yaml, manifests/monitoring/kube-prometheus-stack/release.yaml, manifests/monitoring/kube-prometheus-stack/repository.yaml
Changes:
- Switch the  prometheus-community HelmRepository to OCI
- Bump the kube-prometheus-stack version to latest v41
- Enable keyless cosign verification in the  kube-prometheus-stack HelmRelease
- Add the monitoring stack to the ARM64 e2e tests
=> monitoring: Use kube-prometheus-stack signed OCI Helm chart

Dockerfile
Changes:
- Remove nsswitch.conf creation as it's now included in [Alpine 3.16](https://git.alpinelinux.org/aports/commit/?id=348653a9ba0701e8e968b3344e72313a9ef334e4)
- Update kubectl version to 1.25.4
=> Update kubectl and remove nsswitch.conf in flux-cli image

rfcs/0005-artifact-revision-and-digest/README.md, rfcs/XXXX-artifact-revision-format/README.md
This RFC proposes to establish a canonical `Revision` format for an `Artifact`
which points to a specific revision represented as a checksum (e.g. an OCI
manifest digest or Git commit SHA) of a named pointer (e.g. an OCI image tag or
Git tag). In addition, it proposes to include the algorithm name (e.g.
`sha256`) as a prefix to an advertised checksum for an `Artifact` and
further referring to it as a `Digest`, deprecating the `Checksum` field.
- https://github.com/fluxcd/source-controller/issues/855
- https://github.com/fluxcd/source-controller/pull/925#issuecomment-1285491112
=> RFC-0005: Artifact `Revision` format and introduction of `Digest`

.github/dependabot.yml, .github/workflows/e2e-arm64.yaml, .github/workflows/e2e-azure.yaml, .github/workflows/e2e-bootstrap.yaml, .github/workflows/e2e.yaml, .github/workflows/release.yaml, .github/workflows/scan.yaml, .github/workflows/update.yaml
The main benefit of pinning GitHub actions is the determinism it brings in terms of what version of a given action will be executed. This is a step towards having hermetic builds.
Once pinned to a commit, Dependabot will automatically issue PRs to update to newer versions. For the time being this will happen every Monday.
Pinned versions is the only security metric from OpenSSF scorecard that this repository currently have a zero score.
---
This PR focus on external actions. Flux actions that live in `pkg/actions` will be dealt with separately.
=> build: Pin GitHub Actions

go.mod, internal/build/diff.go, pkg/uninstall/uninstall.go
Adds an error return value to the uninstall functions. The cli ignores the returned error as it relies on the error message being logged to the user. It is however useful for other programs which want the actual returned error.
=> Aggregate errors in uninstall functions

manifests/install/kustomization.yaml
Use GHCR as the default container registry for all controllers
=> Set notification-controller container image to GHCR

go.mod, go.sum
fixes #3391 
This fixes the issue where only .yaml was accepted by `flux build/diff` for a kustomization file extension.
It also adds support for kustomize componenents.
=> Update fluxcd/pkg/kustomize dependency

cmd/flux/build_kustomization.go, cmd/flux/testdata/build-kustomization/delete-service/hpa.yaml, cmd/flux/testdata/build-kustomization/podinfo-result.yaml, cmd/flux/testdata/build-kustomization/podinfo-without-service-result.yaml, cmd/flux/testdata/build-kustomization/podinfo/hpa.yaml, internal/build/build.go
fixes #3411 
If this is implemented, it will not assume that access to a `kubeconfig` is guaranteed even if just for retrieving configured namespace.
=> Fix dry-run still loading kubeconfig issue

.github/workflows/release.yaml
Dependabot should stick to tagged versions if the existing hash relates to the tag made in the comment.
Reverts https://github.com/fluxcd/flux2/pull/3394.
=> build: Revert sigstore/cosign-installer to v2.8.1

cmd/flux/build_artifact.go, cmd/flux/build_artifact_test.go, cmd/flux/push_artifact.go
Fixes bug introduced by https://github.com/fluxcd/flux2/pull/3389 where the path for the build cmd was used in the error message.
Also moves code for saving stdin to file before check for path
=> Fix path on `flux push`

cmd/flux/check.go
After a CRD version upgrade, Kubernetes keeps the old version in the `crd.Status.StoredVersions` so we need to display the last entry in the array otherwise the `flux check` command confuses users by showing the oldest version.
Ref: https://github.com/fluxcd/notification-controller/pull/455#issuecomment-1363667686
=> check: Show the latest stored version of CRDs

install/README.md, install/flux.sh
I use the install script in our ci pipeline which happen to be executed quite frequently. 
We started to run into gh ratelimiting because of this script.
```
Run curl -s https://raw.githubusercontent.com/fluxcd/flux2/main/install/flux.sh | sudo bash
[INFO]  Downloading metadata https://api.github.com/repos/fluxcd/flux2/releases/latest
Error: Process completed with exit code 22.
```
This fix adds support for $GITHUB_TOKEN. If its not set it would just be an anonymous request as it was before.
=> fix(install-script): support $GITHUB_TOKEN

action/README.md, action/action.yml
Hello, the PR in #3474 is still blocked
I'm going to rebase and squash, but here's a reference to the original commit I made which adds just one change to the existing PR is:
* fac19820
to make the review easier, you might want to check that one first.
* c7a48769
* is 15385220 rebased against the current main branch without any other changes
I noticed that this doesn't only affect flux update job which runs hourly, but can even impact GitHub actions jobs that embed the "install flux" action inline!
Trying to get this unblocked, I've added the one suggestion from https://github.com/fluxcd/flux2/pull/3474#discussion_r1067178730 rebased and resubmitted this PR so that it can merge.
I'm going to go ahead and pre-emptively squash all the commits, as well, to simplify the merge.
Fix: …
=> Add GITHUB_TOKEN  to Flux GitHub Action

action/action.yml
Fix #3509 
I have a tester pointed at my local version to be extra sure, sorry there is one more error in that script which we did not see because we were not expecting the context as `set -e` (which I guess all github runners are, and that makes sense.)
Adding quotes here in the original version of this script, when the `TOKEN` variable is empty you get:
```
curl https://api.github.com/repos/fluxcd/flux2/releases/latest -sL ''
```
(ref:
https://github.com/kingdonb/bootstrap-repo/actions/runs/3991169408/jobs/6845685491#step:3:31 )
That does curl twice, once for the URL provided and again for the empty string, which results in curl returning error code 3 "malformed URL" which results in the script aborting, again whenever the user fails to provide a `token`.
The script should mostly work …
=> Fix fluxcd/flux2/action (finally)

action/action.yml
Add an "else" branch
(https://github.com/fluxcd/flux2/pull/3511 failed to fix #3509)
I'll be testing this version both with the TOKEN set and without TOKEN
I added a note in comment for anyone that encounters the rate limiting behavior, looking for a back-reference to the discussion on how it's solved and why this is necessary. Maybe this is not necessary here?
I'm going to test a few different versions because the first version I came up with here is objectively terrible, we should be able to set the output of an IF statement to a variable, or something slightly more elegant than what I've done here, (which is just copy the whole chain of pipes and repeat it twice.)
=> Fix fluxcd/flux2/action

action/action.yml
A bug was introduced in https://github.com/fluxcd/flux2/commit/ed13067ff2ecbc427f83b969503ad676060448d1, when trying to solve this issue: https://github.com/fluxcd/flux2/issues/3509.
If `VERSION` is provided, `VERSION_SLUG` will never be set and `VERSION` will be overwritten with a bad value.
=> Fix broken GitHub Action and handle case where VERSION is provided as an input

.github/workflows/e2e-bootstrap.yaml, .github/workflows/e2e.yaml, Dockerfile
This PR updates Alpine and kubectl in the flux-cli Dockefile. In addition it replaces the `engineerd/setup-kind` GH Action with `helm/kind-action` in CI, ref: https://github.com/fluxcd/flux2/issues/3399.
=> Update Alpine to v3.17 and kubectl to v1.26.1 in flux-cli image

cmd/flux/get.go
Before:
```
$ flux get source git -A
✗ no GitRepository objects found in flux-system namespace
```
After:
```
$ flux get source git -A
✗ no GitRepository objects found in any namespace
```
closes #3530
=> fix misleading messaging when using `-A` flag

manifests/monitoring/kube-prometheus-stack/release.yaml, manifests/monitoring/kube-prometheus-stack/repository.yaml
This PR updates the `HelmRepository` to use the official non-OCI repository. We also disable chart verification for the "kube-prometheus-stack" `HelmChart` since it requires an OCI repository.
The "prometheus-community" developers have disabled OCI builds for now (see https://github.com/prometheus-community/helm-charts/pull/2841).
=> Update prometheus-community helm repo due to the suspension of OCI builds

action/README.md, cmd/flux/push_artifact.go
This PR enables extracting the OCI artifact image name and digest from the `flux push artifact` output in CI.
Example output:
```console
$ .flux push artifact oci://localhost:5050/my-app-config:v1.0.0 --source=local --revision=local --path ./manifests/ -ojson
{
"url": "oci://localhost:5050/my-app-config@sha256:ccbcfcf35161d3b8127a9658c0dcda9a69ec099d22031269930b4e0e3038779c",
"repository": "localhost:5050/my-app-config",
"tag": "v1.0.0",
"digest": "sha256:ccbcfcf35161d3b8127a9658c0dcda9a69ec099d22031269930b4e0e3038779c"
}
```
Example of signing the pushed artifact with cosign:
```sh
digest_url = $(flux push artifact  \
oci://ghcr.io/org/config/app:$(git rev-parse --short HEAD) \
--source="$(git config --get remote.origin.url)" \
--revision="$(git branch --show-current)/$(git rev-parse …
```
=> Add json/yaml output to flux push artifact

cmd/flux/tree_kustomization.go, internal/utils/objectutil.go, internal/utils/utils.go
Fix: https://github.com/fluxcd/flux2/issues/2149
Before:
```console
$ flux tree ks apps-sync
Kustomization/flux-system/apps-sync
├── Namespace/apps
├── HelmRelease/apps/podinfo
│   ├── Service/podinfo
│   ├── Deployment/podinfo
│   └── HorizontalPodAutoscaler/podinfo
├── Ingress/apps/podinfo
└── HelmRepository/apps/podinfo
```
After:
```console
$ flux tree ks apps-sync
Kustomization/flux-system/apps-sync
├── Namespace/apps
├── HelmRelease/apps/podinfo
│   ├── Service/apps/podinfo
│   ├── Deployment/apps/podinfo
│   └── HorizontalPodAutoscaler/apps/podinfo
├── Ingress/apps/podinfo
└── HelmRepository/apps/podinfo
```
=> flux tree: Add namespaces to objects reconciled from HRs

cmd/flux/tree_kustomization.go
Followup: https://github.com/fluxcd/helm-controller/pull/596
=> flux tree: Track CRDs managed by HelmReleases

cmd/flux/tree_kustomization.go
Listing CRDs does not set the GroupKind so we need to manually set it. 
Followup: https://github.com/fluxcd/flux2/pull/3549
=> flux tree: Set CRDs GroupKind in output

rfcs/0003-kubernetes-oci/README.md
Given that DockerHub and all the other popular registries now support custom media type, I propose that we use `application/vnd.cncf.flux` for the artifacts created with `flux push`. This change doesn't affect Flux source-controller, the controller will still work with any type of OCI artifact as long as it contains a `tar+gzip` layer.
Instead of using the Docker distribution media types, we'll be using:
- artifact media type `application/vnd.oci.image.manifest.v1+json`
- config media type `application/vnd.cncf.flux.config.v1+json`
- content media type `application/vnd.cncf.flux.content.v1.tar+gzip`
=> RFC-0003: Introduce Flux OCI media type

cmd/flux/build_artifact_test.go, cmd/flux/build_kustomization_test.go, cmd/flux/diff_kustomization_test.go, cmd/flux/export_test.go, cmd/flux/helmrelease_test.go, cmd/flux/image_test.go, cmd/flux/install_test.go, cmd/flux/kustomization_test.go, cmd/flux/main_e2e_test.go, cmd/flux/source_oci_test.go, internal/utils/utils_test.go
As otherwise the `.golden` values can not be automatically updated using
`-update` as documented in `CONTRIBUTING.md`.
Also ensure we do not use `defer` but rather `t.Cleanup` in tests, as
this will always be called even if e.g. `t.Fatal` abruptly stops the
test.
Also fixed some other minor things I ran into, and filled issues for the
things that are beyond reach of time I have available.
=> tests: only provide template values when used

manifests/bases/helm-controller/kustomization.yaml, manifests/bases/image-automation-controller/kustomization.yaml, manifests/bases/image-reflector-controller/kustomization.yaml, manifests/bases/kustomize-controller/kustomization.yaml, manifests/bases/notification-controller/kustomization.yaml, manifests/bases/source-controller/kustomization.yaml, manifests/rbac/edit.yaml, manifests/rbac/kustomization.yaml, manifests/rbac/view.yaml
This PR adds two cluster roles which grant the Kubernetes `view`, `edit` and `admin` roles access to Flux custom resources. 
Fix: https://github.com/fluxcd/flux2/issues/2409
Fix: #3572
Ref: https://github.com/fluxcd/kustomize-controller/issues/762
=> rbac: Add view and edit aggregated cluster roles

.github/workflows/scan.yaml
Fixing the Snyk build errors by installing Go and downloading the Go modules before scanning.
```
go: downloading github.com/moby/spdystream v0.2.0
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
```
=> ci: Fix Snyk Go build VCS stamping error

cmd/flux/stats.go
```console
$ flux stats -n A
RECONCILERS             RUNNING FAILING SUSPENDED       STORAGE   
GitRepository           2       0       0               105.1 MiB       
OCIRepository           6       1       0               55.8 KiB        
HelmRepository          6       0       0               249.5 KiB       
HelmChart               6       0       0               538.6 KiB       
Bucket                  1       0       1               37.3 KiB        
Kustomization           6       0       0               -               
HelmRelease             6       0       0               -               
Alert                   0       0       0               -               
Provider                0       0       0               -               
Receiver                1       1       0 …
```
=> Add command to print the reconcilers status

rfcs/0003-kubernetes-oci/README.md, rfcs/0005-artifact-revision-and-digest/README.md
Changes:
- Mark RFC-0005 as implemented and add implementation history
- Add custom OCI media types to implementation history of RFC-0003
=> Update implementation history of RFC-0003 and RFC-0005

cmd/flux/events.go, cmd/flux/events_test.go, go.mod, go.sum
This pull request closes #3618 
```
$ flux events
LAST SEEN               TYPE    REASON                  OBJECT                          MESSAGE                                                                                                       
60m                     Normal  ReconciliationSucceeded Kustomization/flux-system       Reconciliation finished in 1.51342644s, next run in 10m0s                                                    
53m (x20 over 19h)      Normal  ArtifactUpToDate        HelmChart/flux-system-ww-gitops artifact up-to-date with remote revision: '4.0.14'                                                           
50m                     Normal  ReconciliationSucceeded Kustomization/flux-system       Reconciliation finished in 1.568797687s, next run in 10m0s …
```
=> Add `flux events` command 

manifests/monitoring/kube-prometheus-stack/release.yaml
Changes to the kube-prometheus-stack HelmRelease:
- update the chart to v45.x
- Disable [Flux drift detection](https://fluxcd.io/flux/cheatsheets/bootstrap/#enable-helm-drift-detection) for webhooks and rules
=> Disable drift detection for kube-prometheus-stack webhooks

.github/workflows/e2e-arm64.yaml, .github/workflows/e2e-azure.yaml, .github/workflows/e2e-bootstrap.yaml, .github/workflows/e2e.yaml, .github/workflows/release.yaml, .github/workflows/scan.yaml, .github/workflows/update.yaml
- Update `actions/setup-go` to v4.0.0 in workflows.
- Remove separate caching steps in favor of built-in caching feature in action (since >=v3.0.0).
Replaces #3702 #3705
=> build: update `actions/setup-go` in workflows

cmd/flux/bootstrap_gitlab.go, go.mod, go.sum, pkg/bootstrap/bootstrap_provider.go
This change set implements support for the `--deploy-token-auth` option in the `flux bootstrap gitlab` command.
That option will reconcile a GitLab Project Deploy Token to use for the authentication of the GitLab git repository.
A GitLab Project Deploy Token can be used the same way as a Personal Access Token which is already supported via `--token-auth`. The difference with the GitLab Project Deploy Token is that the token is managed (created, updated, deleted) by Flux and not provided by the user.
This change is transparent to the source-controller.
A prerequisite for this change is the
`fluxcd/go-git-providers` change here:
* https://github.com/fluxcd/go-git-providers/pull/191
See related discussion here: https://github.com/fluxcd/flux2/discussions/3595
GitLab Issue here: …
=> Implement `--deploy-token-auth` in GitLab bootstrapping

cmd/flux/export.go, cmd/flux/testdata/create_source_git/export.golden, cmd/flux/testdata/create_source_helm/https.golden, cmd/flux/testdata/create_source_helm/oci-with-secret.golden, cmd/flux/testdata/create_source_helm/oci.golden, cmd/flux/testdata/export/alert.yaml, cmd/flux/testdata/export/bucket.yaml, cmd/flux/testdata/export/git-repo.yaml, cmd/flux/testdata/export/helm-release.yaml, cmd/flux/testdata/export/helm-repo.yaml, cmd/flux/testdata/export/image-policy.yaml, cmd/flux/testdata/export/image-repo.yaml, cmd/flux/testdata/export/image-update.yaml, cmd/flux/testdata/export/ks.yaml, cmd/flux/testdata/export/provider.yaml, cmd/flux/testdata/export/receiver.yaml, cmd/flux/testdata/oci/export.golden, cmd/flux/testdata/oci/export_with_secret.golden
Closes #3593 
Following Hidde's hint, the change in this PR should prevent extra newlines from being printed. This affects both the `flux export ..` command and the `--export` flag used in other Flux commands.
Also tested with
```
flux export .. >> export.yaml
flux export .. >> export.yaml
```
and it no longer produces a newline between resources in the same file.
=> fix: Avoid printing an extra newline when exporting resources

cmd/flux/build_kustomization.go, cmd/flux/build_kustomization_test.go, cmd/flux/diff_kustomization.go, cmd/flux/testdata/build-kustomization/ignore/.sourceignore, cmd/flux/testdata/build-kustomization/ignore/configmap.yaml, cmd/flux/testdata/build-kustomization/ignore/not_deployable/ignore_svc.yaml, cmd/flux/testdata/build-kustomization/ignore/secret.yaml, cmd/flux/testdata/build-kustomization/podinfo-with-ignore-result.yaml, go.mod, go.sum, internal/build/build.go
If implemented, users will be able to ignore files when using `build kustomization` and `diff kustomization` using `.sourceignore` and `ignore-paths` flag.
`ignore-paths` accepts a comma separated list of entries that follow the .gitignore pattern format.
Fix: #3760
=> Add the possibility to ignore files with build and diff Kustomization

cmd/flux/get.go, cmd/flux/get_test.go, cmd/flux/testdata/get/get.golden, cmd/flux/testdata/get/get_label_one.golden, cmd/flux/testdata/get/get_label_two.golden, cmd/flux/testdata/get/objects.yaml
This pull request adds a label selector flag to `get` command to enable users filter objects by label
e.g
```
flux get sources git -l sharding.fluxcd.io/key=shard1
```
=> Add label selector flag to get cmd

.github/aur/flux-bin/.SRCINFO.template, .github/aur/flux-bin/PKGBUILD.template, .github/aur/flux-bin/publish.sh, .github/aur/flux-go/.SRCINFO.template, .github/aur/flux-go/PKGBUILD.template, .github/aur/flux-go/publish.sh, .github/aur/flux-scm/PKGBUILD.template, .github/aur/flux-scm/publish.sh
=> Fix publishing pre-release versions to AUR

cmd/flux/pull_artifact.go
- When there's an error stat'ing the output directory flux now prints
the error:
Before:
```
✗ invalid output path ./ro-dir/foo
```
After:
```
✗ invalid output path "./ro-dir/foo": stat ./ro-dir/foo: permission denied
```
- When no output directory is provided flux now explicitly says so in
the error:
Before:
```
✗ invalid output path
```
After:
```
✗ output path cannot be empty
```
=> better messaging for `pull artifact` command

manifests/monitoring/loki-stack/release.yaml
The location of this URL was moved: https://github.com/grafana/helm-charts/blob/main/charts/loki/README.md
=> Outdated Loki Helm values URL

.github/workflows/e2e-arm64.yaml
Update the e2e test matrix to the latest supported Kubernetes versions.
=> Run conformance tests for Kubernetes 1.27

tests/azure/azure_test.go
This updates the Azure alert testing to add a summary which should be sent to Azure as a commit-status genre.
=> e2e: Add summary to Azure Alert

manifests/rbac/kustomization.yaml, manifests/rbac/resourcequota.yaml
Added `ResourceQuota` for critical pods set to max 1K pods to allow horizontal scaling and sharding. 
Fixes insufficient quota error on GKE, reported [here](https://github.com/fluxcd/flux2/issues/3800#issuecomment-1544270865).
Tested on GKE 1.26
```console
$ flux check
✔ Kubernetes 1.26.2-gke.1000 >=1.20.6-0
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.32.2
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.0-rc.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0-rc.2
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.0-rc.2
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ …
```
=> Add ResourceQuota for critical pods

cmd/flux/reconcile_helmrelease.go, cmd/flux/reconcile_kustomization.go, cmd/flux/reconcile_source_chart.go, cmd/flux/reconcile_with_source.go, cmd/flux/testdata/helmrelease/reconcile_helmrelease_from_git.golden
Reconciling helm charts which are configured as semver are not reconciled via reconcile hr. 
This is because the HelmChart does not get annotated.
More details are found here:
* https://github.com/fluxcd/flux2/pull/3660
* https://github.com/fluxcd/flux2/issues/3656
This pr adds a new command `reconcile source chart` which also supports the --source flag for the referencing repository.
`reconcile hr --with-source` now supports annotating the entire source tree for a HelmRelease: Repository => Chart => Release.
This pr supersedes #3660.
Fixes #3656
=> feat: add reconcile source chart command

cmd/flux/create_helmrelease.go, cmd/flux/create_source_helm.go
Hello flux maintainers!
This PR fixes a few missing break lines in the create helmrelease and create source help documentation that could lead to some unintended executions if blindly copy-pasted 
For example, I've added `--export` to the `create source helm` OCI example included in the `flux create source helm --help` command:
Discovered this while I was pasting examples in my terminal with the `--export` flag to check if I was using the newest API versions for my flux objects
```
❯   flux create source helm podinfo \
--url=oci://ghcr.io/stefanprodan/charts/podinfo
--username=username \
--password=password --export
✚ generating HelmRepository source
► applying HelmRepository source
✔ source updated
◎ waiting for HelmRepository source reconciliation
^C
```
=> Fix break lines in create helmrelease and source

cmd/flux/main.go, go.mod
This is required because `controller-runtime` expects its consumers to set a logger through `log.SetLogger` within 30 seconds of the program's initalization. If not set, the entire debug stack is printed as an error. Ref: https://github.com/kubernetes-sigs/controller-runtime/blob/ed8be90/pkg/log/log.go#L59 Since we have our own logging and don't care about `controller-runtime`'s logger, we configure it's logger to do nothing.
Fixes: #3931
=> Set `controller-runtime` logger to a null logger

tests/azure/util_test.go
Checks and returns error if cloning Azure DevOps repository fails
=> Return clone error in Azure e2e tests

.github/workflows/e2e-azure.yaml
Run e2e Azure tests for PRs and commits to main if the `tests` directory
or the Azure workflow itself changes.
=> e2e: Run e2e Azure tests for PRs to main if tests or wofklow changes

tests/azure/azure_test.go, tests/azure/go.mod, tests/azure/util_test.go
This pull request sets the controller-runtime logger and checks for clone errors.
=> Set controller runtime logger in Azure e2e tests

cmd/flux/logs.go, cmd/flux/logs_e2e_test.go, cmd/flux/logs_unit_test.go, cmd/flux/main_test.go
**UX changes:**
- Only print an error when a pod doesn't have a matching container
instead of exiting early.
- Return a non-zero status code when no pod is found at all.
**Details:**
In certain situations there might be 3rd-party pods running in the
Flux namespace that cause the command to fail streaming logs, e.g.
when they have multiple containers but none of them is called
`manager` (which all Flux-maintained pods do). An example of such a
situation is when Flux is installed with the 3rd-party Flux extension
on AKS.
The `logs` command is now more forgiving and merely logs an error in
these situations instead of completely bailing out. It still returns a
non-zero exit code.
For the parallel log streaming with `-f` the code is now a little more
complex so that errors are now written to …
=> Make `flux logs` more lenient

cmd/flux/get.go, cmd/flux/get_image_all.go
Whenever an API type is not available then both, `flux get all` and `flux get image all` will just skip over that type instead of logging an error message.
Before:
```
$ flux get all
✗ failed to get API group resources: unable to retrieve the complete list of server APIs: source.toolkit.fluxcd.io/v1beta2: the server could not find the requested resource
[...]
✗ failed to get API group resources: unable to retrieve the complete list of server APIs: image.toolkit.fluxcd.io/v1beta2: the server could not find the requested resource
✗ failed to get API group resources: unable to retrieve the complete list of server APIs: image.toolkit.fluxcd.io/v1beta2: the server could not find the requested resource
[...]
$ echo $?
0
```
After:
```
$ flux get all
$ echo $?
0
```
closes #3973
=> Don't log errors with missing CRDs for "get * all" commands

.github/workflows/e2e-bootstrap.yaml, .github/workflows/release.yaml
Generate SLSA level 3 provenance attestations for the release assets and for the multi-arch container images.
Part of: https://github.com/fluxcd/flux2/issues/3994
=> Add SLSA3 generators to release workflow

.github/aur/flux-go/PKGBUILD.template, .github/aur/flux-scm/PKGBUILD.template, go.mod, tests/azure/go.mod
Part of: https://github.com/fluxcd/flux2/issues/4014
=> Align `go.mod` version with Kubernetes (Go 1.20)

cmd/flux/push_artifact.go
Remove the duplicate `:` from the OCI URL.
=> docs: Fix the `flux push` example for ECR

CONTRIBUTING.md, cmd/flux/check.go, cmd/flux/testdata/check/check_pre.golden
Bump the minimum supported version to Kubernetes 1.24.0 as 1.23/22 are now EOL https://endoflife.date/kubernetes
=> Set minimum supported version to Kubernetes 1.24.0

.github/dependabot.yml, .github/labels.yaml, .github/workflows/backport.yaml, .github/workflows/sync-labels.yaml
CI changes:
- Add backport workflow
- Add sync labels workflow
Part of: https://github.com/fluxcd/flux2/issues/4022
=> Add backport GitHub Action workflow

go.mod, go.sum, tests/azure/go.mod, tests/azure/go.sum
To improve support for Git >=v2.41.0.
=> Update go-git to unreleased v5.8.0

pkg/bootstrap/bootstrap_provider.go
=> Annotate errors from go-git-providers

.github/dependabot.yml, .github/workflows/backport.yaml, .github/workflows/e2e-arm64.yaml, .github/workflows/e2e-bootstrap.yaml, .github/workflows/e2e.yaml, .github/workflows/scan.yaml, .github/workflows/update.yaml
Changes:
- run backport under fluxcdbot account
- enable workflows for `release/**` branches
- group all GH action updates under the same PR
=> Run e2e tests on release branches

.github/workflows/e2e-arm64.yaml, .github/workflows/e2e-bootstrap.yaml, .github/workflows/e2e.yaml
CI changes:
- bump kind to v0.20.0
- bump Kubernetes to v1.27.3
- don't run e2e tests for docs changes
=> Run conformance tests for Kubernetes v1.27.3

.github/workflows/release.yaml
This ensures `jq` can properly parse the given `ARTIFACTS` JSON blob, as it contains escaped newlines in for example the Brew formula.
This should address the issue with the generation of SLSA metadata.
=> ci: release: disable interpretation backslash esc

.github/workflows/release.yaml
Backport of #4041 to `release/v2.0.x`.
=> [release/v2.0.x] ci: release: disable interpretation backslash esc

.github/workflows/backport.yaml
The backport workflow uses the default token to push the cherrypick branch so we need to give it write perms.
=> ci: backport: set write permissions

.github/workflows/release.yaml
Fix the generation of SLSA metadata for the flux-cli container image.
=> ci: release: extract the image tag from GITHUB_REF

.github/workflows/action.yaml, action/action.yml
Plus the verification of the SHA256 of the archive, as advertised in the checksum file published together with the release.
=> action: use `$RUNNER_TOOL_CACHE`, support MacOS and Windows, validate checksum

action/README.md
Update the Flux GitHub Action readme to point to https://fluxcd.io/flux/flux-gh-action/ for usage examples.
Followup #4051 and https://github.com/fluxcd/website/pull/1552
=> docs: Link to the Flux GitHub Action documentation

action/action.yml
To allow usage of action on GitHub Enterprise instances.
Fixes: #4060
=> action: re-allow configuration of non-default token

cmd/flux/build_kustomization_test.go, internal/build/build.go, internal/build/build_test.go, internal/build/diff.go
fix #3733
If implemented users will be able to use `flux diff ks --kustomization-file` while retrieving the inventory from the cluster to report stale objects. This implies that a local Flux Kustomization file takes precedence over it's live counterpart.
For `flux build ks --kustomization-file`, the cluster will be not queried when using `--dry-run`.
=> diff: Take into account the server-side inventory for local Flux Kustomizations

action/action.yml
As availability may be limited in some edge cases.
When a job is for example running within a container, `openssl` is not
always available. However, when running on a macOS or Windows runner,
the actual opposite is true.
=> action: support `openssl` and `sha256sum`

cmd/flux/check.go, cmd/flux/testdata/check/check_pre.golden
Drop support for Kubernetes 1.24 (EOL 28 Jul 2023)
Part of: #4125
=> Set Kubernetes min version to 1.25

cmd/flux/diff_kustomization_test.go, cmd/flux/testdata/diff-kustomization/flux-kustomization-multiobj.yaml, internal/build/build.go, internal/build/build_test.go, internal/build/testdata/local-kustomization/invalid-resource.yaml
Fixes https://github.com/fluxcd/flux2/issues/4132
=> Fix selection of kustomization resource from multi doc yaml

.github/workflows/e2e-azure.yaml
The Azure e2e tests are failing due to a missing subscription.
This pull request temporarily disables the tests until this is resolved.
=> Disable azure e2e test

.github/workflows/e2e-arm64.yaml, .github/workflows/e2e-bootstrap.yaml, .github/workflows/e2e.yaml
Run end-to-end tests for the following Kubernetes versions:
- v1.25.11
- v1.26.6
- v1.27.3
- v1.28.0
=> e2e: Add Kubernetes v1.28.0 to conformance tests

internal/flags/rsa_key_bits.go, internal/flags/rsa_key_bits_test.go
Don't generate RSA keys with a bit size less than 1024.
=> Set min value for the `--ssh-rsa-bits` flag

cmd/flux/version.go, cmd/flux/version_test.go
Take into account private registries and digest pinning when extracting the controller version from the container image.
Supersedes: #4076
=> Fix controller version info

manifests/monitoring/README.md
~:warning: Merge this just before the release of v2.1.0 after updating the release date in the first line of the README.~
Part of https://github.com/fluxcd/flux2/issues/4128.
=> Add monitoring configuration deprecation notice

README.md, action/README.md
=> Fix links to fluxcd.io

.github/aur/flux-go/.SRCINFO.template, .github/aur/flux-go/PKGBUILD.template, .github/aur/flux-scm/.SRCINFO.template, .github/aur/flux-scm/PKGBUILD.template
Relate #4224 #4228
- remove armv6h
=> chore: remove support armv6h for aur package

cmd/flux/main.go
The `--insecure-skip-tls-verify`, `--certificate-authority`, `client-key` and `client-certificate` are kubeconfig flags that are used when connecting to the Kubernetes API Server. The generic description sometimes makes users assume that this is for something else e.g [see comment](https://github.com/fluxcd/flux2/issues/4218#issuecomment-1711741628)
> Though I have the option --insecure-skip-tls-verify , still getting certifcate error.
This pull request updates the description to be clear about which server it is used for.
Before
```
--insecure-skip-tls-verify               If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure
--certificate-authority string           Path to a cert file for the certificate authority …
```
=> Update description of kubeconfig specific flag

internal/utils/apply.go
When using Apply with a set of files that end up with an empty first change set, wait will timeout waiting for nothing.
Only wait if the changeSet isn't empty.
=> fix: only wait for changeset if the result is not empty

cmd/flux/pull_artifact.go, go.mod, go.sum
Allow `flux pull artifact` to retrieve any kind of OCI artifact without an index, e.g. a Helm chart for debugging.
This is a follow-up to fluxcd/pkg#653
=> Make `flux pull` work for OCI artifacts produced by other tools

cmd/flux/bootstrap.go, cmd/flux/bootstrap_bitbucket_server.go, cmd/flux/bootstrap_git.go, cmd/flux/bootstrap_github.go, cmd/flux/bootstrap_gitlab.go, cmd/flux/cluster_info.go, cmd/flux/cluster_info_test.go, cmd/flux/install.go, cmd/flux/uninstall.go
This pull request prompts a user to confirm before overriding an existing Flux installation that's not managed by flux when running `install` or `bootstrap`.
The pull request also adds a better uninstallation prompt when flux is managed by some other tool.
Fixes: https://github.com/fluxcd/flux2/issues/4342
=> Confirm before overriding installation by another manager

cmd/flux/bootstrap_gitea.go, go.mod, go.sum, pkg/bootstrap/provider/factory.go, pkg/bootstrap/provider/provider.go
This PR implement `bootstrap gitea` command feature requested here: https://github.com/fluxcd/flux2/issues/4080
output: 
```
./bin/flux bootstrap gitea --owner Azhovan --repository test3       
► connecting to gitea.com
► cloning branch "main" from Git repository "https://gitea.com/Azhovan/test3.git"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ committed sync manifests to "main" ("a5860ca2f6919d98874461d97e6495f03e22b67e")
► pushing component manifests to "https://gitea.com/Azhovan/test3.git"
► installing components in "flux-system" namespace
✔ installed components
✔ reconciled components
► determining if source secret "flux-system/flux-system" exists
► generating source secret
✔ public key: ecdsa-sha2-nistp384 …
```
=> feat: add bootstrap gitea command

cmd/flux/events.go, cmd/flux/events_test.go
The `events` cmd didn't return data if the kind in the `--for` selector was lowercase. This pr fixes that. It also adds validation for the `--type` and `--for` flags.
Before 
```
➜  flux2 git:(flux-events) flux events --for alert/webapp    
✗ No events found in flux-system namespace.
```
Now
```
./bin/flux events --for alert/webapp
LAST SEEN               TYPE    REASON                          OBJECT          MESSAGE                                                                                                                                                 
3h53m                   Warning NotificationDispatchFailed      Alert/webapp    failed to send notification for HelmRepository/flux-system/podinfo: postMessage failed: failed to execute request: context deadline exceeded …
```
=> Make events cmd work well with lowercased and only kind selector

rfcs/0003-kubernetes-oci/README.md
Extend the  keyless verification specification to include OIDC identity matching.
- implemented in https://github.com/fluxcd/source-controller/pull/1250 
- scheduled for Flux 2.2.0 release
=> [RFC-0003] OIDC identity matching for keyless verification

cmd/flux/install.go, cmd/flux/install_test.go
This PR was implemented to address the issue reported by myself on #4403.
I made sure that it is working on the cases where there are only flag arguments, or no arguments.
I wanted to add a test for a successful run, but when I tried I actually got an "install failed" error. So I figured that maybe there was a reason why no successful tests were present.
I can add more tests, but I would need some guidance.
=> Fix flux install command so it returns an error when unexpected arguments are passed

cmd/flux/bootstrap_bitbucket_server.go, cmd/flux/bootstrap_gitlab.go
Fix minor typos in the flux bootstrap command documentation for Bitbucket Server and GitLab.
=> Fix typos in flux bootstrap documentation

Dockerfile
Bump Alpine to 3.19 and kubectl to 1.28.4 in the flux-cli Dockerfile
=> build: Update alpine and kubectl in flux-cli image

pkg/bootstrap/bootstrap_plain_git.go
=> Correct "sync" to "component" in log lines

.github/workflows/e2e-arm64.yaml, cmd/flux/check.go, cmd/flux/testdata/check/check_pre.golden
Remove 1.25 from test matrix and bump flux check to min 1.26.
=> Drop support for Kubernetes EOL versions

cmd/flux/get.go, cmd/flux/get_all.go, cmd/flux/get_source_all.go
This can happen when Custom Resource Definitions do not exist on the cluster. For example, because only a subset of the Flux controllers are installed on the cluster.
Previously, the detection was based on a combination of error type and string matching. However, a more reliable (and maintained) `apimeta.IsNoMatchError` checker is available upstream. Making it less likely this suddenly stops to matching properly when Kubernetes changes things.
Fixes #4474
=> Properly detect unsupported API errors

.github/workflows/e2e-arm64.yaml
Add Kubernetes 1.29 to the end-to-end testing matrix.
=> Run conformance tests for Kubernetes v1.29.0

cmd/flux/stats.go
flux cli does not properly detect unexpected argument on `flux stats` command.
=> `flux stats` should error on unrecognised args

cmd/flux/check.go
flux cli does not properly detect unexpected argument on `flux check` command.
=> `flux check` should error on unrecognised args

internal/build/build.go
Hi, I fixed typos I stumbled upon during code reading.
=> Fix typo in build.go

.github/runners/README.md, .github/runners/prereq.sh, .github/runners/runner-setup.sh
At Equinix suport team request, I have created new baremetal servers to host our GitHub runners. The new machines are using the latest Kubernetes Kind release and latest Docker engine. I have also created dedicated runners for the benchmark repo.
=> Update Equinix ARM64 GitHub runners

cmd/flux/bootstrap.go, cmd/flux/install.go
Fixes: https://github.com/fluxcd/flux2/issues/4630
Found a typo in the --force flag long description.
`diffrent` -> `different`
I first discovered them in the `flux bootstrap -h` section, but looks like it exists also for `install`.
=> Fix a typo in `--force` flag description

manifests/rbac/controller.yaml
As mentioned in the linked issue, all components use HEAD requests to /livez/ping to determine rate limits. This PR adds the required permissions to call the endpoint.
Fixes fluxcd/source-controller#1411
=> Add permissions required for flow control

Makefile
[This commit](https://github.com/kubernetes-sigs/controller-runtime/commit/4c2442e4d743d172a2e0126a841ecd274fffc228) causes failures to install envtest, see https://github.com/kubernetes-sigs/controller-runtime/issues/2720 for details.
This PR pins envtest to the latest version that still works.
=> Pin envtest version

.github/workflows/e2e-bootstrap.yaml, cmd/flux/bootstrap.go, cmd/flux/bootstrap_bitbucket_server.go, cmd/flux/bootstrap_git.go, cmd/flux/bootstrap_gitea.go, cmd/flux/bootstrap_github.go, cmd/flux/bootstrap_gitlab.go, cmd/flux/install.go, cmd/flux/install_test.go, pkg/bootstrap/bootstrap.go, pkg/bootstrap/bootstrap_plain_git.go, pkg/manifestgen/install/options.go, pkg/manifestgen/sourcesecret/sourcesecret.go
Add an optional flag called `--registry-creds` to the `flux bootstrap` and `flux install` commands for generating an image pull secret for container images stored in private registries.
TODO (after merge):
- Update the air-gapped installation guide https://fluxcd.io/flux/installation/configuration/air-gapped/
- Expose the new option in Flux Terraform provider https://github.com/fluxcd/terraform-provider-flux/blob/8733e7566bd505616fc9562988f7196607ade593/internal/provider/resource_bootstrap_git.go#L90
Closes: #4621
=> Add `--registry-creds` flag to bootstrap and install commands

manifests/bases/helm-controller/patch.yaml, manifests/bases/image-automation-controller/patch.yaml, manifests/bases/image-reflector-controller/patch.yaml, manifests/bases/kustomize-controller/patch.yaml, manifests/bases/notification-controller/patch.yaml, manifests/bases/source-controller/patch.yaml, manifests/install/kustomization.yaml
if applied, set `GOMAXPROCS` and `GOMEMLIMIT` for all controllers based on container resources which leads to reduce throttling and better performance.
ref: https://github.com/fluxcd/source-controller/pull/1443
ref: https://github.com/fluxcd/flux-benchmark/pull/5
=> Set `GOMAXPROCS` and `GOMEMLIMIT` to all Flux controllers

cmd/flux/bootstrap_git.go
This pull request introduces the capability to use Personal Access Tokens (PATs) as bearer tokens for authenticating Git operations in Oracle Visual Builder Studio (VBS). Oracle VBS requires that PATs be included in the Authorization header to secure Git operations. To facilitate this, a new flag, --with-bearer-token, has been added. When enabled, this flag treats the provided password as a bearer token, aligning with Oracle VBS's authentication requirements.
This change is crucial for developers leveraging Oracle VBS who need to integrate with Flux's automation capabilities in environments that mandate bearer token authentication. For detailed guidance on configuring PATs in Oracle VBS, please refer to the Oracle documentation: [Access a Git Repository Using Token-Based …
=> bootstrap: Add support for Git HTTP/S authorization header

cmd/flux/create_source_oci.go, cmd/flux/create_source_oci_test.go, cmd/flux/testdata/oci/export_with_complete_verification.golden, cmd/flux/testdata/oci/export_with_issuer.golden, cmd/flux/testdata/oci/export_with_subject.golden
This change introduces two new flags to `create source oci` for providing the values to the `OCIRepository.spec.verify.matchOIDCIdentity.(issuer,subject)` fields.
=> Add flags for issuer/subject OCI signature verification

cmd/flux/bootstrap.go, cmd/flux/bootstrap_git.go
Allow configuring the list of host key algorithms to use for SSH connections initialised by the CLI during bootstrap.
This allows using `flux bootstrap git` for Azure DevOps repos over SSH.
Refs:
- https://github.com/fluxcd/flux2/issues/4726
- https://github.com/fluxcd/terraform-provider-flux/issues/678
=> Add `--ssh-hostkey-algos` flag to bootstrap command

.github/kind/config.yaml, .github/workflows/e2e.yaml
Changes:
- Run e2e on large GH runners
- Use Kind images from [ghcr.io/fluxcd/kindest/node](https://github.com/fluxcd/flux-benchmark/pkgs/container/kindest%2Fnode)
- Use a 3 nodes kind cluster
- Update Calico to latest v3.27
- Add smoke tests for Flux events
=> Improve end-to-end test workflow

cmd/flux/create_source_chart.go, cmd/flux/create_source_chart_test.go, cmd/flux/delete_source_chart.go, cmd/flux/export_source_chart.go, cmd/flux/export_test.go, cmd/flux/testdata/create_source_chart/basic.yaml, cmd/flux/testdata/create_source_chart/setup-source.yaml, cmd/flux/testdata/create_source_chart/verify_basic.yaml, cmd/flux/testdata/create_source_chart/verify_complete.yaml, cmd/flux/testdata/export/helm-chart.yaml, cmd/flux/testdata/export/objects.yaml, internal/flags/local_helm_chart_source.go
The `create source chart` command supports all HelmChart.spec fields except `.valuesFiles` and `ignoreMissingValuesFiles` as these are assumingly rarely used fields and the CLI usually only supports commonly used ones.
closes #4760
=> Add `(create|delete|export) source chart` commands

.github/workflows/e2e-k3s.yaml
This PR adds end-to-end tests for bootstrapping Flux on k3s clusters (latest two minor versions corresponding to Kubernetes to 1.28 and 1.29).
Big thanks to @marccampbell and [Replicated](https://www.replicated.com/) for sponsoring the Flux project with on-demand k3s clusters 🤗 
Part of: https://github.com/fluxcd/flux2/issues/4712
=> Add k3s to the conformance test suite

tests/integration/suite_test.go, tests/integration/util_test.go
Run `flux check` after installation to show the relevant cluster and resource configurations in the environment.
```console
...
2024/05/10 14:43:02 Installing flux
2024/05/10 14:43:50 Running flux check
✔ Kubernetes 1.28.7-gke.1026000 >=1.26.0-0
► checking version in cluster
✔ distribution: flux-v0.0.0-dev.0
✔ bootstrapped: true
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.0.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.38.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.32.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.3.0
✔ notification-controller: deployment ready
► …
```
=> tests/integration: Run flux check after installation

Dockerfile, cmd/flux/check.go, cmd/flux/testdata/check/check_pre.golden
Changes:
- Update the Kubernetes version check and drop EOL versions
- Update kubectl to 1.30.0 in the flux-cli Dockerfile
Part of: #4712
=> Set Kubernetes 1.28 as min required version

cmd/flux/create_helmrelease.go, cmd/flux/create_helmrelease_test.go, cmd/flux/reconcile_helmrelease.go, cmd/flux/testdata/create_hr/basic.yaml, cmd/flux/testdata/create_hr/hc_basic.yaml, cmd/flux/testdata/create_hr/or_basic.yaml, cmd/flux/testdata/create_hr/setup-source.yaml
=> Add support for HelmRelease v2 in `flux reconcile` and `flux create`

.github/workflows/release.yaml, .goreleaser.yml
Deal with breaking changes in https://goreleaser.com/deprecations/?h=changelog#removed-in-v2
=> ci: Adapt config to GoRelease v2

manifests/bases/helm-controller/labels.yaml, manifests/bases/image-automation-controller/labels.yaml, manifests/bases/image-reflector-controller/labels.yaml, manifests/bases/kustomize-controller/labels.yaml, manifests/bases/notification-controller/labels.yaml, manifests/bases/source-controller/labels.yaml
Add `app.kubernetes.io/part-of: flux` label to controllers base to allow targeting all deployments by label in the install kustomization.
=> Add `part-of` label to controllers base

.github/workflows/conformance.yaml
=> Run ARM64 e2e tests on GitHub runners

.github/workflows/conformance.yaml
Bump Kind node images to latest minor versions of Kubernetes.
=> Update conformance tests to Kubernetes v1.30.2

cmd/flux/bootstrap_gitlab.go, internal/flags/gitlab_visibility.go, internal/flags/gitlab_visibility_test.go, pkg/bootstrap/bootstrap_provider.go
This MR introduces a `––visibility=private|public|internal` flag for `bootstrap gitlab`.
At the same time it deprecates the `--private` flag.
Related to https://github.com/fluxcd/flux2/issues/3817
=> Introduce visibility flag for bootstrap gitlab

internal/build/build.go, internal/build/diff.go
This PR stops spinner on cancel of `flux diff kustomization` command - otherwise cursor (hidden by spinner package) remains invisible.
`stopSpinner()` is called before `CleanDirectory()` since later happens to return an error if _kustomize.yaml_ doesn't exist and then `Cancel()` exits still leaving cursor invisible.
=> Stop spinner on cancel of flux diff kustomization

.github/workflows/conformance.yaml
=> Run conformance tests for Kubernetes v1.31

.github/workflows/e2e-azure.yaml, .github/workflows/e2e-bootstrap.yaml, .github/workflows/e2e-gcp.yaml, .github/workflows/e2e.yaml, .github/workflows/release.yaml, .github/workflows/update.yaml, Dockerfile
Part of: https://github.com/fluxcd/flux2/issues/4927
=> Build with Go 1.23

cmd/flux/build_kustomization.go, cmd/flux/build_kustomization_test.go, cmd/flux/diff_kustomization.go, cmd/flux/diff_kustomization_test.go, cmd/flux/main_test.go, cmd/flux/testdata/build-kustomization/my-app/configmap.yaml, cmd/flux/testdata/build-kustomization/podinfo-with-my-app-result.yaml, cmd/flux/testdata/build-kustomization/podinfo-with-my-app/kustomization.yaml, cmd/flux/testdata/build-kustomization/podinfo-with-my-app/my-app.yaml, cmd/flux/testdata/diff-kustomization/diff-with-recursive.golden, cmd/flux/testdata/diff-kustomization/my-app.yaml, internal/build/build.go, internal/build/build_test.go, internal/build/diff.go
This PR will add `--recursive` flag to recursively diff encountered Kustomizations similar to discussions https://github.com/fluxcd/flux2/discussions/2466, https://github.com/fluxcd/flux2/discussions/2434, https://github.com/fluxcd/flux2/discussions/820. (Currently it doesn't expand HelmReleases, probably could be added later).
Sources of additional repositories can be provided as comma-separated list by `--local-sources Kind/namespace/name=path` (i.e. `--local-sources GitRepository/flux-system/flux-gitops=$HOME/git/flux-gitops`)
Couple of words on our use case and motivation. We have number of clusters of different kinds sharing common GitOps repository with Kustomizations and overrides. To avoid unexpected changes most clusters are locked to a specific SHA instead of main branch. So …
=> Recursively diff Kustomizations

cmd/flux/create_source_git.go, cmd/flux/create_source_git_test.go, cmd/flux/testdata/create_source_git/source-git-provider-azure.yaml, cmd/flux/testdata/create_source_git/source-git-provider-generic.yaml, internal/flags/source_git_provider.go
- Add provider flag to `flux create source git` command with supported values: `azure`, `generic`.
- Unit tests validating the generated yaml with supported provider and error conditions.
=> [RFC-0007] Add `--provider` flag to `flux create source git`

.github/workflows/conformance.yaml, .github/workflows/e2e-bootstrap.yaml, .github/workflows/e2e.yaml
Update conformance tests matrix to the latest supported Kubernetes versions.
Kubernetes 1.28 active supported ended https://endoflife.date/kubernetes so this PR removes 1.28 from the test suite.
Part of: #4947
=> Run conformance tests for Kubernetes 1.29-1.31

cmd/flux/create_source_bucket.go, cmd/flux/create_source_git.go, cmd/flux/create_source_oci.go
Add the `--proxy-secret-ref` flag to:
- `flux create source bucket`
-  `flux create source git`
-  `flux create source oci`
Part of: #4947
=> Add `--proxy-secret-ref` to `flux create source` commands

cmd/flux/create_secret_proxy.go, cmd/flux/create_secret_proxy_test.go, cmd/flux/main_test.go, cmd/flux/testdata/create_secret/proxy/secret-proxy.yaml, pkg/manifestgen/sourcesecret/options.go, pkg/manifestgen/sourcesecret/sourcesecret.go
Add `flux create secret proxy` command for generating Kubernetes Secrets used for Bucket, GitRepository and OCIRepository in `.spec.proxySecretRef`.
=> Add `flux create secret proxy` command

.github/workflows/conformance.yaml
Official repo is `replicated-actions`
=> Use replicated-actions in conformance tests 

docs/release/release-notes-template.md
See my brief exchange with @stefanprodan in
- https://github.com/fluxcd/flux2/discussions/5072
=> docs: Mention Flux upgrade guide in release notes

internal/build/diff.go
When recursively diffing Kustomization objects on a cluster, each Kustomization is built and then a server-side dry-run apply is performed. This isn't practical to perform if the Kustomization references a remote cluster via `kubeConfig.secretRef`.
Currently, because it's not skipped, it's treated as though it's being applied to the context cluster, not the remote cluster, which results in an incorrect diff.
Instead, write out special message / warnings indicating that it has been skipped:
```
► Kustomization/my-ns/my-kst skipped: diff not supported for remote clusters
```
See also:
* https://github.com/fluxcd/flux2/discussions/5065
=> fix: skip remote Kustomizations on recursive diff

cmd/flux/build_kustomization.go, cmd/flux/diff_kustomization.go
This will fix double quotes in examples that were misplaced when last example was added.
=> fix misplaced quotes

cmd/flux/debug_helmrelease.go, cmd/flux/debug_helmrelease_test.go, cmd/flux/debug_kustomization.go, cmd/flux/debug_kustomization_test.go, cmd/flux/export_test.go, cmd/flux/main_test.go, cmd/flux/testdata/debug_helmrelease/status.golden.yaml, cmd/flux/testdata/debug_kustomization/objects.yaml, cmd/flux/testdata/debug_kustomization/status.golden.yaml, cmd/flux/testdata/debug_kustomization/vars-from.golden.env, cmd/flux/testdata/debug_kustomization/vars.golden.env, cmd/flux/trace_test.go
This PR implements the `flux debug ks` command as specified in #5109 
Followup: #5106
Closes: #5109
=> Implement `flux debug kustomization` command

rfcs/0008-custom-event-metadata-from-annotations/README.md
This RFC comes as a response to the need for adding custom metadata to events about Flux objects
sent to notification providers. 
When sending events about Flux objects, we propose sending annotation keys prefixed with the well-defined
API Group `event.toolkit.fluxcd.io` followed by a slash, i.e. prefixed with `event.toolkit.fluxcd.io/`, in
addition to all the metadata that is already sent in the event.
=> [RFC-0008] Custom Event Metadata from Annotations

.github/workflows/conformance.yaml
OpenShift 4.16 & 4.17 are also now available to add to the existing conformance testing.
See https://github.com/fluxcd/flux2/pull/4729#issuecomment-2578138218
=> Add OpenShift 4.16 & 4.17 to conformance testing

cmd/flux/resume.go, cmd/flux/testdata/kustomization/resume_kustomization_from_git_multiple_args_wait.golden
Currently, doing a resume operation on non-existent objects, e.g.
`flux resume helmrelease foo bar baz`
results in the error:
```
✗ no HelmRelease objects found in flux-system namespace
✗ no HelmRelease objects found in flux-system namespace
✗ no HelmRelease objects found in flux-system namespace
```
This message could be more helpful. Additionally, when resuming only a single resource, the error message is slightly misleading as there might exist `HelmRelease` objects, just not the ones your provided.
With this PR, the output would become:
```
✗ HelmRelease object 'foo' not found in flux-system namespace
✗ HelmRelease object 'bar' not found in flux-system namespace
✗ HelmRelease object 'baz' not found in flux-system namespace
```
This error message is more descriptive and follows the …
=> Improve "flux resume" error message on non-existent object

internal/build/diff.go
Fixes: https://github.com/fluxcd/flux2/issues/5163
Following https://github.com/fluxcd/pkg/pull/862
=> fix: align `flux diff` skipping with kustomize-controller

.github/workflows/conformance.yaml
Update the conformance test suite to latest Kubernetes supported versions and drop EOL versions.
Part of: https://github.com/fluxcd/flux2/issues/5186
=> Update conformance test suite

.github/workflows/release.yaml
In this PR:
* use auto-generate ephemeral GITHUB_TOKEN
* check token's permissions (seem to be in place already)
* some minor formatting improvements
=> change: use the default ephemeral GITHUB_TOKEN instead of the static one

.scorecard.yml
According to the [docs](https://github.com/ossf/scorecard/tree/main/config), we should be able to put in place annotations about why the check should be ignored. Unfortunately, I failed to confirm this with a local run - maybe it will work fine when it runs for a real repository.
closes #5257
=> add: OSSF scorecard configuration file - ignore false-positive

cmd/flux/diff_artifact.go, cmd/flux/list_artifact.go, cmd/flux/pull_artifact.go, cmd/flux/push_artifact.go
This PR relates to the [following discussion](https://github.com/fluxcd/flux2/discussions/5296#discussioncomment-12801631).
If merged, this PR will introduce a new `--insecure-registry` flag to the following commands: `push artifacts`, `pull artifact`, `diff artifact` and `list artifacts`. When used the flag will lead to the option `crane.Insecure` being passed to the `crane` client allowing the use of insecure repositories.
=> Allow to pull/push artifacts to insecure registries without TLS

rfcs/0010-multi-tenant-workload-identity/README.md
In this RFC we aim to add support for multi-tenant workload identity in Flux, i.e. the ability to specify at the object-level which set of cloud provider permissions must be used for interacting with the respective cloud provider on behalf of the reconciliation of the object. In this process, credentials must be obtained automatically, i.e. this feature must not involve the use of secrets. This would be useful in a number of Flux APIs that need to interact with cloud providers, including all controllers except helm-controller.
Preview: https://github.com/fluxcd/flux2/blob/rfc-multi-tenant-workload-identity/rfcs/0010-multi-tenant-workload-identity/README.md
Umbrella issue for implementation: #5022
=> [RFC-0010] Multi-Tenant Workload Identity

cmd/flux/build_kustomization_test.go, internal/build/build.go
This PR tries to fix the issue using `flux build` with dry-run and recursion.
We have a setup with nested kustomizations and want to render the whole tree 
as yaml files, including `postBuild` substitutions. Afterwards, this should be
checked via kube-linter.
Currently this seems not possible(?) with the flux-cli together with dry-run, 
therefore I made some changes.
Since I don't know all the use cases for `flux build`, it is hard to tell if this
breaks anything.
Maybe someone with deeper knowledge can review the changes.
The command I use is similar to this:
flux build kustomization flux-system \
--recursive \
--path ./clusters/dev/mykustomizations \
-n flux-system \
--local-sources GitRepository/flux-system/flux-system=./ \
--dry-run \
--kustomization-file …
=> fix: allow recursive dry-run over local sources

manifests/rbac/controller.yaml
Part of: #5022
All the six controllers will eventually implement object-level workload identity so this should be fine.
=> [RFC-0010] Add RBAC for creating service account tokens

cmd/flux/get.go, cmd/flux/get_test.go
Fixes #5330 - Changes the error handling in the `get` command to properly return non-zero exit codes when resources are not found, instead of just logging errors.
I tested both the original and modified behaviour with the following test script (I compiled before to compare to the version in .bin/flux):
```
#!/bin/bash
echo "Test 1: Specific object not found - original flux command (should return 0 exit code)"
flux get kustomization non-existent-resource
echo "Exit code: $?"
echo -e "\nTest 2: No objects found in namespace - original flux command (should return 0 exit code)"
flux get helmrelease -n kube-system
echo "Exit code: $?"
echo -e "\nTest 3: Specific object not found - modified ./bin/flux command (should return 1 exit code)"
./bin/flux get kustomization non-existent-resource
echo …
```
=> Fix exit code handling in get command

.github/workflows/e2e.yaml
The `--short` flag has been [removed from kubectl with 1.28.0](https://github.com/kubernetes/kubernetes/blob/49945dbfab342a6d7dee7e83778bb1cc3886bdbe/CHANGELOG/CHANGELOG-1.28.md#deprecation).
=> Fix e2e workflow

.github/labels.yaml
=> Add backport label for `v2.6.x`

cmd/flux/oci.go, cmd/flux/push_artifact.go, go.mod, go.sum
=> fix: Allow Azure CLI calls in `flux push artifact --provider azure` on DevOps runners

cmd/flux/create_tenant.go, cmd/flux/create_tenant_test.go, cmd/flux/testdata/create_tenant/tenant-basic.yaml, cmd/flux/testdata/create_tenant/tenant-with-cluster-role.yaml, cmd/flux/testdata/create_tenant/tenant-with-service-account.yaml
This PR adds an optional cli flag `--with-service-account` to the `flux create tenant` command. The flag allows to configure the name of the ServiceAccount, which is created by the cli command.
If the flag is not given, the current default is used (tenant name).
Closes #5400
=> Make service-account name configurable in `flux create tenant`

cmd/flux/oci.go, cmd/flux/push_artifact.go, go.mod, go.sum
This PR updates the error handling for `GetArtifactRegistryCredentials()` following the improvements in fluxcd/pkg/auth v0.18.0.
As mentioned in https://github.com/fluxcd/image-reflector-controller/pull/786#issuecomment-2993234261, this removes unnecessary nil checks
as the function now returns errors directly for unsupported providers.
- Update fluxcd/pkg/auth to v0.18.0
- Replace authentication code in push_artifact.go with `loginWithProvider()`
- Remove unnecessary authenticator nil check in oci.go
- Implements cleanup mentioned in fluxcd/image-reflector-controller#786
- Part of the broader effort to simplify error handling after fluxcd/pkg#946
=> refactor: cleanup GetArtifactRegistryCredentials error handling

go.mod, go.sum
Upgrading `pkg/ssa` to version `0.49.0` 
Includes fix for #800: Remove CABundle from CRDs if cert is invalid
@matheuscscp
=> Bump pkg/ssa to v0.49.0 for CABundle validation fix

cmd/flux/push_artifact.go, go.mod, go.sum
=> Fix `flux push artifact` for insecure registries

.github/workflows/update.yaml
=> ci: Use GITHUB_TOKEN for API calls in update workflow

manifests/bases/helm-controller/labels.yaml, manifests/bases/image-automation-controller/labels.yaml, manifests/bases/image-reflector-controller/labels.yaml, manifests/bases/kustomize-controller/labels.yaml, manifests/bases/notification-controller/labels.yaml, manifests/bases/source-controller/labels.yaml, manifests/install/labels.yaml, manifests/openshift/labels.yaml, pkg/manifestgen/install/templates.go
Ensure also pods contain the relevant labels inherited from parent Deployment object, this makes it easier to select and filter the pods using the labels eg. when scraping for metrics.
=> manifests: Add `app.kubernetes.io/part-of: flux` label to controller pods

.github/workflows/conformance.yaml
Part of: #5496
Using:
- `ghcr.io/fluxcd/kindest/node:v1.34.0-amd64`
- `ghcr.io/fluxcd/kindest/node:v1.34.0-arm64`
=> Run conformance tests for Kubernetes 1.34.0

manifests/bases/helm-controller/patch.yaml, manifests/bases/image-automation-controller/patch.yaml, manifests/bases/image-reflector-controller/patch.yaml, manifests/bases/kustomize-controller/patch.yaml, manifests/bases/notification-controller/patch.yaml, manifests/bases/source-controller/patch.yaml
Remove the `GOMAXPROCS` env var from all controllers to allow the Go 1.25 runtime to dynamically set it from the cgroup CPU limits.
xref: https://github.com/fluxcd/flux2/issues/5481
=> Allow the Go runtime to dynamically set `GOMAXPROCS`

cmd/flux/events.go
The `flux events` command always applied a namespace filter, even when `--all-namespaces` was set.  
This produced incomplete results and confused users expecting cluster-wide events.
Changes made:
* Build `clientListOpts` dynamically.
* Omit `client.InNamespace(...)` when `eventArgs.allNamespaces` is true, ensuring no namespace constraint.
Impact:
`flux events --all-namespaces` now returns events from every namespace, restoring expected functionality without affecting other options.
=> fix(events): respect `--all-namespaces` flag

rfcs/0000-external-artifact/README.md, rfcs/0012-external-artifact/README.md
This RFC proposes the introduction of a new API called `ExternalArtifact` that would allow 3rd party controllers to act as a source of truth for the cluster desired state. In effect, the `ExternalArtifact` API acts as an extension of the existing `source.toolkit.fluxcd.io` APIs that enables Flux `kustomize-controller` and `helm-controller` to consume artifacts from external source types that are not natively supported by `source-controller`.
Preview: https://github.com/fluxcd/flux2/blob/rfc-external-artifact/rfcs/0012-external-artifact/README.md
=> [RFC-0012] External Artifact API

cmd/flux/debug_helmrelease.go, cmd/flux/debug_helmrelease_test.go, cmd/flux/testdata/debug_helmrelease/history-empty.golden.yaml, cmd/flux/testdata/debug_helmrelease/history.golden.yaml, cmd/flux/testdata/debug_helmrelease/objects.yaml, rfcs/0012-external-artifact/README.md
This pull request adds a new feature to the `flux debug hr` command, allowing users to print the reconciliation history of a Helm release. It also refines the command-line flag validation logic to ensure only one output option is selected at a time. The most important changes are grouped below:
* Added the `--show-history` flag to the `flux debug hr` command, enabling users to print the reconciliation history of a Helm release. This includes documentation and YAML output of the release history. [[1]](diffhunk://#diff-87f93a84de91276a8c89099e27232e59b66188a5e31d38be44de0881c385d443L43-R46) [[2]](diffhunk://#diff-87f93a84de91276a8c89099e27232e59b66188a5e31d38be44de0881c385d443R55-R88) [[3]](diffhunk://#diff-87f93a84de91276a8c89099e27232e59b66188a5e31d38be44de0881c385d443R133-R146)
* Updated …
=> Add `--show-history` flag to `debug  helmrelease`

cmd/flux/artifact.go, cmd/flux/create_source_bucket.go, cmd/flux/create_source_git.go, cmd/flux/create_source_helm.go, cmd/flux/create_tenant.go, cmd/flux/events.go, cmd/flux/export.go, cmd/flux/export_artifact.go, cmd/flux/export_artifact_generator.go, cmd/flux/get_artifact.go, cmd/flux/get_artifact_generator.go, cmd/flux/install.go, cmd/flux/main.go, cmd/flux/tree_artifact.go, cmd/flux/tree_artifact_generator.go, go.mod, go.sum, internal/utils/utils.go
This PR adds the following commands to the Flux CLI:
- `flux export artifact generator` - Exports one or more `ArtifactGenerators` from the cluster in YAML format 
- `flux get artifact generator` - Lists the `ArtifactGenerators` and their status 
- `flux tree artifact generator` - Prints the list of ExternalArtifacts managed by an `ArtifactGenerator`
- `flux events --for ArtifactGenerator/<name>` - Prints the events emitted by source-watcher for an `ArtifactGenerator`
Part of: #5514
=> Add read-only commands for `ArtifactGenerator` kind

.github/workflows/release.yaml
Turns out #5509 broke our release workflow, the public endpoint does not return the latest Flux release, instead it serves `latest` from cache, which will always be one version behind at release time. This PR switches back to using the GitHub API by passing the `GITHUB_TOKEN` to the action.
Closes: #5546
=> ci: Set `GITHUB_TOKEN` in the `release-flux-manifests` workflow

cmd/flux/diff_artifact.go, cmd/flux/list_artifact.go, cmd/flux/oci.go, cmd/flux/pull_artifact.go, cmd/flux/push_artifact.go, cmd/flux/tag_artifact.go
Fixes: #5549
While this fix is not released in Flux 2.7.1 (to happen soon), users can use the workarounds described below.
All the workarounds below are based on generating a docker config that `flux push artifact` will detect automatically, in which case the `--provider` flag is not needed. They are standard docker login procedures for the cloud providers, the same procedures you use for pushing app images to container registries. Flux OCI artifacts work seamlessly with these procedures.
For GitHub Actions, follow instructions [here](https://github.com/aws-actions/amazon-ecr-login?tab=readme-ov-file#building-and-pushing-an-image). Example:
```yaml
- name: Configure AWS credentials
uses: aws-actions/configure-aws-credentials@v5
with:
role-to-assume: arn:aws:iam::<AWS ACCOUNT ID>:role/<AWS …
```
=> Fix `flux push artifact` not working with `--provider`

.goreleaser.yml
AUR is now publishing Flux CLI, dropping our packages from the release workflow.
https://archlinux.org/packages/extra/x86_64/fluxcd/
=> Disable AUR publishing

pkg/manifestgen/install/manifests.go, pkg/manifestgen/install/templates.go
Changes:
- Fix `--storage-adv-addr` in source-watcher deployment (fix: #5573)
- Use `RUNTIME_NAMESPACE` when setting `--events-addr` (fix: #5567)
=> Fix manifest generation for `--storage-adv-addr` and `--events-addr` flags
