Makefile
cmd/tk/main.go
go.sum

Add command to generate CLI commands docs.

Generate tk docs with cobra/doc

---

manifests/bases/kustomize-controller/kustomization.yaml
manifests/bases/source-controller/kustomization.yaml

- source-controller v0.0.1-alpha.3
- kustomize-controller v0.0.1-alpha.5

manifests: update components

---

cmd/tk/check.go
cmd/tk/install.go
cmd/tk/main.go
cmd/tk/uninstall.go
cmd/tk/utils.go

Changes:
- add components global flag
- install selected components
- check selected components

Implement components selection

---

cmd/tk/create_kustomization.go
cmd/tk/create_source.go

Changes:
- add create kustomization command
- update kustomization if exists
- update source if exists

Implement create kustomization command

---

Makefile
cmd/tk/create_kustomization.go
cmd/tk/create_source.go
cmd/tk/main.go

Changes:
- add git tag option to create source
- add examples to main command
- format kustomization examples

Add git tag option to create source

---

.github/workflows/e2e.yaml
cmd/tk/delete.go
cmd/tk/delete_kustomization.go
cmd/tk/get_kustomization.go
cmd/tk/resume.go
cmd/tk/resume_kustomization.go
cmd/tk/suspend.go
cmd/tk/suspend_kustomization.go

Changes:
- add delete kustomization command with confirmation and warning if not suspended
- add suspend kustomization command
- add resume kustomization command
- add suspend/resume/delete e2e tests

Implement delete, suspend and resume kustomization

---

.github/workflows/e2e.yaml
cmd/tk/delete_source.go
cmd/tk/delete_source_git.go
cmd/tk/export.go
cmd/tk/export_kustomization.go
cmd/tk/export_source.go
cmd/tk/export_source_git.go
cmd/tk/main.go
cmd/tk/utils.go
go.mod

Changes:
- add export commands for git sources and kustomizations
- add export e2e tests
- add delete source git command
- add delete source git e2e test

Implement export to YAML

---

.github/workflows/e2e.yaml
cmd/tk/resume_kustomization.go

When resuming a kustomization, check for the condition reason when waiting to sync.

Fix resume waiting

---

cmd/tk/main.go

Changelog will be auto-generated and posted on the release page.

Release v0.0.1-alpha.1

---

.github/workflows/e2e.yaml
cmd/tk/check.go
cmd/tk/install.go
go.mod
go.sum

Use kustomize libraries in install command and drop kustomize binary requirement.

Use kustomize API instead of binary

---

cmd/tk/uninstall.go

This is an attempt to provide a way for the cluster admins to bulk delete all objects that were deployed on the cluster via the kustomize-controller before uninstalling the toolkit.

Add kustomizations removal to uninstall cmd

---

cmd/tk/bootstrap_github.go

This PR allows a cluster admin to rotate the SSH deploy key. An admin can delete the current key from the cluster and run the bootstrap, a new key will be created and the old one will be removed from the GitHub deploy keys.

Rotate GitHub deploy key during bootstrap

---

docs/get-started/index.md

Add get started guide

---

cmd/tk/check.go
cmd/tk/create_source_git.go
cmd/tk/export_source_git.go
cmd/tk/get_source_git.go
cmd/tk/sync_source_git.go
cmd/tk/utils.go
pkg/git/provider_github.go
pkg/git/provider_gitlab.go

Improve logging and error messages

---

cmd/tk/bootstrap_github.go
cmd/tk/bootstrap_gitlab.go

Use owner in Git author email

---

cmd/tk/main.go
mkdocs.yml

Honour KUBECONFIG environment variable

---

docs/roadmap/index.md
mkdocs.yml

Add roadmap draft to docs

---

cmd/tk/bootstrap.go
cmd/tk/bootstrap_github.go
cmd/tk/bootstrap_gitlab.go
cmd/tk/check.go
cmd/tk/create_kustomization.go
cmd/tk/create_source_git.go
cmd/tk/delete_kustomization.go
cmd/tk/delete_source_git.go
cmd/tk/export_kustomization.go
cmd/tk/export_source_git.go
cmd/tk/get_kustomization.go
cmd/tk/get_source_git.go
cmd/tk/install.go
cmd/tk/log.go
cmd/tk/main.go
cmd/tk/resume_kustomization.go
cmd/tk/suspend_kustomization.go
cmd/tk/sync_kustomization.go
cmd/tk/sync_source_git.go
cmd/tk/uninstall.go
pkg/log/log.go

Create logger interface

---

docs/guides/notifications.md
manifests/bases/notification-controller/kustomization.yaml
manifests/bases/source-controller/kustomization.yaml
manifests/bases/source-controller/patch.yaml

Changes:
- update notification-controller to v0.0.1-beta.1
- update source-controller to v0.0.2
- enable notifications for source events
- update notifications guide with wildcards

Enable notifications for source events

---

CONTRIBUTING.md
docs/contributing/index.md
mkdocs.yml

Point to #flux-dev, point to video and relevant repositories.

explain a bit more about Flux Toolkit

---

CONTRIBUTING.md
README.md
docs/dev-guides/source-watcher.md
mkdocs.yml

Fix: https://github.com/fluxcd/source-controller/issues/76
Ref: #53
Preview: https://toolkit.fluxcd.io/dev-guides/source-watcher/

Add source watcher dev guide

---

cmd/tk/reconcile_source_helm.go
cmd/tk/resume_helmrelease.go
cmd/tk/suspend_helmrelease.go
docs/cmd/tk_resume.md
docs/cmd/tk_resume_helmrelease.md
docs/cmd/tk_suspend_helmrelease.md
mkdocs.yml

Changes:
- add `tk suspend hr`
- add `tk resume hr`
- update docs
- fix readiness checks for HelmRepositories/Releases

Add helm suspend/resume commands

---

cmd/tk/install.go

Set nodeSelector to linux/amd64 for clusters with mixed nodes (linux, windows, amd64, arm).

Add linux/amd64 node selector to controllers

---

docs/_static/custom.css
docs/roadmap/index.md
mkdocs.yml

Add progressbar and checks to roadmap md

---

docs/roadmap/index.md

Mark metrics as completed ref:  #94

Mark metrics as completed in roadmap

---

docs/faq/index.md
mkdocs.yml

Add initial set of FAQ

---

go.mod
go.sum
manifests/bases/kustomize-controller/kustomization.yaml

Update kustomize-controller to v0.0.10

---

cmd/gotk/create_kustomization.go
cmd/gotk/main.go
docs/cmd/gotk_create_kustomization.md
docs/guides/mozilla-sops.md
mkdocs.yml

Changes:
- Add decryption flags to `gotk create kustomization` command
- Add Mozilla SOPS guide to docs

Mozilla SOPS

---

.github/workflows/bootstrap.yaml
cmd/gotk/bootstrap_github.go
cmd/gotk/create.go
go.mod
go.sum

Add e2e tests for `gotk bootstrap github` using fluxcd-testing org.

Add GitHub bootstrap e2e test

---

cmd/gotk/bootstrap.go
cmd/gotk/create_kustomization.go
go.mod
go.sum
manifests/bases/kustomize-controller/kustomization.yaml

Changes:
- Update kustomize-controller to v0.0.12
- Add HelmRelease kind to heath checks

Update kustomize-controller to v0.0.12

---

cmd/gotk/bootstrap.go

Validate bootstrap required components

---

cmd/gotk/bootstrap_github.go
cmd/gotk/bootstrap_gitlab.go

Always apply sync manifests on bootstrap

---

CONTRIBUTING.md
README.md
docs/index.md

Add community section to `README.md`

---

.github/workflows/docs.yaml
cmd/gotk/create_source_bucket.go
cmd/gotk/delete_source_bucket.go
cmd/gotk/export_source_bucket.go
cmd/gotk/get_source_bucket.go
cmd/gotk/main.go
cmd/gotk/reconcile_source_bucket.go
docs/cmd/gotk_create_source.md
docs/cmd/gotk_create_source_bucket.md
docs/cmd/gotk_delete_source_bucket.md
docs/cmd/gotk_export_source.md
docs/cmd/gotk_export_source_bucket.md
docs/cmd/gotk_get_sources.md
docs/cmd/gotk_get_sources_bucket.md
docs/cmd/gotk_reconcile_source.md
docs/cmd/gotk_reconcile_source_bucket.md
docs/index.md
mkdocs.yml

Implement bucket CRUD commands

---

cmd/gotk/bootstrap.go
cmd/gotk/utils.go

This PR generates a kustomization.yaml file in the bootstrap target path, this enables further customisations of the bootstrap manifests.

Generate a kustomize package for the bootstrap manifests

---

cmd/gotk/bootstrap.go
cmd/gotk/reconcile_helmrelease.go
cmd/gotk/reconcile_kustomization.go
docs/cmd/gotk_bootstrap.md
docs/cmd/gotk_bootstrap_github.md
docs/cmd/gotk_bootstrap_gitlab.md
docs/get-started/index.md
docs/guides/installation.md

This PR changes the bootstrap default branch to `main` to match GitHub default.

Change the bootstrap default branch to main

---

.github/workflows/docs.yaml
.github/workflows/e2e.yaml
.github/workflows/fossa.yml
README.md

Ref: https://github.com/fluxcd/toolkit/issues/152

Change default branch to main

---

cmd/gotk/get_helmrelease.go
cmd/gotk/get_kustomization.go
cmd/gotk/get_source_bucket.go
cmd/gotk/get_source_git.go
cmd/gotk/get_source_helm.go

Remove faulty `break` from get commands

---

cmd/gotk/utils.go

Ref:
https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#the-kubeconfig-environment-variable
Fixes: #300

Support multi-path KUBECONFIG

---

.github/workflows/e2e.yaml
cmd/gotk/get.go
cmd/gotk/get_helmrelease.go
cmd/gotk/get_kustomization.go
cmd/gotk/get_source_bucket.go
cmd/gotk/get_source_git.go
cmd/gotk/get_source_helm.go
cmd/gotk/utils.go
docs/cmd/gotk_get.md
docs/cmd/gotk_get_helmreleases.md
docs/cmd/gotk_get_kustomizations.md
docs/cmd/gotk_get_sources.md
docs/cmd/gotk_get_sources_bucket.md
docs/cmd/gotk_get_sources_git.md
docs/cmd/gotk_get_sources_helm.md
go.mod
go.sum

Fix #292 
Happy Hacktoberfest! 🎃 
Signed-off-by: circa10a <caleblemoine@gmail.com>

Switch get commands to use tables for output

---

docs/index.md

- close parentheses
- make link to guide more obvious

close parentheses, make link to guide more obvious

---

README.md

Added invite for Leigh's GOTK guide walk-through on Oct 19 (10am PT/18:00 BST) to the Community Section. LMK if this should be somewhere else - or condensed (wasn't sure how much info to include). Thanks! :)

Add featured talks and meetups section

---

cmd/gotk/uninstall.go

Changes to uninstall command:
- ignore not found errors when deleting objects
- remove the CR/CRDs before deleting the cluster role binding
- capture kubectl exist code
Uninstalling on a cluster without the toolkit CRDs should not error out when run with `gotk uninstall --resources=false`, fix: #328

Uninstall improvements

---

docs/roadmap/index.md

This leaves the implementation tasks as not done -- a bit of a
simplification, since there's some implementation done, and some
design left to do, but it's close enough at this level.
I estimated that having the design basics figured out is worth 30%
overall.

Mark the design tasks for image automation as done

---

cmd/gotk/create_alertprovider.go

Set alert provider secretRef only if specified

---

docs/index.md

updated "Community" section to include "Featured Talks" + "Upcoming Meetups"

updated with featured talks + upcoming meetups

---

cmd/gotk/bootstrap.go

This PR enables client-side validation for the kustomization created at bootstrap.

Enable client side validation on bootstrap

---

.goreleaser.yml

Publish CLI binary for Windows

---

cmd/gotk/uninstall.go

Ignore missing kinds when uninstalling, do not assume `bootstrap` was used.
Fix: #359

Ignore missing kinds when uninstalling

---

docs/guides/installation.md
docs/guides/sealed-secrets.md

Ref: https://helm.sh/blog/new-location-stable-incubator-charts/

Update the stable Helm repository in docs

---

README.md

- Adjust the description so it talks about the whole system (Flux) as
one thing
- Describe what GitOps Toolkit is, and how it relates to Flux v2.

Minimal rewrite of README to explain Flux v2

---

README.md
docs/index.md

(this also happens to fix a dangling link in the intro paras)

Add GOTK section to index

---

README.md
install/README.md
install/flux.sh

Fix install script

---

README.md
docs/index.md

Changes:
- add Michael's Kubelist podcast
- add KubeCon NA upcoming talk

Update talks section

---

docs/dev-guides/source-watcher.md
docs/internal/release.md

Explain the release procedure and how to upgrade Kubernetes modules.

Add release procedure documentation

---

docs/guides/helm-operator-migration.md
mkdocs.yml

Add Helm Operator migration guide

---

docs/guides/flux-v1-migration.md

docs: fix typo

---

docs/guides/helmreleases.md

Add values file example to Helm docs

---

.github/workflows/bootstrap.yaml
.github/workflows/e2e.yaml

Ref: https://github.com/engineerd/setup-kind/issues/28

Update engineerd/setup-kind to v0.5.0

---

cmd/flux/create_source_helm.go
cmd/flux/reconcile_source_bucket.go
cmd/flux/reconcile_source_git.go
cmd/flux/reconcile_source_helm.go

Utilize LastHandledReconcileAt for source reconcile commands

---

MAINTAINERS

Self-Promotion is the best promotion :blush:

Add @relu to maintainers list

---

docs/guides/mozilla-sops.md

Add AWS IAM role example to SOPS docs

---

README.md

Signed-off-by: mewzherder <tamao@weave.works>

Update Upcoming events w/ Nov 30 talk

---

cmd/flux/bootstrap.go
cmd/flux/check.go
cmd/flux/install.go
cmd/flux/uninstall.go
internal/utils/utils.go

Set kubecontext and kubeconfig for kubectl exec

---

docs/guides/installation.md

Add upgrade docs to install guide

---

MAINTAINERS

Signed-off-by: Philip Laine <philip.laine@xenit.se>

Add Philip Laine to maintainer list

---

docs/guides/installation.md

Specify where to place Kubernetes manifests after bootstrap

---

README.md

Signed-off-by: mewzherder <tamao@weave.works>

Upcoming events and Featured talks: reorder & update

---

cmd/flux/create_secret_git.go

Fix create secret for Git over HTTP/S

---

pkg/manifestgen/install/manifests.go

Signed-off-by: Sylvain Rabot <sylvain@abstraction.fr>

Fix typo in manifests download error message

---

cmd/flux/create_source_git.go
docs/cmd/flux_create_source_git.md
docs/guides/installation.md
go.sum

Adds a flag to the git source create command to be able to specify the git implementation field. It also adds specific information for the Azure DevOps users.

Add git implementation flag and note about Azure DevOps

---

cmd/flux/bootstrap.go
cmd/flux/install.go

Fix cluster domain mapping

---

docs/guides/installation.md
mkdocs.yml

Fix Azure DevOps SSH URL in docs

---

cmd/flux/completion_zsh.go
docs/cmd/flux_completion_zsh.md

As spotted on Twitter :-)
https://twitter.com/alc0der/status/1327532027621617665

Fix zsh completion command example

---

action/README.md

Add note about ignoring flux action binary

---

action/entrypoint.sh

Ref: https://github.com/fluxcd/flux2/issues/540#issuecomment-747407696

Move flux binary to GitHub workspace

---

cmd/flux/check.go
internal/utils/utils.go

Support check command with multiple config files

---

docs/guides/image-update.md

Make sure flux create output gets redirected to file

---

cmd/flux/bootstrap.go
cmd/flux/install.go
internal/utils/utils.go
pkg/manifestgen/install/options.go

Validates components set

---

docs/core-concepts/index.md
mkdocs.yml

This doc outlines some concepts that anyone going through the Getting Started Guide needs to be familiar with.

Add core concepts to docs

---

cmd/flux/bootstrap_gitlab.go

This pull request validates the project name for gitlab.
Fixes #633 

Validates project name for gitlab

---

docs/index.md

Put things in chronological order, added new events, moved old ones, switched order of the 2 sections to match fluxcd/flux2 
Signed-off-by: Stacey Potter <50154848+staceypotter@users.noreply.github.com>

Update upcoming events & featured talks section

---

docs/guides/helmreleases.md

This changes the documentation regarding how to configure HelmRepositories with cloud storage services.
The old documentation recommended using the Bucket resource, which has the downside that source-controller will download the whole bucket. Chartmuseum seems like a  better option as it is a helm project that has added support for a bunch of different backends. This is a huge benefit as it may reduce the amount of feature requests for source-controller to support different storage backends.
Fixes fluxcd/source-controller/issues/249
Fixes fluxcd/source-controller/issues/206

Update helm release guide

---

docs/guides/image-update.md

Document a workaround solution for users to rely on until native image
repository authentication is implemented for supported cloud providers.

Add documentation for ECR authentication

---

cmd/flux/bootstrap_github.go
cmd/flux/bootstrap_gitlab.go

Coverts backward slash to forward slash in path flag

---

cmd/flux/bootstrap.go
cmd/flux/bootstrap_github.go
cmd/flux/bootstrap_gitlab.go

Checks if bootstrap path differs

---

docs/roadmap/index.md

Specifically:
- integration into `flux` CLI
- guide to how to use the controllers

Cross off tasks in the image automation roadmap

---

cmd/flux/bootstrap.go
cmd/flux/create_secret.go
cmd/flux/create_secret_git.go
cmd/flux/create_source_git.go

Map ecdsa/ed25519 args to create secret

---

pkg/manifestgen/sync/sync.go

Ref: [terraform#73](https://github.com/fluxcd/terraform-provider-flux/issues/73)

Fix manifests path on Windows

---

docs/index.md

Signed-off-by: Stacey Potter <50154848+staceypotter@users.noreply.github.com>

Added Jan 25 Meetup to Upcoming Events section

---

cmd/flux/bootstrap_gitlab.go
go.mod
go.sum

Fix: #674
Merge after (pkg#66)[https://github.com/fluxcd/pkg/pull/66]

Fix GitLab bootstrap when used with sub-groups

---

internal/utils/utils.go

Check for multiple files in KUBECONFIG variable

---

docs/guides/image-update.md

Add GCR auth to image update guide

---

docs/index.md

Updated and moved this from Upcoming Events: 
- 11 Jan 2021 - [Helm + GitOps = ⚡️⚡️⚡️ with Scott Rigby](https://www.meetup.com/GitOps-Community/events/275348736/)
To this in Featured Talks:
- 11 Jan 2021 - [Helm + GitOps = ⚡️⚡️⚡️ with Scott Rigby](https://youtu.be/YG8jMFrYQvM)
Signed-off-by: Stacey Potter <50154848+staceypotter@users.noreply.github.com>

Moved 11 Jan talk from Upcoming to Featured

---

cmd/flux/bootstrap_gitlab.go
go.mod
go.sum

Update pkg/git to v0.2.1

---

.github/workflows/e2e.yaml

This PR adds e2e tests for container image scanning of public registries and semver policies.

Add e2e tests for image repository and policy

---

docs/guides/mozilla-sops.md

Add GCP docs for Mozilla SOPS

---

README.md

Signed-off-by: mewzherder <tamao@weave.works>

Clarify options on our GH Discussions page

---

README.md
docs/index.md

move talk info, part of fluxcd/community#24

---

cmd/flux/get_source_bucket.go
cmd/flux/get_source_chart.go
cmd/flux/get_source_git.go
cmd/flux/get_source_helm.go
cmd/flux/source.go

Refactor get source commands

---

cmd/flux/get_helmrelease.go
cmd/flux/get_kustomization.go
cmd/flux/helmrelease.go
cmd/flux/kustomization.go

Refactor get command for kustomization and helmrelease

---

docs/guides/helm-operator-migration.md

Ref: https://github.com/fluxcd/helm-controller/issues/185#issuecomment-765022697

Document StorageNamespace in Helm migration guide

---

pkg/manifestgen/install/manifests.go

Workaround for kustomize not being able to patch the SA in ClusterRoleBindings

RBAC Fix: Replace SA namespace in ClusterRoleBindings

---

cmd/flux/reconcile_helmrelease.go
cmd/flux/reconcile_kustomization.go

Set source namespace when reconciling with source

---

cmd/flux/delete_helmrelease.go
cmd/flux/delete_kustomization.go
cmd/flux/delete_source_bucket.go
cmd/flux/delete_source_git.go
cmd/flux/delete_source_helm.go

Refactor delete command for kustomizations, sources and helmreleases

---

cmd/flux/suspend_helmrelease.go
cmd/flux/suspend_kustomization.go
cmd/flux/suspend_source_bucket.go
cmd/flux/suspend_source_chart.go
cmd/flux/suspend_source_git.go
cmd/flux/suspend_source_helm.go

Refactor suspend commands

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
README.md
docs/index.md

Also link to support page.
Closes: fluxcd/website#77

Add issue template for bug reports and questions

---

cmd/flux/reconcile_helmrelease.go
cmd/flux/reconcile_kustomization.go
cmd/flux/reconcile_source_bucket.go
cmd/flux/reconcile_source_git.go
cmd/flux/reconcile_source_helm.go

Refactor reconcile commands

---

README.md

Signed-off-by: mewzherder <tamao@weave.works>

Community section clarity of purpose + support page link

---

cmd/flux/resume_helmrelease.go
cmd/flux/resume_kustomization.go
cmd/flux/resume_source_bucket.go
cmd/flux/resume_source_chart.go
cmd/flux/resume_source_git.go
cmd/flux/resume_source_helm.go

Refactor resume command

---

docs/guides/image-update.md

Increase attention to missing flux components.

Add image automation components hint to docs

---

cmd/flux/delete_image.go
cmd/flux/delete_image_policy.go
cmd/flux/delete_image_repository.go
cmd/flux/delete_image_updateauto.go
docs/cmd/flux_delete.md
docs/cmd/flux_delete_image.md
docs/cmd/flux_delete_image_policy.md
docs/cmd/flux_delete_image_repository.md
docs/cmd/flux_delete_image_update.md

This slipped through the auto->image change made in the course of preparing #538.

Rename flux delete auto to flux delete image

---

docs/guides/image-update.md

This PR extends the image automation documentation with:
- How to suspend automation and image scanning during an incident
- How to revert an application to a previous version using semver policies

Add incident management section to image automation docs

---

docs/faq/index.md

Signed-off-by: Chanwit Kaewkasi <chanwit@gmail.com>

Add FAQ to explain the current Kustomize behavior

---

docs/guides/installation.md

Ref: https://github.com/fluxcd/flux2/issues/760#issuecomment-775139828

Add Azure DevOps PAT auth to install docs

---

docs/guides/image-update.md
docs/roadmap/index.md

Flux image update feature parity is now at 100% 🎉

Update image update feature parity roadmap

---

.github/workflows/snyk.yaml

Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>

Snyk GitHub Action added

---

.github/workflows/docs.yaml

Fix controller_version helper func

---

docs/guides/installation.md

Ref: https://github.com/fluxcd/flux2/discussions/913

Document air-gapped install procedure

---

docs/faq/index.md

Fix anchor on kustomize migration link

---

.github/aur/flux-bin/PKGBUILD.template
.github/aur/flux-go/PKGBUILD.template
.github/aur/flux-scm/PKGBUILD.template

Install Bash, Fish, ZSH auto complete in AUR pkgs

---

docs/guides/image-update.md
docs/guides/installation.md
docs/guides/mozilla-sops.md
docs/index.md
docs/use-cases/azure.md
mkdocs.yml

Changes:
-   Add Azure Use-Case doc to new section (fix: #803)
-   Improve Azure DevOps install notes
-   Document Flux + SOPS + Azure Key Vault (fix: #851)

Document Azure + Flux Installs

---

docs/dev-guides/source-watcher.md

Depends on: https://github.com/fluxcd/source-watcher/pull/18

Update dev guide to controller-runtime v0.8

---

cmd/flux/alert.go
cmd/flux/alert_provider.go
cmd/flux/create_alert.go
cmd/flux/create_alertprovider.go
cmd/flux/create_helmrelease.go
cmd/flux/create_kustomization.go
cmd/flux/create_receiver.go
cmd/flux/create_source_bucket.go
cmd/flux/create_source_git.go
cmd/flux/create_source_helm.go
cmd/flux/delete_alert.go
cmd/flux/delete_alertprovider.go
cmd/flux/delete_source_helm.go
cmd/flux/export.go
cmd/flux/export_alert.go
cmd/flux/export_alertprovider.go
cmd/flux/export_helmrelease.go
cmd/flux/export_kustomization.go
cmd/flux/export_receiver.go
cmd/flux/export_secret.go
cmd/flux/export_source_bucket.go
cmd/flux/export_source_git.go
cmd/flux/export_source_helm.go
cmd/flux/get_alert.go
cmd/flux/get_alertprovider.go
cmd/flux/get_receiver.go
cmd/flux/receiver.go

Refactor remaining create, delete, export, get cmd to use adapter

---

cmd/flux/reconcile.go
cmd/flux/reconcile_alert.go
cmd/flux/reconcile_helmrelease.go
cmd/flux/reconcile_kustomization.go
cmd/flux/reconcile_with_source.go
cmd/flux/resume_alert.go
cmd/flux/resume_receiver.go
cmd/flux/suspend_alert.go
cmd/flux/suspend_receiver.go

Refactor reconcile and resume cmd for alert and receiver

---

cmd/flux/create_source_git.go
cmd/flux/log.go
pkg/log/log.go

Fix create source git auth for non-HTTPS repos

---

cmd/flux/bootstrap_git.go

Take private key from file into account in Git bootstrap

---

cmd/flux/create_image_policy.go
cmd/flux/create_image_repository.go
cmd/flux/create_image_update.go
cmd/flux/delete_image_policy.go
cmd/flux/delete_image_repository.go
cmd/flux/delete_image_update.go
cmd/flux/export_image_policy.go
cmd/flux/export_image_repository.go
cmd/flux/export_image_update.go
cmd/flux/get_image_all.go
cmd/flux/get_image_policy.go
cmd/flux/get_image_repository.go
cmd/flux/get_image_update.go
cmd/flux/image.go
cmd/flux/reconcile_image_repository.go
cmd/flux/reconcile_image_updateauto.go
cmd/flux/resume_image_repository.go
cmd/flux/resume_image_updateauto.go
cmd/flux/suspend_image_repository.go
cmd/flux/suspend_image_updateauto.go
internal/utils/utils.go

Move to `v1alpha2` image update APIs

---

.github/workflows/update.yaml

This includes updating the version in the `manifests/crds` directory
for the component thas has a newer latest version.
Fixes: #1258

build: incl CRD version change in component update

---

.github/workflows/update.yaml
manifests/crds/kustomization.yaml

Fix update automation and update CRDs

---

cmd/flux/create_secret_git.go
cmd/flux/create_source_git.go
docs/cmd/flux_create_secret_git.md
docs/cmd/flux_create_source_git.md

Add password for ssh private key to create secret git

---

manifests/monitoring/grafana/dashboards/control-plane.json
manifests/monitoring/grafana/deployment.yaml
manifests/monitoring/prometheus/deployment.yaml
manifests/monitoring/prometheus/prometheus.yml

Update Prometheus labels and dashboard

---

manifests/monitoring/grafana/dashboards/cluster.json
manifests/monitoring/grafana/dashboards/control-plane.json
manifests/monitoring/kube-prometheus-stack/kustomization.yaml
manifests/monitoring/kube-prometheus-stack/namespace.yaml
manifests/monitoring/kube-prometheus-stack/release.yaml
manifests/monitoring/kube-prometheus-stack/repository.yaml
manifests/monitoring/monitoring-config/kustomization.yaml
manifests/monitoring/monitoring-config/podmonitor.yaml

Fixes #1392 
Flux Cluster Stats
Flux Control Plane
Kubernetes / Compute Resources/ Workloads

Replace monitoring stack with kube-prometheus-stack

---

go.mod
go.sum

This update along with #1471 fixes #1463

Update go-git to v5.4.2

---

cmd/flux/create_secret_git.go

Adresses https://github.com/fluxcd/flux2/discussions/1504

Fix yq example for create secret git

---

cmd/flux/bootstrap_git.go

This PR allows unattended bootstrap for when the deploy key is setup in advance .e.g
```sh
flux bootstrap git --private-key-file /some/path.pem --slient 
```
Fix: #1508

Allow disabling the deploy key prompt for bootstrap git

---

cmd/flux/create_helmrelease.go

Add create target namespace arg to helmrelease cmd

---

.github/workflows/bootstrap.yaml
.github/workflows/e2e.yaml

Add e2e test  to prove that #1554 fixed #1543

Add libgit2 test to bootstrap workflow

---

action/README.md
action/action.yml

Add ARM and ARM64 support to flux GitHub Action

---

cmd/flux/main_test.go

Changes:
- Fix issues introduced in PR#1671 in support fo issue #1658

Remove deprecated io/ioutil usage

---

README.md

Update links to calendar and resources

---

cmd/flux/create_helmrelease.go

Check if helmRelease.Spec.Install is nil

---

cmd/flux/bootstrap_git.go

Set username only when it isn't default

---

manifests/integrations/eventhub-credentials-sync/_base/kubectl-patch.yaml
manifests/integrations/eventhub-credentials-sync/_cronjobs/_base/kubectl-patch.yaml
manifests/integrations/registry-credentials-sync/_base/kubectl-patch.yaml
manifests/integrations/registry-credentials-sync/_cronjobs/_base/kubectl-patch.yaml

Use multi-arch image for kubectl

---

cmd/flux/reconcile.go
cmd/flux/reconcile_with_source.go
cmd/flux/testdata/helmrelease/reconcile_helmrelease_from_git.golden
cmd/flux/testdata/kustomization/reconcile_kustomization_from_git.golden

Add better checks for reconciliation in reconcile run command

---

cmd/flux/logs.go

Filter pods from each deployment for flux logs

---

.goreleaser.yml

This PR adds installation of shell completion script to homebrew formula.

Add shell completion installation to homebrew formula

---

cmd/flux/export.go
cmd/flux/export_test.go
cmd/flux/testdata/export/alert.yaml
cmd/flux/testdata/export/bucket.yaml
cmd/flux/testdata/export/git-repo.yaml
cmd/flux/testdata/export/helm-release.yaml
cmd/flux/testdata/export/helm-repo.yaml
cmd/flux/testdata/export/image-policy.yaml
cmd/flux/testdata/export/image-repo.yaml
cmd/flux/testdata/export/image-update.yaml
cmd/flux/testdata/export/ks.yaml
cmd/flux/testdata/export/objects.yaml
cmd/flux/testdata/export/provider.yaml
cmd/flux/testdata/export/receiver.yaml

Add unit tests for export

---

cmd/flux/tree_kustomization.go

Enable completion for flux tree cmd

---

cmd/flux/main.go

This PR allows users to change the default namespace from `flux-system` to some other value using the `FLUX_SYSTEM_NAMESPACE` environment variable. 
Ref: https://github.com/fluxcd/flux2/discussions/1284

Set default ns with `FLUX_SYSTEM_NAMESPACE` env var

---

cmd/flux/tree_kustomization.go

Given that Flux Kustomizations and HelmReleases can target remote clusters, it is not possible to discover the reconciled resources by just querying the management cluster API. In the future we may want to consider fetching the `kubeConfig` and connect to the remote clusters, but for now we'll just skip the discovery for those Flux CRs.
Fix: #2063

Skip remote clusters in flux tree cmd

---

.github/workflows/bootstrap.yaml
Makefile
tests/image-automation/auto.yaml
tests/image-automation/kustomization.yaml
tests/image-automation/main.go

This PR adds an end-to-end test for image automation using a repository bootstrapped with the default SSH key format ECDSA.
Ref: #2094

Add e2e test for image automation

---

cmd/flux/bootstrap_bitbucket_server.go
go.mod
go.sum
internal/bootstrap/bootstrap_provider.go
internal/bootstrap/provider/factory.go
internal/bootstrap/provider/provider.go

The new command set is:
flux bootstrap bitbucket-server --owner=<project> --username=<user> --repository=<repository name> --hostname=<domain> --token-auth
There is a parity in the capabilities with the other providers.
```
⋊> ~/f/fleet-infra on main ◦ flux bootstrap stash \                                                                                                                                                 17:31:38
--owner=go-git-provider-testing \
--username=fluxcd \
--repository=fleet-infra \
--branch=main \
--path=./clusters/my-cluster \
--hostname=stash.stashtestserver.link:7990 \
--token-auth
► connecting to stash.stashtestserver.link:7990
► cloning branch "main" from Git repository …
```

bootstrap: add BitBucket Server (previously known as Stash) support

---

cmd/flux/bootstrap_bitbucket_server.go
cmd/flux/bootstrap_github.go
cmd/flux/bootstrap_gitlab.go
go.mod
go.sum
internal/bootstrap/bootstrap_plain_git.go
internal/bootstrap/options.go
internal/bootstrap/provider/factory.go
internal/bootstrap/provider/provider.go

bootstrap: Add support for self-signed TLS certs by supplying a custom CA 

---

MAINTAINERS

update Aurel's email

---

manifests/monitoring/grafana/dashboards/control-plane.json

Fix: #2192
Updated this will look like the following:

Removing Kubernetes API Request Duration Graph

---

rfcs/0001-multi-tenancy/README.md

The multi-tenancy implementations described rely on impersonation and
remote apply; to make this RFC stand by itself, those need to be
explained, along with the authorisation model (how Flux "decides" what
it's allowed to do).
This commit adds a summary of the authorisation model, impersonation,
and remote apply, and rejigs the headings a little to make space.

Explain authorisation model and mechanisms

---

internal/bootstrap/bootstrap_provider.go

Use provided SSH hostname to sync with SSH

---

go.mod
go.sum

Update go-git-provider to fix GitLab bootstrap regression bug

---

go.mod
go.sum

Upgrade go-git-providers to v0.5.3

---

.github/runners/prereq.sh

This is required for IAC to run `make test`.

Add pkg-config to arm runners

---

cmd/flux/diff.go
cmd/flux/diff_kustomization.go
cmd/flux/main.go
cmd/flux/main_test.go
internal/build/diff.go

fixes #2365 
If implemented, calling the diff command on kustomization will return 0,
1(if changes are identified), >1 for errors.

Add contextual error code for flux diff kustomization

---

cmd/flux/bootstrap_bitbucket_server.go
cmd/flux/bootstrap_github.go
cmd/flux/bootstrap_gitlab.go

Signed-off-by: Robert Wittman <robkwittman@gmail.com>

Add GPG signing to Github/Gitlab/Bitbucket bootstrap

---

cmd/flux/resume.go
cmd/flux/suspend.go

Use `client.Patch` for suspend/resume operations

---

go.mod
go.sum

Update `fluxcd/pkg/ssa` to v0.13 that contains https://github.com/fluxcd/pkg/pull/234
Fix: #2351

Fix bootstrap CRD wait race condition

---

cmd/flux/create_image_update.go

Add `--git-repo-namespace` arg to allow cross-namespace references in  `ImageUpdateAutomations.sourceRef`.

Add GitRepository namespace arg to `flux create image update`

---

go.mod
go.sum
internal/build/diff.go

If implemented, users will see a spinner run while the diff is on-going.

Add a simple spinner when running flux diff kustomization

---

go.mod
go.sum

fixes #2411 
When fetching a project by name, a list is returned. If implemented, this
will make sure we return the right project from the list.

Bootstrap bitbucket-server: Make sure we retrieve the right project

---

cmd/flux/logs.go

Use text/template library instead of html/template for logs

---

cmd/flux/alert.go
cmd/flux/alert_provider.go
cmd/flux/helmrelease.go
cmd/flux/image.go
cmd/flux/kustomization.go
cmd/flux/object.go
cmd/flux/receiver.go
cmd/flux/reconcile.go
cmd/flux/reconcile_with_source.go
cmd/flux/source.go
cmd/flux/testdata/helmrelease/delete_helmrelease_from_git.golden
cmd/flux/testdata/helmrelease/resume_helmrelease_from_git.golden
cmd/flux/testdata/helmrelease/suspend_helmrelease_from_git.golden
cmd/flux/testdata/kustomization/delete_kustomization_from_git.golden
cmd/flux/testdata/kustomization/resume_kustomization_from_git.golden
cmd/flux/testdata/kustomization/suspend_kustomization_from_git.golden

Use `metadata.Client` for reconcile operations

---

cmd/flux/resume.go

Fixes: #2379 
This pull request changes the `resume` command so that it doesn't wait for reconciliation to finish when resuming many objects(when the `--all` flag is set). The `--wait` flag can be used to make the command wait for reconciliation.

Add `--wait` flag to flux `resume` cmd

---

docs/internal/diagrams.md

Add end-to-end sequence diagrams made with Mermaid for:
- Cluster sync from Git
- Helm release upgrade from Git
- Image update to Git
Ref: https://github.com/fluxcd/website/pull/725

Add e2e sequence diagrams

---

cmd/flux/bootstrap.go
cmd/flux/install.go

Add components-extra example usage to CLI help

---

internal/build/build.go

Fixes #2535
Signed-off-by: Sanskar Jaiswal <jaiswalsanskar078@gmail.com>

Handle secret types properly while masking sops data

---

MAINTAINERS

Ref: https://github.com/fluxcd/community/issues/175

Add Paulo Gomes to maintainer's list

---

cmd/flux/uninstall.go

Followup:
- https://github.com/fluxcd/image-reflector-controller/pull/266
- https://github.com/fluxcd/image-automation-controller/pull/397

Remove image finalizers on uninstall

---

cmd/flux/logs.go

This PR replaces `os.Stdout` with `writer` from `io.Pipe()`, and simplify strings compare with `strings.EqualFold()`
Thanks in advance for your review!
Signed-off-by: TianZong48 [tianzong48@gmail.com](mailto:tianzong48@gmail.com)

logs: write into writer from io.Pipe instead of os.Stdout

---

cmd/flux/create_source_oci_test.go
cmd/flux/main_test.go
cmd/flux/source_oci_test.go
cmd/flux/testdata/oci/create_source_oci.golden
cmd/flux/testdata/oci/delete_oci.golden
cmd/flux/testdata/oci/export.golden
cmd/flux/testdata/oci/export_with_secret.golden
cmd/flux/testdata/oci/get_oci.golden
cmd/flux/testdata/oci/reconcile_oci.golden
cmd/flux/testdata/oci/resume_oci.golden
cmd/flux/testdata/oci/suspend_oci.golden

Add tests for source oci command

---

cmd/flux/testdata/oci/get_oci.golden
go.mod
go.sum
internal/oci/build_test.go
internal/oci/list_test.go
internal/oci/push_pull_test.go
internal/oci/suite_test.go
internal/oci/tag_test.go
internal/oci/testdata/build/deployment.yaml
internal/oci/testdata/build/somedir/repo.yaml

This pull request adds the the flux `<build/list/push/pull/tag> artifact` command

Add test for `flux <verb> artifact` command

---

cmd/flux/logs.go
cmd/flux/logs_test.go
cmd/flux/testdata/logs/all-logs.txt
cmd/flux/testdata/logs/kind.txt
cmd/flux/testdata/logs/log-level.txt
cmd/flux/testdata/logs/multiple-filters.txt
cmd/flux/testdata/logs/namespace.txt
go.mod

Closes: #2949 
Supersedes: #2950

fix log filter and add tests for `flux logs`

---

README.md
rfcs/0002-helm-oci/README.md
rfcs/0003-kubernetes-oci/README.md

To be merged after Flux v0.32.0 release

Status update for RFC-0002 and RFC-0003

---

cmd/flux/main_test.go

This pull request adds more flags to `resetCmdArgs`.
This ensure that flags from one test doesn't affect others.

Reset flag after executing command in tests

---

cmd/flux/list_artifact.go
go.mod
go.sum

Add `--filter-semver` and `--filter-regex` flags to `list artifacts`

---

cmd/flux/version_utils.go

Add version validation to install commands

---

CONTRIBUTING.md
README.md
docs/_redirects
manifests/integrations/eventhub-credentials-sync/_cronjobs/generic/secret-azure-credentials.yaml
manifests/integrations/registry-credentials-sync/aws/config-patches.yaml
rfcs/0002-helm-oci/README.md

update to new doc links structure

---

cmd/flux/source_oci_test.go
cmd/flux/testdata/oci/get_oci.golden

This pull request updates the `get source oci` golden file and uncomments the test

Update golden file for `get source oci`

---

README.md

Part of #3212 
Signed-off-by: Eddie Knight <iv.eddieknight@gmail.com>

Added ArtifactHub badge

---

README.md

Add FOSSA license scanning badge

---

cmd/flux/diff_artifact.go
cmd/flux/diff_artifact_test.go
cmd/flux/testdata/diff-artifact/deployment-diff.yaml
cmd/flux/testdata/diff-artifact/deployment.yaml
cmd/flux/testdata/diff-artifact/success.golden
go.mod
go.sum

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Fixes #3194 
/cc @stefanprodan

Add `diff artifact` command

---

.github/workflows/bootstrap.yaml
.github/workflows/e2e-arm64.yaml
.github/workflows/e2e-azure.yaml
.github/workflows/e2e.yaml
.github/workflows/release-manifests.yml
.github/workflows/release.yaml
.github/workflows/scan.yaml
.github/workflows/update.yaml

Part of #3212 
Each workflow should be tested prior to merging these changes!
Signed-off-by: Eddie Knight <knight@linux.com>

Adjusted workflow permissions

---

.github/workflows/release-manifests.yml
.github/workflows/release.yaml
.github/workflows/scan.yaml

Part of #3212
2 fixes for code placement
1 fix for permissions at top level
Signed-off-by: Eddie Knight <knight@linux.com>

Additional workflow permissions tweaks

---

tests/azure/azure_test.go
tests/azure/util_test.go

Resolves broken e2e tests.
See: https://github.com/fluxcd/flux2/actions/runs/3682732442/jobs/6230612981

Use proper file paths in Azure e2e tests

---

.github/workflows/e2e-arm64.yaml
.github/workflows/e2e-azure.yaml
.github/workflows/e2e-bootstrap.yaml
.github/workflows/e2e.yaml
.github/workflows/release.yaml
.github/workflows/scan.yaml
.github/workflows/update.yaml
CONTRIBUTING.md
Dockerfile
Makefile

Part of https://github.com/fluxcd/flux2/issues/3559

Update Go to 1.20

---

pkg/bootstrap/bootstrap_plain_git.go

Remove all files/subdirs from the directory we are cloning into. This is needed because go-git returns a `repository already exists` error if the directory is non-empty, which is possible since we retry cloning (into the same dir) if the first attempt fails.
before:
```
❯ flux bootstrap git --url=ssh://git@github.com/aryan9600/non-existent-repo.git --branch=main
► cloning branch "main" from Git repository "ssh://git@github.com/aryan9600/non-existent-repo.git"
⚠️  clone failure: unable to clone: repository not found: git repository: 'ssh://git@github.com/aryan9600/non-existent-repo.git'
⚠️  clone failure: unable to clone 'ssh://git@github.com/aryan9600/non-existent-repo.git': repository already exists
✗ failed to clone repository: unable to clone …
```

Clean directory before cloning git repo

---

cmd/flux/reconcile_image_repository.go

Fix: #3840 
Should we start using a completion test routine ?

Fix autocompletion for image repository reconcile

---

.github/workflows/ossf.yaml
README.md

Add OSSF Scorecard

---

cmd/flux/build_artifact.go

fix build_artifact.go typo

---

.github/workflows/e2e-arm64.yaml

[release/v2.2.x] Run conformance tests for Kubernetes v1.29.0

---

pkg/bootstrap/bootstrap_plain_git.go

Just a tiny typo I stumbled upon.

Fix typo in Git bootstrap

---

cmd/flux/uninstall.go

This PR fixes #4551.
Let me know if you believe any test cases are needed (similar to install.go) and I can add them.

Properly detect unexpected arguments during uninstall

---

.github/workflows/backport.yaml
.github/workflows/e2e-arm64.yaml
.github/workflows/e2e-azure.yaml
.github/workflows/e2e-gcp.yaml
.github/workflows/ossf.yaml
.github/workflows/release.yaml

cherry picked from commit 2726da5b856adebfc83925986c462670eaadf66f

build(deps): Update GitHub workflows

---

.github/workflows/e2e-arm64.yaml
.github/workflows/e2e-azure.yaml
.github/workflows/e2e-bootstrap.yaml
.github/workflows/e2e-gcp.yaml
.github/workflows/e2e-openshift.yaml
.github/workflows/e2e.yaml
.github/workflows/release.yaml
.github/workflows/update.yaml

Ref: https://x.com/stefanprodan/status/1780966643201388991

Specifying go version in setup-go github action.

---

.github/workflows/e2e-bootstrap.yaml
Makefile
manifests/scripts/bundle.sh

Use the new `.status.lastPushCommit` to determine if image automation works

ci: Adapt image automation test to v1beta2

---

.github/workflows/backport.yaml
.github/workflows/conformance.yaml
.github/workflows/e2e-bootstrap.yaml
.github/workflows/e2e.yaml
.github/workflows/release.yaml
.github/workflows/scan.yaml

Fixed the token-permission and pinned dependencies issue reported by [scorecard](https://scorecard.dev/viewer/?uri=github.com/fluxcd/flux2).
Part of #4943

fix: fixed GHA token-permission and pinned dependencies issue

---

.github/workflows/conformance.yaml

Part of: https://github.com/fluxcd/flux2/issues/5110

Run conformance tests for Kubernetes 1.32.0

---

.github/workflows/e2e.yaml
cmd/flux/check.go
cmd/flux/testdata/check/check_pre.golden

Sync the Kubernetes active supported versions with https://endoflife.date/kubernetes

Update Kubernetes min supported version to 1.30

---

.github/workflows/conformance.yaml
Dockerfile

Fix kubectl URL and and fix conformance tests for OpenShift min version.

Update flux-cli image

---

Dockerfile

Update kubectl in flux-cli image

---

rfcs/0007-git-repo-passwordless-auth/README.md

a simple correction to the readme

fix: correct name on github app secret

---

rfcs/0008-custom-event-metadata-from-annotations/README.md
rfcs/0009-custom-health-checks/README.md

Part of: #4809
Part of: #5151 
Will merge this right after releasing Flux v2.5.

Update RFC 0008 and RFC 0009 milestones

---

cmd/flux/testdata/trace/deployment-hr-ocirepo.golden
cmd/flux/testdata/trace/deployment-hr-ocirepo.yaml
cmd/flux/trace.go
cmd/flux/trace_test.go

Before:
```
$ flux -n default trace pod default-podinfo-585856f49c-4jl4m
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x10618da70]
goroutine 1 [running]:
main.traceHelm({0x106dd7b28, 0x14000201490}, {0x12f34c0d8, 0x14000783100}, {{0x1400071e130?, 0x1061e7795?}, {0x1400071e109?, 0x1000d9c84?}}, 0x140006a6030)
/home/runner/work/flux2/flux2/cmd/flux/trace.go:404 +0x2f0
main.traceObject({0x106dd7b28, 0x14000201490}, {0x12f34c0d8, 0x14000783100}, 0x140006a6030)
/home/runner/work/flux2/flux2/cmd/flux/trace.go:134 +0x11c
main.traceObjects({0x106dd7b28, 0x14000201490}, {0x12f34c0d8, 0x14000783100}, {0x140006a6040, 0x1, 0x0?})
/home/runner/work/flux2/flux2/cmd/flux/trace.go:112 +0x74 …
```

Fix `flux trace` for HRs from `OCIRepository`s

---

rfcs/0010-multi-tenant-workload-identity/README.md

[RFC-0010] Update RFC to include opt-in feature gate

---

rfcs/0010-multi-tenant-workload-identity/README.md

[RFC-0010] Update RFC feature gate behavior

---

.github/workflows/conformance.yaml
.github/workflows/e2e-bootstrap.yaml
.github/workflows/e2e.yaml
cmd/flux/check.go
cmd/flux/testdata/check/check_pre.golden

Part of: https://github.com/fluxcd/flux2/issues/5363

Set Kubernetes 1.31 as min supported version

---

cmd/flux/build_artifact.go
cmd/flux/diff_artifact.go
cmd/flux/list_artifact.go
cmd/flux/pull_artifact.go
cmd/flux/push_artifact.go
cmd/flux/tag_artifact.go

Promote artifact commands to stable

---

cmd/flux/create_image_policy.go
cmd/flux/image_test.go
cmd/flux/testdata/image/get_image_policy_semver.golden

Depends on: https://github.com/fluxcd/image-reflector-controller/pull/368, https://github.com/fluxcd/image-automation-controller/pull/902
Part of: #4245
Closes: #4244

Add --interval and --reflect-digest flags to flux create image policy

---

rfcs/0010-multi-tenant-workload-identity/README.md

[RFC-0010] Add workload identity support for remote clusters

---

rfcs/0010-multi-tenant-workload-identity/README.md

Part of: #5022
xref: #5447
xref: #4548

[RFC-0010] Add workload identity support for remote generic clusters

---

rfcs/0011-opentelemetry-tracing/README.md

Specification for fluxcd/notification-controller#1097

[RFC-0011] OpenTelemetry Tracing

---

CONTRIBUTING.md
README.md

Add links to source-watcher repo and APIs.

Add source-watcher to docs

---

cmd/flux/migrate.go
cmd/flux/migrate_test.go
cmd/flux/testdata/migrate/file-system/dir.golden/some-file.yaml
cmd/flux/testdata/migrate/file-system/dir/some-file.yaml

Fix `flux migrate -f` not considering kind comments
